### ISSUE TITLE
Better stack traces for Task/Coeval/IO? Possible solutions?

### ISSUE THREAD

**Issue by alexandru** [monix/monix#1015]
For post `3.0.0` lets discuss possible solutions for better stack traces when using `Task` and `Coeval`.

We'll probably avoid thinking about this now, as we are busy with the `3.0.0` release ... but opening this now in order to not forget about it.

**Comment by mosteli** [comment]
@alexandru 
Are there any plans for when this might be implemented or otherwise?
I am wondering as this is marked for 3.1.0 though that has already been released. 
Apologies if there is recent discussion around this that I missed.

**Comment by Avasil** [comment]
@mosteli 

I don't know if @alexandru had any progress with it but from my side, I might have some free time to port Cats IO implementation in the second half of October. I would really like to have stack traces available and released this year.

**Comment by mosteli** [comment]
@Avasil That would be awesome. Thanks for the reply.

**Comment by Avasil** [comment]
@mosteli 
I actually found time now and opened a PR: https://github.com/monix/monix/pull/1267

Feedback would be very helpful :)
