### ISSUE TITLE
Are monix operators thread safe?

### ISSUE THREAD

**Issue by Ben-Barron** [monix/monix#1019]
Are the monix operators thread safe or do we need to call `.observeOn()` to get them onto the same Scheduler?

I have a series of Observables that are basically wrapping library callback registrations, so I don't have control about which thread `onNext()` is called on. If I was working in RX.NET, when it comes to merging these Observables you'd `.synchronize()` to get them on the same thread as the operators are not thread safe. Do we need to do something similar in monix?

Referring to version 2.x

**Comment by Avasil** [comment]
By default `onNext` is not thread safe, see https://monix.io/docs/3x/reactive/observers.html#contract

You can use `ConcurrentSubject` which allows concurrent `onNext` calls and no synchronization is needed. Alternatively, `Observable.create` is also safe in this regard.

If you're asking about operators in general (like `mergeMap`) then I don't think you need anything like `observeOn` but an example would clear a lot if my answer doesn't fully cover your question

**Comment by Avasil** [comment]
I'm closing it but feel free to ask further questions if you'd like me to clarify or expand on anything
