### ISSUE TITLE
Monix 3.0 Release is not backward compatible with cats-effect 1.4.0

### ISSUE THREAD

**Issue by YulawOne** [monix/monix#1042]
Simple app:
build.sbt
```scala
name := "monix-test"
version := "0.1"
scalaVersion := "2.12.10"

val CatsVersion = "1.6.1"
val CatsEffectVersion = "1.4.0"
val MonixVersion = "3.0.0"

dependencyOverrides ++= Seq(
  "org.typelevel" %% "cats-core" % CatsVersion,
  "org.typelevel" %% "cats-effect" % CatsEffectVersion
)

libraryDependencies ++= Seq(
  "io.monix" %% "monix" % MonixVersion
)
```

```scala
import monix.catnap.MVar
import monix.eval.Task

object CatsCompatibilityTest extends App {
  MVar[Task].empty[Unit]()
}
```

if run main, it produces:
```scala
Exception in thread "main" java.lang.NoSuchMethodError: cats.effect.ContextShift.$init$(Lcats/effect/ContextShift;)V
	at monix.eval.TaskContextShift$$anon$8.<init>(Task.scala:4760)
	at monix.eval.TaskContextShift.<init>(Task.scala:4760)
	at monix.eval.TaskParallelNewtype.<init>(Task.scala:4732)
	at monix.eval.TaskInstancesLevel0.<init>(Task.scala:4685)
	at monix.eval.TaskInstancesLevel1.<init>(Task.scala:4627)
	at monix.eval.Task$.<init>(Task.scala:2492)
	at monix.eval.Task$.<clinit>(Task.scala)
	at CatsCompatibilityTest$.delayedEndpoint$CatsCompatibilityTest$1(CatsCompatibilityTest.scala:5)
	at CatsCompatibilityTest$delayedInit$body.apply(CatsCompatibilityTest.scala:4)
```

From my observation, this happens due ContextShift trait was changed from pure interface to interface with default methods:
before:
```scala 
trait ContextShift[F[_]] {
  def shift: F[Unit]
  def evalOn[A](ec: ExecutionContext)(fa: F[A]): F[A]
}
```
now:
```scala
trait ContextShift[F[_]] {
  def shift: F[Unit]
  def blockOn[A](blocker: Blocker)(fa: F[A]): F[A] =
    evalOn(blocker.blockingContext)(fa)
  def evalOn[A](ec: ExecutionContext)(fa: F[A]): F[A]
}
```

**Comment by Avasil** [comment]
@YulawOne I have investigated a bit and arrived at the following results: https://github.com/Avasil/cats-effect-bincompat

Basically configuration like:
```
lazy val core = project
  .settings(libraryDependencies += "org.typelevel" %% "cats-effect" % "2.0.0")

lazy val child = project
  .settings(dependencyOverrides += "org.typelevel" %% "cats-effect" % "1.4.0")
  .dependsOn(core)
```
where `core` is `Monix` would require *forward* compatibility ( https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html ) to run a new version in a project using the old one. 

I'm not an expert on binary compatibility so I could be mistaken, perhaps @alexandru knows more or we could raise it in `cats-effect` repo.

I included few other combination that should work. If your use case require exactly your configuration then you could try Monix `3.0.0-RC5` which is almost the same as `3.0.0`: https://github.com/monix/monix/releases

`3.0.0` is binary compatible with `3.0.0-RC5` on Scala 2.12 so I think you could upgrade library A for `3.0.0-RC5` with Cats-Effect 1.3, have library B on Monix `3.0.0` and project C depending on both without any issues. If that's not the case, please let us know.

**Comment by YulawOne** [comment]
>  I have investigated a bit and arrived at the following results:

for 2-4 case eviction rules are working and 2.0.0 will be used in runtime, that is not desired as our project has dependency on doobie 0.5.x which we cannot upgrade on 0.8.x right now due significant breaking changes (doobie 0.5 require cats 1.x and cats-effect 1.x)

> 3.0.0 is binary compatible with 3.0.0-RC5 on Scala 2.12 so I think you could upgrade library A for 3.0.0-RC5 with Cats-Effect 1.3, have library B on Monix 3.0.0 and project C depending on both without any issues. If that's not the case, please let us know.

Same here, the latest cats-effect version will be in runtime (as both versions cannot co-exists in classpath) which will break doobie.

> If your use case require exactly your configuration then you could try Monix 3.0.0-RC5 which is almost the same as 3.0.0

If @alexandru doesn't see any way for monix 3.0.0 to run on cats-effect 1.4, I think we will use RC5 for now, hopefully there is no bugs.

*off-topic*

As I mentioned in Gitter, for me this issue seems as a big adoption issue for cats/cats-effect, where people are forced to upgrade all libraries dependent on cats/cats-effect in one go or not to upgrade at all. 
- 1st case is often not possible due different adoption speed for different libraries or even due to certain issue in user codebase which block some libraries from upgrade (like our case). 
- 2nd case might force user to stay with buggy or vulnerable version or even force to change stack away from  cats

**Comment by Avasil** [comment]
> has dependency on doobie 0.5.x which we cannot upgrade on 0.8.x right now due significant breaking changes (doobie 0.5 require cats 1.x and cats-effect 1.x)

> Same here, the latest cats-effect version will be in runtime (as both versions cannot co-exists in classpath) which will break doobie.

Isn't it cats-effect 0.10? 
According to: https://github.com/tpolecat/doobie/blob/series/0.5.x/build.sbt#L10
And then fs2: https://github.com/functional-streams-for-scala/fs2/blob/series/0.10/build.sbt#L215

I would expect Cats-Effect `2.0` to work fine if your doobie version uses `1.x`

> If @alexandru doesn't see any way for monix 3.0.0 to run on cats-effect 1.4, I think we will use RC5 for now, hopefully there is no bugs.

I think the only difference is cats version. It will diverge in the future, we can backport fixes of course but hopefully we will figure out the root issue

**Comment by YulawOne** [comment]
> I would expect Cats-Effect 2.0 to work fine if your doobie version uses 1.x
I will try to do it. 2

**Comment by Avasil** [comment]
What are incompatibilities you encounter when running doobie with Cats-Effect 2.0? Is it only about `ContextShift`?

**Comment by alexandru** [comment]
This looks to be a Cats-Effect 2.0 issue 😐

I thought it preserved binary compatibility with 1.4, but apparently it doesn't.

**Comment by alexandru** [comment]
And I have no idea why this happens btw. That changed looked to be safe. Don't those traits use Java's default methods anyway?

**Comment by YulawOne** [comment]
> What are incompatibilities you encounter when running doobie with Cats-Effect 2.0? Is it only about ContextShift?

I'm testing this atm, so far it looks like doobie has no issues with cats-effect 2.0 and cats 2.0. I need to migrate one more project to understand that everything is fine. I hope to finish it by EOD

> And I have no idea why this happens btw. That changed looked to be safe. Don't those traits use Java's default methods anyway?

I believe Scala is not always can compile in Java's default method, it's might be related to anonymous classes

**Comment by Avasil** [comment]
@YulawOne Any update on this? Did you manage to make it work or are there issues that we could help with?

**Comment by YulawOne** [comment]
@Avasil Sorry, I had to switch on other tasks and had to postpone migration. So far we manage to migrate one module, however, it's just small codebase and I can't say surely that that was a total success. I hope I would be able to switch back on migration soon.

**Comment by YulawOne** [comment]
@Avasil I finally managed to migrate our main codebase on 3.1.0 and so far it works with doobie 0.5.4 without any issues and our integration tests haven't spotted any class resolution issues.

**Comment by Avasil** [comment]
Awesome @YulawOne I'm very glad to hear

I will close the issue then but of course feel free to reopen in case you spot anything
