### ISSUE TITLE
Observable#mapParallel could cancel earlier

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1045]
If any concurrent `Task` fails we don't cancel immediately:

https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/MapParallelUnorderedObservable.scala#L101

We send the error downstream so it will reply with `Stop` on the next completed `Task`:
https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/MapParallelUnorderedObservable.scala#L108

And then it cancels. I think we could do it earlier, during the first error. The same applies to `mapParallelOrdered` .

cc @alexandru in case it is desired for some reason

**Comment by TapanVaishnav** [comment]
Hi @Avasil 
I'd like to take on this one.

**Comment by Avasil** [comment]
Fantastic, nice to see you again @TapanVaishnav - let me know if you have any questions!

**Comment by TapanVaishnav** [comment]
@Avasil Just to be sure,
https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/MapParallelUnorderedObservable.scala#L101
If we are calling `self.onError`, then as per the observer contract it won't allow any further calls to occur, right? So the only thing(as per my understanding) to cancel the process immediately, is to add `composite.cancel()` in the error scope.
Am I thinking in the right direction, can you check a bit?

**Comment by Avasil** [comment]
> If we are calling self.onError, then as per the observer contract it won't allow any further calls to occur, right?

Correct

> So the only thing(as per my understanding) to cancel the process immediately, is to add composite.cancel() in the error scope.

Yes, I feel like it should be enough

**Comment by TapanVaishnav** [comment]
@Avasil Hi, Thanks for your reply. Also, please have a look at the pr when you have time.
