### ISSUE TITLE
Add method onProtect to CircuitBreaker

### ISSUE THREAD

**Issue by jakubjanecek** [monix/monix#1067]
Hello,
we've been using `CircuitBreaker` and we often enrich it with extra features such as logging and metrics. Methods such as `onClose` and `onOpen` are very useful for that however we are missing method called `onProtect` that would allow us to count the number of requests going through the circuit breaker. Would that be something that could be added? If yes we are ready to prepare a PR for that. Please let us know whether we should make the effort.

Thank you.

**Comment by Avasil** [comment]
I haven't used `CircuitBreaker` but it indeed seems useful.
Would it fire always or only on "accepted" tasks?

Any thoughts @oleg-py @alexandru ?

**Comment by jakubjanecek** [comment]
I think it should fire always and be called before the protected code block. That way you can for example count number of requests going through the circuit breaker and thanks to having `onRejected` you know how many got through and how many were rejected.
