### ISSUE TITLE
CircuitBreaker shoud change state to Open when reset attempt was canceled

### ISSUE THREAD

**Issue by kostousov-ds** [monix/monix#1080]
https://github.com/monix/monix/blob/b10210bd30c43b95265c818537c24098cbbcab05/monix-catnap/shared/src/main/scala/monix/catnap/CircuitBreaker.scala#L361

In previous step CB's state was set to `HalfOpen`. When task was canceled the state wasn't changed (see CircuitBreaker.scala#L361). In the HalfOpen state CB doesn't try to check F status.

It's look like a bug

**Comment by mikkka** [comment]
Minimal example is the following:

object MonixCB extends TaskApp {
  override def run(args: List[String]): Task[ExitCode] = {
    case object SomeError extends Exception("realcall oops")
    case object TO extends TimeoutException("timeout in call") with NoStackTrace

    def method(x: Int): Task[String] =
      if (x == 0) Task.raiseError(SomeError)
      else  Task.sleep(2.second) *> Task.cancelBoundary *> Task(x.toString)

    val scenario = for {
      cb       <- CircuitBreaker.of(0, 5.second)
      _        <- cb.protect(method(0)).onErrorFallbackTo(Task("first"))
      _        <- Task.sleep(7.second)
      _        <- cb.protect(method(1)).timeoutWith(1.second, TO).onErrorFallbackTo(Task("second"))
      _        <- cb.protect(method(1))
      cbState  <- cb.state
    } yield cbState

    scenario.map(println).as(ExitCode.Success)
  }
}

**Comment by mikkka** [comment]
Minimal example is the following:

object MonixCB extends TaskApp {
  override def run(args: List[String]): Task[ExitCode] = {
    case object SomeError extends Exception("realcall oops")
    case object TO extends TimeoutException("timeout in call") with NoStackTrace

    def method(x: Int): Task[String] =
      if (x == 0) Task.raiseError(SomeError)
      else  Task.sleep(2.second) *> Task.cancelBoundary *> Task(x.toString)

    val scenario = for {
      cb       <- CircuitBreaker.of(0, 5.second)
      _        <- cb.protect(method(0)).onErrorFallbackTo(Task("first"))
      _        <- Task.sleep(7.second)
      _        <- cb.protect(method(1)).timeoutWith(1.second, TO).onErrorFallbackTo(Task("second"))
      _        <- cb.protect(method(1))
      cbState  <- cb.state
    } yield cbState

    scenario.map(println).as(ExitCode.Success)
  }
}

**Comment by tomasherman** [comment]
can someone confirm this? im investigating a error in our cluster where CB gets stuck in half-open state sometimes, i wonder if this could be it

**Comment by tomasherman** [comment]
in the scenario above, is there any way for CB to recover and ever get opened/closed again?

**Comment by Avasil** [comment]
Thanks for the detailed report, I will look into it in the following days (probably on Saturday)

**Comment by mikkka** [comment]
@tomasherman no, it can't

**Comment by tomasherman** [comment]
ok so it looks like i finally tracked down the issue - or rather - you guys did ... thank you so much! if there is anything i can do to help fix this i will

**Comment by Avasil** [comment]
@tomasherman 

> ok so it looks like i finally tracked down the issue - or rather - you guys did ... thank you so much! if there is anything i can do to help fix this i will

Pull Request or bug investigation is of course very welcome but unfortunately I don't have any tips until I have a time to look at this closer, I'm not familiar with `CircuitBreaker` implementation.

**Comment by tomasherman** [comment]
So we played around with this and we can verify that this bug exists - when the half-opened task is canceled, CB becomes dead.

I wonder if some failsafe mechanism could be introduced that would always close circuitbreaker after some time no matter what happens to give it a chance to recover

**Comment by Avasil** [comment]
I have finally taken a look at this and potential fix is easy but I'm not yet sure what should happen if the task is canceledin half-open state, I see at least 3 options:
- Close `CircuitBreaker` (treat it as a success)
- Open with a new timeout (treat it as a failure)
- Open without resetting the timeout (the next task will attempt to close it)

I suppose 3rd option looks the best but I am curious about your opinions

**Comment by tomasherman** [comment]
so for me, both 1 and 3 is acceptable - with 3 being optimal

**Comment by Avasil** [comment]
I implemented a 3rd option and created a snapshot which includes the fix: `3.2.0-eb5e5c7-SNAPSHOT`

**Comment by Avasil** [comment]
I merged my fix but feel free to open if you discover that it's not fully fixed in the snapshot version (not sure when we release `3.2.0`, I'd like to close few more issues before that)
