### ISSUE TITLE
Observable getting stuck when consumed with failed Task

### ISSUE THREAD

**Issue by TVerse** [monix/monix#1105]
I've noticed some strange behaviour when consuming Observables with failing Tasks. The first snippet will will print "1", then the stack trace through the scheduler's uncaught exception handler, and then get stuck until `runSyncUnsafe`'s timeout, and print the `TimeoutException` in the catch block:
```scala
try {
  Observable(1, 2, 3)
    .consumeWith {
      Consumer.foreachTask { i =>
        if (i == 2) Task.raiseError(new RuntimeException("ERROR: " + i.toString))
        else Task(println(i))
      }
    }
    .runSyncUnsafe(5.seconds)
} catch {
  case NonFatal(e) => println("CAUGHT: " + e.getMessage)
}
```
What I would expect to happen instead, is the consumer completing early with the raised exception. The following two snippets do have the correct behaviour, but are not substitutes for the original snippet. This one `flatMap`'s an observable instead:
```scala
try {
  Observable(1, 2, 3)
    .flatMap { i =>
      if (i == 2) Observable.raiseError(new RuntimeException("ERROR: " + i.toString))
      else Observable.fromTask(Task(println(i)))
    }
    .consumeWith(Consumer.complete)
    .runSyncUnsafe(5.seconds)
} catch {
  case NonFatal(e) => println("CAUGHT: " + e.getMessage)
}
```
And this one throws an exception instead of returning a failed Task:
```scala
try {
  Observable(1, 2, 3)
    .consumeWith {
      Consumer.foreachTask { i =>
        if (i == 2) throw new RuntimeException("ERROR: " + i.toString)
        else Task(println(i))
      }
    }
    .runSyncUnsafe(5.seconds)
} catch {
  case NonFatal(e) => println("CAUGHT: " + e.getMessage)
}
```

It seems to be related the the `ForeachAsyncConsumer`. There is an `onError` method, which will signal `Stop` if an error is thrown from `onNext`. However, if the error is not thrown but instead returned in the `Future[Ack]` from `onNext`, the observable never completes and gets stuck until timed out.

**Comment by Avasil** [comment]
Thank you for detailed report!

I think you are right, it is also not consistent with `mapEval`

I think we should use `redeem` instead of `map` here: 
https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/consumers/ForeachAsyncConsumer.scala#L44

Are you interested in making a PR?

**Comment by TVerse** [comment]
I will give it a shot, good chance to learn the Monix internals a bit better. I'll update once I have something.

**Comment by Avasil** [comment]
I am happy to help If you get stuck and have any questions

**Comment by Avasil** [comment]
@TVerse 
Anything I can help with? 
I would like to include it in `3.2.0` which I hope to release within a month 
Let me know if you don't have time or lost interest and I will implement the fix :D

**Comment by TVerse** [comment]
Sorry, I had much less time than I thought and got very distracted. If you could implement that'd be great. Sorry for missing your comment as well.

**Comment by paualarco** [comment]
will give it a try :)
