### ISSUE TITLE
withFilter support for Observable

### ISSUE THREAD

**Issue by mantasindrasius** [monix/monix#1109]
Hey,

in my team we are using more of the Monix library in our day-to-day work. However, one annoying issue is popping up that Observable does not contain `.withFilter` method, which means that we cannot use `if` keyword in for-comprehension.

I.e. we would like to have support for this:

```scala
val adultsObservable = for {
  adult <- peopleObservable if person.age >= 18
} yield adult
```

Currently we need to write it as:

```scala
val adultsObservable = for {
  adult <- peopleObservable.filter(_.age >= 18)
} yield adult
```

Are there plans to support it and, if no, what's the reason?

**Comment by Avasil** [comment]
Hi @mantasindrasius - thanks for raising the issue

I'm not aware if it's intended or not, I vaguely recall there are some problems with `withFilter` but quick test looks alright to me.

Although I wonder why I don't see it implemented in any other streaming library, probably streams in for comprehension are not very common

**Comment by oleg-py** [comment]
I'd say we should do this, for both Observable and Iterant. There's no reason not to if we already have `filter`.

It's probably a bit annoying to implement if you want to do it in a conventional way - most Scala collections create a `WithFilter` wrapper that has only map/flatmap/filter/foreach that is lazy and composed chained calls to `filter` together. Not sure if we should do this, given that Observable/Iterant are already lazy, but it might be worth it for performance.

**Comment by Avasil** [comment]
Ok, let's do it then!

@mantasindrasius are you interested in making a PR?

**Comment by alexandru** [comment]
@oleg-py 

> It's probably a bit annoying to implement if you want to do it in a conventional way - most Scala collections create a WithFilter wrapper that has only map/flatmap/filter/foreach that is lazy and composed chained calls to filter together. Not sure if we should do this, given that Observable/Iterant are already lazy, but it might be worth it for performance.

Scala collections do that because they are strict. No need to do it for `Observable` since it already does that for regular `map`/`flatMap`/`filter`.

**Comment by mantasindrasius** [comment]
@Avasil I may try

**Comment by Avasil** [comment]
@mantasindrasius 
Sorry I'm trying to clean up some issues in preparation for the next release and I have just created a PR with it 25 mins ago (probably the reason Alex noticed the issue :D)

but if you're interested in contributing then I have just created https://github.com/monix/monix/issues/1130 and I have lots of simple issues in https://github.com/monix/monix-bio

**Comment by mantasindrasius** [comment]
Np :) Since I've started already, will do a PR to Iterant.

**Comment by mantasindrasius** [comment]
https://github.com/monix/monix/pull/1132
