### ISSUE TITLE
Add Task.parSequence and Task.parTraverse aliases

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1130]
Task.parSequence = Task.gather
Task.parTraverse = Task.wander

**Comment by alexandru** [comment]
I'm starting to dislike the proliferation of aliases in Monix.

WDYT? Should we deprecate the old names? We'll keep them for binary compatibility of course.

**Comment by Avasil** [comment]
I'm fine with deprecation in this example.
I suppose we should add `parXXXUnordered` and `parXXXN` as well?
I think in Cats it's called `parUnorderedTraverse` but we use `wanderUnordered` and `wanderN`

1. If we are consistent with ourselves:
`parTraverse`, `parTraverseN`, `parTraverseUnordered`

2. If we are consistent with Cats:
`parTraverse`, `parTraverseN`, `parUnorderedTraverse`

It's unfortunate but I would go with 1 because discoverability seems to be better

**Comment by jozic** [comment]
+1 for `parTraverseUnordered`

**Comment by jozic** [comment]
I'll take this if no objections
