### ISSUE TITLE
Release for ScalaJS 1.0.x

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1131]
Cats-Effect has PR with a support for new ScalaJS, we can probably copy it https://github.com/typelevel/cats-effect/pull/753

**Comment by alexandru** [comment]
We probably need to wait for Cats-Effect to release first, right?

**Comment by Avasil** [comment]
@alexandru ScalaJS 1.0.0-RC2 is included in Cats-Effect 2.1.x but only for Scala 2.12 and 2.13
https://mvnrepository.com/artifact/org.typelevel/cats-effect

Oleg has created a PR with an upgrade: https://github.com/monix/monix/pull/1117

**Comment by Avasil** [comment]
@alexandru 
We are currently blocked by `minitext` and `implicitbox` only
Would you mind doing releases for these libraries?

**Comment by Avasil** [comment]
ScalaJS support has been added in https://github.com/monix/monix/pull/1157 but I will leave the issue open until the release

**Comment by trywe-ltd** [comment]
Any ETA on a new release including this update?

**Comment by adamw** [comment]
@trywe-ltd I think 3.2.1 contains this

**Comment by Avasil** [comment]
Yes, hopefully without any issues now :D

**Comment by ssaleem-ee** [comment]
Thanks @Avasil - that is great news! 👍
