### ISSUE TITLE
Improve the documentation grammar in some places

### ISSUE THREAD

**Issue by fnqista** [monix/monix#1148]
Some documentations are unclear - the most noticeable are the missing usages of the word "the", and in general others are unclear in the way the sentence is constructed.

**Comment by fnqista** [comment]
I'm a new fan and a prospective contributor - first I will try to improve the documentation on Observables.

**Comment by Avasil** [comment]
That's fantastic @fnqista and very appreciated. :)
I plan to overhaul many docs in April so please feel welcome to share any suggestions about anything (confusing explanation, missing examples etc.) whenever you encounter it and I will make sure to address it.

**Comment by fnqista** [comment]
I should have linked this issue in monix.io - I will just close this since I have submitted a PR also on the monix.io repo
