### ISSUE TITLE
New consumer builder `.seq` for `Consumer` companion object

### ISSUE THREAD

**Issue by paualarco** [monix/monix#1151]
Would be nice to have the `.seq` signature as a builder for `Consumer`.
I guess there are some reasons why this is has not being implemented yet but  in my opinion would be worth having it. (I find very handy the equivalent in akka streams `Sink.seq`)

**Comment by Avasil** [comment]
> I guess there are some reasons why this is has not being implemented yet but in my opinion would be worth having it.

I don't think there is a specific reason other than no one bringing it up before. 
The use case is covered (`toListL`) but I wouldn't mind seeing it on `Consumer`

**Comment by paualarco** [comment]
@Avasil how does it seem to you? I have reused the already existing `FoldLeftConsumer`
