### ISSUE TITLE
Observable.fromInputStream emits bytes whose length is less than the chunkSize

### ISSUE THREAD

**Issue by fnqista** [monix/monix#1154]
Not sure if this is a bug or is intended, but using `Observable.fromInputStream` (and its variants) emits bytes whose length is less than the `chunkSize` in a situation like below:

- `InputStream` actually has **more** bytes to stream than the `chunkSize`
- `InputStream.read` results in bytes streamed **less** than the `chunkSize` in `monix.reactive.internal.builders.InputStreamObservable` (an internal Monix class)

Coming from the standpoint of the official API of `InputStream.read`, nothing is violated:

> public int read(byte[] b)
         throws IOException

> Reads some number of bytes from the input stream and stores them into the buffer array b. The number of bytes actually read is returned as an integer. This method blocks until input data is available, end of file is detected, or an exception is thrown.

> If the length of b is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at the end of the file, the value -1 is returned; otherwise, at least one byte is read and stored into b. 

This contract has existed for a long time and is an accepted fact.

However, there are situations when one wants to fill the given buffer even though `InputStream.read` cannot - by continuously calling it until the buffer is fiiled - or - the stream is exhausted.

Now, if the original intention of `Observable.fromInputStream` is to fill the `chunkSize`, there needs to be made some fixes to `monix.reactive.internal.builders.InputStreamObservable` to continuously read from the `InputStream` until the buffer is filled or the stream ends - otherwise, I am suggesting a variant of this method that does so.

As a motivating example, I was trying to download a 10 Gb file from a Hadoop HDFS file system and split it into size 1 GB each, so I used `Observable.fromInputStream(Task(<hdfsInputStream>), chunkSize = 1e9)`, but each emission from `Observable.fromInputStream` is actually only of size 65KB instead of `chunkSize` (1 GB). I had to roll out my own `InputStreamObservable` implementation to continuously read from the `InputStream` until it hits the `chunkSize` given.

Thoughts?

**Comment by fnqista** [comment]
I am now pretty convinced this is a bug. Reading from an input stream must be done in a loop, otherwise it won't fill the given buffer, rendering it pointless.

**Comment by Avasil** [comment]
I agree it is surprising behavior and could be improved but I need to brush up on `InputStream` to be sure

Could you show your implementation?

**Comment by fnqista** [comment]
Sure. In `InputStreamObservable.fastLoop`, the part where it reads the input stream:

`val length = blocking(fillBuffer(in, buffer))` // instead of the old `in.read`...

In `fillBuffer`:

```
@tailrec
  private def fillBuffer(in: InputStream, buffer: Array[Byte], bytesRead: Int = 0): Int = {
    if (bytesRead >= buffer.length) bytesRead                 // buffer is filled
    else {
      val batchRead = in.read(buffer, bytesRead, buffer.length - bytesRead)
      if (batchRead > 0)                 // stream is not exhausted 
                                         // and we read something, recurse to fill the buffer
        fillBuffer(in, buffer, bytesRead + batchRead)
      else {                            // stream has ended
        if (bytesRead <= 0)             // we read nothing, just return an EOF
          -1                            // stops the observable
        else                           // we read something
          bytesRead                    // return the bytes we read first
      }
    }
  }
```

I did recursion because I think it was cool, but a normal while loop would also suffice. I am also not sure if it is best to use nested if-else for readability or just use pattern matching on the ints.

I hope it illustrates the point, though.

**Comment by fnqista** [comment]
@Avasil I have time to do this, submitting a PR.
I used a property test to validate - please review when you have time.
