### ISSUE TITLE
Debugging support - reify the subscription tree somehow

### ISSUE THREAD

**Issue by dvtomas** [monix/monix#116]
It would be just fantastic If there was a way to ask an (already subscribed) observable for a chain of (upstream) producers it is subscribed to, and a tree of (downstream) subscribers that are subscribed to it, and perhaps even give some string names to intermediate observables for debugging purposes, that would be just fantastic. It is very hard to tell what's going on in large observable chains and how are they composed.

I wish I could do something like

``` scala
val ticksSource = Observable.interval(10.milli).map(_.toString).share.name("Time ticks")
val o2 = ticksSource. .... .name("o2")
val o3 = tickSource. ... .name("o3")
o2.subscribe(...))
o3.subscribe(...)
```

``` scala
ticksSource.debugAncestorsChain
```

would print something the chain of upstream ancestors, like

```
interval("100 milli")
map
share
name("Time ticks")
```

``` scala
ticksSource.debugOffsprings
```

would print the whole tree of downstream subscribers, something like

```
|
+   ...
|   name("o2")
+   ...
    name("o3")
```

Methods that would return the chain of ancestors and the tree of offsprings, and some methods for getting a user-friendly description of an observable would be awesome.

**Comment by alexandru** [comment]
This is a little incompatible with the `Observable` model and in general debugging can work with simpler tools like `.dump`. Will close this for now.
