### ISSUE TITLE
Prepending  an element to an Observable before zipping it with another Observable causes a non-deterministic result.

### ISSUE THREAD

**Issue by wjlow** [monix/monix#1164]
## Versions

JDK: 11
Monix: 3.1.0
Scala: 2.13.1
SBT: 1.3.10

## How to reproduce

I have a project with running code that you can run and reproduce the problem I am facing: https://github.com/wjlow/observable-prepend

This piece of code results in non-deterministic output. 

```scala
import cats.effect.ExitCode
import monix.eval.{Task, TaskApp}
import monix.reactive.Observable

object Main extends TaskApp {
  override def run(args: List[String]): Task[ExitCode] = {
    intermittentFailure.flatMap(x => Task(println(x.mkString("\n")))).map(_ => ExitCode.Success)
  }

  // This is where the problem is
  def intermittentFailure: Task[List[(Int, Int)]] = {
    val streamA = 0 +: Observable(1, 2, 3)
    val streamB = Observable(0, 1, 2, 3)
    streamA.zip(streamB).toListL
  }
}
```

Sometimes, the output is incorrect: 

```
(0,0)
(2,1)
(3,2)
```

Other times, the output is as expected:

```
(0,0)
(1,1)
(2,2)
(3,3)
```

## Additional comments

It looks like replacing `0 +: Observable(1, 2, 3)` with `Observable(Observable(0), Observable(1, 2, 3)).concat` fixes the non-determinism and gives the expected output.

**Comment by alexandru** [comment]
Yikes, this doesn't sound good.
