### ISSUE TITLE
Observable.fromIterator(Task) does not close file

### ISSUE THREAD

**Issue by alexandru** [monix/monix#1183]
We are doing this:

```scala
def fromIterator[A](task: Task[Iterator[A]]): Observable[A] =
  Observable.fromTask(task.map(fromIteratorUnsafe)).flatten
```

This is wrong. Because the `Task` acts as a factory, the `Observable` should be in charge of closing the file.

**Comment by Avasil** [comment]
There's no `close` on `Iterator`
