### ISSUE TITLE
Support merging observables

### ISSUE THREAD

**Issue by ctoomey** [monix/monix#1202]
We're using the monix reactive library and love it, thanks!

One of the needs we currently have is to [merge](http://reactivex.io/documentation/operators/merge.html) multiple observables into 1, and more particularly using priorities assigned to the observables, such that the merged observable emits elements from the highest-priority source when multiple sources have new elements available. An example of this feature in akka-streams is [Source.combine](https://doc.akka.io/api/akka/current/akka/stream/scaladsl/Source$.html#combine[T,U](first:akka.stream.scaladsl.Source[T,_],second:akka.stream.scaladsl.Source[T,_],rest:akka.stream.scaladsl.Source[T,_]*)(strategy:Int=%3Eakka.stream.Graph[akka.stream.UniformFanInShape[T,U],akka.NotUsed]):akka.stream.scaladsl.Source[U,akka.NotUsed]) using [MergePrioritized](https://doc.akka.io/api/akka/current/akka/stream/scaladsl/MergePrioritized.html).

I'm envisioning at 2 flavors, a plain, unprioritized merge, and a prioritized one. Is this functionality something you're receptive to incorporating if I contribute an implementation?

**Comment by Avasil** [comment]
> I'm envisioning at 2 flavors, a plain, unprioritized merge, and a prioritized one. Is this functionality something you're receptive to incorporating if I contribute an implementation?

Of course, it will be much appreciated!

We already have a plain merge but a prioritized one would be useful. I would also like to see a merge with limited parallelism (https://github.com/monix/monix/issues/1139)

**Comment by ctoomey** [comment]
@Avasil I'd overlooked the `merge` as I embarassingly didn't grok it's signature and so didn't realize it was doing what I was looking for.

After looking at the code though I see that it doesn't support the normal consumer-driven back-pressure and instead returns immediate `Ack`s upstream and buffers elements per the given `OverflowStrategy`. For our use case we want the normal consumer-driven back pressure, and the closest we can get would be using the `BackPressure` overflow strategy. But that requires a minimum buffer of size 2 and so still wouldn't do what we want. Curious, why isn't a buffer size of 1 allowed?  And even if it were, the implementation would still send an immediate `Ack` upstream, right?

Also for our use case all the producer observables are known/available at startup, like `combineLatestList`. In fact since that method implements normal consumer-driven back pressure, I was able to implement my `mergePrioritized` pretty easily by copying/modifying `combineLatestList`'s implementation and using a priority queue for buffering. Would a companion object method such as this (taking list of producer observables and implementing normal consumer-driven back pressure) still be of interest?

I looked at supporting a prioritized variant of the existing `merge` but that's a whole lot more work given the variety of `OverflowStrategy`s that would have to be supported, so that's not something I can sign up for.

**Comment by Avasil** [comment]
> Curious, why isn't a buffer size of 1 allowed?

I don't remember exactly but I recall that it's an implementation detail (sth about JS and JCTools queues) - I just asked @alexandru about it and we could probably add a specialized implementation for this case. It's a quite common request

> And even if it were, the implementation would still send an immediate Ack upstream, right?

No, it should back-pressure the source until there is a space in the buffer. 

> Also for our use case all the producer observables are known/available at startup, like combineLatestList. In fact since that method implements normal consumer-driven back pressure, I was able to implement my mergePrioritized pretty easily by copying/modifying combineLatestList's implementation and using a priority queue for buffering. Would a companion object method such as this (taking list of producer observables and implementing normal consumer-driven back pressure) still be of interest?

Sure, a version with fixed number of observables is useful too. Maybe it won't be too far from "dynamic" one. If you can open a PR with what you have right now, I would love to take a look

**Comment by alexandru** [comment]
For JavaScript the issue is definitely that we used an [circular buffer](https://en.wikipedia.org/wiki/Circular_buffer) that sacrifices one element out of the internal array.

There's also the issue that JCTools allocates queues with sizes as powers of 2, so we can allocate 1, 2, 4, 8, 16, ... elements. I don't remember atm if it lets you allocate just 1 element, I think some implementations have issues with queues of 1 element. Plus our JavaScript implementation has to be consistent with the JVM implementation, so if we allocate sizes as powers of 2, then we have to ensure that works consistently on both implementations.

In the grand scheme of things it's wrong to rely on a specific buffer size. E.g. it's wrong to rely on exactly 5 elements being buffered, no more, no less. In such a case it's OK to compromise and pick between 4 and 8.

On the other hand a buffer of size one is interesting in its use-cases and should be possible. We should see what to do about that.

**Comment by ctoomey** [comment]
Draft for review/discussion in #1205 .

**Comment by ctoomey** [comment]
Done w/ #1205
