### ISSUE TITLE
runToFuture starts Task immediately despite using TestScheduler

### ISSUE THREAD

**Issue by timbertson** [monix/monix#1222]
I was surprised by this and can't find any docs to indicate it's intended. `TestScheduler` appears to run a task immediately if used via `runToFuture`, even though it doesn't if `schedule` is explicitly called.

Digging in a little bit this seems to be an optimisation in TaskRunLoop, so it might not be worth fixing but I figured I'd report it in case it wasn't known.

If I explicitly set `ExecutionModel.AlwaysAsyncExecution` on the TestScheduler then this works as expected, so maybe it's just a documentation issue? Should that become the default, or are there other issues with that?

```scala
package test

import monix.eval.Task
import monix.execution.ExecutionModel
import monix.execution.atomic.Atomic
import monix.execution.schedulers.TestScheduler

object SchedulerTest {
  implicit val s = TestScheduler()
  val sequence = Atomic(List.empty[String])
  def log(str: String) = sequence.transform(_.appended(str))
  def reset() = sequence.set(Nil)

  def main(args: Array[String]) = {

    // scenario 1: execute

    s.execute(() => log("runnable"))
    log("tick")
    s.tick()
    println(sequence.get)

    // scenario 2: runToFuture

    reset()
    val _ = Task { log("runToFuture") }.runToFuture
    log("tick")
    s.tick()
    println(sequence.get)
  }
}
```

When I run this (monix 3.2.2), the output is:

Expected:

```
List(tick, runnable)
List(tick, runToFuture)
```

Actual:

```
List(tick, runnable)
List(runToFuture, tick)
```

**Comment by alexandru** [comment]
@timbertson seems to me like it's working as intended.

```scala
Task(println("Hello!")).runToFuture
```

This will execute immediately and the reason for it is that no async boundaries, by default, are introduced. The run-loop will eventually fork if it's a loop, after a number of cycles, configured by default via `BatchedExecution`.

If you want that `Task` to not execute with a `TestScheduler`, then do `Task.evalAsync` or `Task(???).executeAsync`.

**Comment by timbertson** [comment]
If this is expected, then I do understand why, now. So my next question is whether the docs could be improved (or if I just missed the relevant bit). I'm re-reading https://monix.io/docs/current/execution/scheduler.html#execution-model, which seems like the place which should convey this, but it's still not entirely clear to me:

> acts as a guideline for pieces of computations that are doing possibly asynchronous execution in loops

"in loops" makes this seem irrelevant, since I'm not doing anything with loops.

> AlwaysAsyncExecution specifies that units of work within a loop should always execute asynchronously on each step

Again the loop reference feels off in this context.

I had a go at clarifying this text (at least, as I understand it):
https://github.com/monix/monix.io/pull/108

**Comment by timbertson** [comment]
After writing the note about TestScheduler specifically, I'm wondering if TestScheduler should always default to AlwaysAsyncExecution. My rule of thumb is that "a test scheduler shouldn't do anything until I tick() it". Now, I know that technically it isn't the scheduler executing stuff in this case, but logically it is in my mind (I read the `runToFuture` method as "run to future on this scheduler").

Making the TestScheduler default to AlwaysAsync would make that rule of thumb hold true, and feels less surprising (to me). WDYT?

**Comment by Avasil** [comment]
> So my next question is whether the docs could be improved (or if I just missed the relevant bit)

Yes, I think the docs could be improved. I think the confusion is more about `runXXX` methods than execution model and it would be worth mentioning in their scaladocs (if it isn't already) that they execute on the current thread until the first async boundary. We could also give a bigger emphasis that ticks in `TestScheduler` are about async boundaries and there can be fully synchronous tasks

>>acts as a guideline for pieces of computations that are doing possibly asynchronous execution in loops
>
> "in loops" makes this seem irrelevant, since I'm not doing anything with loops.
>
>> AlwaysAsyncExecution specifies that units of work within a loop should always execute asynchronously on each step
>
> Again the loop reference feels off in this context.

I'm not sure what the author had in mind - perhaps `flatMap` (or other synchronous operation) loops which matters for `BatchedExecution`?

> Making the TestScheduler default to AlwaysAsync would make that rule of thumb hold true, and feels less surprising (to me). WDYT?

I feel like it's good to have the same default as normal `Scheduler` and it is often used to test whether `Task` is running synchronously or asynchronously in the Monix tests

**Comment by timbertson** [comment]
> I feel like it's good to have the same default as normal Scheduler and it is often used to test whether Task is running synchronously or asynchronously in the Monix tests

I think it'd be reasonable for those to specify an explicit ExecutionContext, since the execution mechanism is actually under test in that kind of scenario. But you could probably argue either way, and it's potentially a disruptive change. I'll close this now, since the docs updates are enough to hopefully clarify for future travelers.
