### ISSUE TITLE
Drop support for Scala 2.11

### ISSUE THREAD

**Issue by alexandru** [monix/monix#1229]
Scala 2.11 is costing us developer resources that we don't have, and as much as I'd like to maintain it, the ecosystem has moved on.

- Cats no longer builds for 2.11
- Cats-Effect no longer builds for 2.11
- sbt has moved to Scala 2.12 some time ago
- Spark has moved to Scala 2.12, finally

What sparked this desire is that publishing to Sonatype for Scala 2.11 is currently broken. This is because Scaladoc packaging fails on Scala 2.11.12, with the compiler crashing. And disabling Scaladoc packaging for Scala 2.11 is not possible, as it would fail when uploading to Sonatype b/c the staging servers on Sonatype require doc packages.

Current issue: #1231 

**UPDATE:** we could still wait for as long as we can. Meaning the 3.x series. But after Cats-Effect 3.0, which isn't source compatible, we'll have no choice.

**Comment by Avasil** [comment]
I'm fine with it, 2.11 users can always stay on 3.2.2 that seems to be solid.

**Comment by SemanticBeeng** [comment]
Hmm... I'd like to still use `monix` with `spark` which is always quite far beyond.
Was pretty sure I'd get stuck trying to to make `spark` with 2.12...
But now checking release notes for 3.0 and seems this GA release has 2.12 support: https://spark.apache.org/releases/spark-release-3-0-0.html

This remains a concern to me and suggest this is important to others using Scala for big data applications.
Please advise.

**Comment by alexandru** [comment]
I find the situation regrettable. The big issue is that our dependencies stopped supporting 2.11.

We would have to stay on older versions for Cats and Cats-Effect. And once Cats-Effect 3.0 hits the shelves, which is about the end of the year (by my own estimates), that's basically impossible.

Also I've bumped into the error above by upgrading to Scala 2.11.12 and Scala.js 0.6.33. Sjs 0.6.33 is probably the last in the 0.6.x line, and 1.x does not support 2.11. I don't know which of the upgrades are responsible, but we'd have to stay on older versions that still work, or invest resources in working around the issue (like starting to delete the problematic code or smth).

You can still stay `3.2.x` for Scala 2.11, that version doesn't go away. You'd do the same with Cats too.

**Comment by alexandru** [comment]
I think I know how to proceed, given I've figured out what caused #1231. 

Due to the upcoming Cats-Effect 3.0, we need to start working on Monix 4.0 anyway. Therefore:

1. I renamed `master` to `series/3.x` (we'll no longer have a `master`)
2. I created a new [series/4.x](https://github.com/monix/monix/tree/series/4.x) branch

We'll start breaking binary compatibility there.

**Comment by alexandru** [comment]
#1230 was merged in [series/4.x](https://github.com/monix/monix/tree/series/4.x).
