### ISSUE TITLE
.mapAsync parallelism parameter meaning

### ISSUE THREAD

**Issue by AlejandroME** [monix/monix#1272]
Hello there!

I hope that this is the right channel to ask this question...
We want to use `.mapAsync` in an `Observable` (monix 2.3.3) but we don't quite understand what does it do the `parallelism` parameter required by the function.

What I understand is that the supplied function maps to a `Task`, alongside the parallelism factor which will determine how many elements of the observable will be processed in parallel. This is where a couple of questions arise:

When a `Task` is produced by that mapping function, how does it map to the underlying thread pool? I mean, if for example I choose `256` as the parallelism factor, would this mean that for each task a thread will be used? Or it isn't necessarily a 1:1 correlation (1 Task executed in 1 thread)?

We want to devise the potential issues while sizing that parallelism.

If this is not the right channel to ask this or if it's documentation that can shed some light on this that you can point me out to it'd be greatly appreciated.

Thanks!

**Comment by Avasil** [comment]
I've made a presentation on similar topic: [slides](https://slides.com/avasil/fp-concurrency-flatmap2019) / [video](https://monix.io/presentations/2019-dispelling-magic-behind-concurrency-in-fp.html)

`parallelism` parameter specifies how many Tasks will be scheduled concurrently. 
How many threads will be used, depends on your `Scheduler`.

If you use a Scheduler with 4 threads and set the parallelism factor to 256 then tasks will use 4 threads.
First four tasks will take those threads and others will wait until they are either finished, or they did asynchronous boundary.
I don't remember the behavior in `2.3.3` but async boundaries would most likely happen in any concurrent operator like `gather` or `sleep`, or after each 1k flatMaps depending on `ExecutionModel`.

**Comment by AlejandroME** [comment]
@Avasil This is what I was looking for. Thank you for such quick answer!

Closing the issue

**Comment by Avasil** [comment]
You're welcome!
