### ISSUE TITLE
TakeLeftByTimespanObservable should not call onComplete in onNext

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1277]
[TakeLeftByTimespanObservable calls onComplete](https://github.com/monix/monix/blob/series/3.x/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/TakeLeftByTimespanObservable.scala#L55) in `onNext` but it is a no-op because the `isActive` flag will be always `false` at this moment.

**Comment by jyoo980** [comment]
I opened a PR for this work 🙂
