### ISSUE TITLE
Add Task & Coeval flatTap

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1279]
Similar to [FlatMap#flatTap](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/FlatMap.scala#L153)

```scala
final def flatTap[B](f: A => Task[B]): Task[A] 
```

**Comment by Avasil** [comment]
`tapError` could be nice as well, we already have it in `monix-bio`:

```scala
final def tapError[B](f: Throwable => Task[B]): Task[A]
```

And I feel like `tapEval` could be better name than `flatTap` (because of tap prefix and "Eval" is often used in Observable when effects are involved) but we would lose consistency with cats - thoughts from anyone?

**Comment by GKhotyan** [comment]
I'll make it
