### ISSUE TITLE
Add none/some builders for Task and Coeval

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1281]
On companion objects:

```scala
val none: Task[Option[Nothing]]
def some[A](a: A): Task[Option[A]]
```

**Comment by jozic** [comment]
why not `def none[A]: Task[Option[A]]` ?
this seems more useful

**Comment by Avasil** [comment]
I'm wondering about it, similarily to https://github.com/monix/monix/issues/1280

I think you're right, `Task[Option[Nothing]]` can be inconvenient when it's later used in a fold
