### ISSUE TITLE
TestScheduler seems to not be able to deal with executeAsync.  By design?

### ISSUE THREAD

**Issue by maxhillaert** [monix/monix#1285]
Hi

I have some code that does a fork using mergeMap(x=>x.executeAsync) on some observables and when I write tests with testscheduler it doesn't seem to be able to cope and values are never emitted.

Here is a contrived example snippet.   

```
implicit val testScheduler = TestScheduler()
val test = PublishSubject[Int]()
test.executeAsync.doOnNext(x=>Task.delay(println(s"MAX2: Got a value $x"))).subscribe()

test.onNext(42)
test.onNext(43)
test.onNext(44)
testScheduler.tick()
```

This won't emit any values,  but if I remove executeAsync , it works.   I had a look at executeAsync and I can't work out why it would be a problem.    I'd love to understand why its not working.

Is the use of executeAsync basically not compatible with writing tests using test scheduler?   Should I try to factor executeAsync out?

**Comment by Avasil** [comment]
I think that's because `subscribe()` will be called after `onNext` (that can be synchronous and don't need to wait for tick).

You could try doing `tick()` after subscribe and before `onNext`

**Comment by maxhillaert** [comment]
God , you're right.  Still catches me out this stuff and I go all the way back to the original rx .net beta. :)

Thanks
