### ISSUE TITLE
Add Observable.paginate & Observable.paginateEval

### ISSUE THREAD

**Issue by Avasil** [monix/monix#1360]
```scala
def paginate[S, A](seed: => S)(f: S => (A, Option[S])): Observable[A]

def paginateEval[S, A](seed: => S)(f: S => Task[(A, Option[S])]): Observable[A]
```

Implementation is similar to [unfold](https://github.com/monix/monix/blob/series/3.x/monix-reactive/shared/src/main/scala/monix/reactive/internal/builders/UnfoldEvalObservable.scala) but we will emit one more `A` before completing on `None`

See [fs2 unfoldLoopEval](https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala/fs2/Stream.scala#L3610) and [ZIO's paginateM](https://github.com/zio/zio/blob/master/streams/shared/src/main/scala/zio/stream/ZStream.scala#L3800) for usage examples

**Comment by Wosin** [comment]
Happy to tackle that.

**Comment by Avasil** [comment]
@Wosin That's awesome - let me know if you have any questions or need some direction

**Comment by Wosin** [comment]
Hey, if I understand correctly that's just a `unfold` which in case of `None` returns the `A` again, right ?

**Comment by Avasil** [comment]
That's correct.

This is the result I'd expect:

```scala
Observable.unfold(0)(i => if (i < 10) Some((i, i + 1)) else None).toListL
// result: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Observable.paginate(0)(i => if (i < 10) Some((i, i + 1)) else None).toListL
// result: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

**Comment by Wosin** [comment]
Can be closed I guess :)
