### ISSUE TITLE
GraalVM Native Image instructions?

### ISSUE THREAD

**Issue by rohan-sircar** [monix/monix#1409]
I have been trying to compile monix applications to GraalVM native images for a while but I have been unsuccessful. Looking around there are plenty of instructions and projects for compiling cats-effect/fs2 to native images but almost none for monix.

I have set up a demo application monix application(to show the problem) here - https://github.com/rohan-sircar/monix-native-test/runs/2466468068?check_suite_focus=true . Usually the errors point to JCTools. Any pointers?

**Comment by Avasil** [comment]
I'm not that familiar with GraalVM - does it work with JCTools queues?

If not, we could see if we can detect that we're dealing with GraalVM and provide a different underlying queue impl: https://github.com/monix/monix/blob/series/3.x/monix-execution/jvm/src/main/scala/monix/execution/internal/collection/queues/LowLevelConcurrentQueueBuilders.scala

**Comment by rohan-sircar** [comment]
I think if stuff like logback can work with native image(and it apparently does) then there's no reason JCTools couldn't. There's just a lot of configuration required for stuff like reflection and class initialization. Some of it can be automated with this tracing agent that scans a running application and generates a config file - https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271

It would be good to have at least one monix demo project that compiles to native image to serve as a reference. Let me investigate this further with more examples. Some help from the community would be appreciated.

**Comment by rohan-sircar** [comment]
And this is the error I get in my http4s monix project - 
`Warning: RecomputeFieldValue.ArrayIndexScale automatic substitution failed. The automatic substitution registration was attempted because a call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) was detected in the static initializer of monix.execution.internal.jctools.util.UnsafeRefArrayAccess. Detailed failure reason(s): Could not determine the field where the value produced by the call to jdk.internal.misc.Unsafe.arrayIndexScale(Class) for the array index scale computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
`

**Comment by Avasil** [comment]
cc @lbialy maybe you'd like to lend a hand :D

**Comment by jvican** [comment]
Hey @rohan-sircar, you need to add `--initialize-at-run-time=monix.execution.internal.jctools` to your `native-image.properties`. I have a big native binary that uses Monix extensively and works great for me. I recommend generating native images from the last GraalVM release *and* Java 11 (not Java 8, which has some issues).

**Comment by alexandru** [comment]
This piece of advice could be an article.

**Comment by rohan-sircar** [comment]
@jvican Hi, really sorry for the late response! I passed that flag to native image arguments  [here](https://github.com/rohan-sircar/monix-native-test/blob/main/build.sbt#L15) but I get the [same errror ](https://github.com/rohan-sircar/monix-native-test/runs/2607345894?check_suite_focus=true).

**Comment by jvican** [comment]
I submitted a PR to your repo here https://github.com/rohan-sircar/monix-native-test/pull/1

The reflect configuration was missing. After adding it, it builds and runs successfully
