### ISSUE TITLE
`doOnNext` should not infer with backpressure 

### ISSUE THREAD

**Issue by paualarco** [monix/monix#1411]
Hi!

The Observable's `doOnNext` operator implementation is synchronous as it is infers to backpressure, and I think it should not be, as in [RxJava](http://reactivex.io/RxJava/javadoc/rx/Observable.html#doOnNext-rx.functions.Action1-) or Reactor.

```
 final def doOnNext(cb: A => Task[Unit]): Observable[A] =
    self.mapEval(a => cb(a).map(_ => a))
```

I think it should run that asynchronously in the background:
```
 final def doOnNext(cb: A => Task[Unit]): Observable[A] =
    self.mapEval(a => cb(a).startAndForget.as(a))
```

Perhaps we could replace the current operator with a new name like `tapEval`? 

Let me know about your thoughts

**Comment by oleg-py** [comment]
Note that Monix differs from RxJava in how its backpressure works. You might notice that monix Observer#onNext returns a `Future[Ack]` while same thing in RxJava returns `Unit`. That is quite a key difference that allows monix Observable to provide lossless backpressure of producers if the whole pipeline properly waits on these Futures (which nearly all our operators do).

Also, given `doOnNext` takes a Task-returning lambda (again, unlike RxJava, which is more oriented towards impure functions), my expectation has always been that it would backpressure. What you propose sounds surprising to me (you'll have uncancelable async actions and won't even get guarantees that `f` runs before `g` in  `obs.doOnNext(f).doOnNext(g)`) and it's easily obtainable by doing `.startAndForget` (while reverse isn't true).

**Comment by paualarco** [comment]
Thanks for responding and clarifying @oleg-py, have checked that on the java libraries and indeed seems to be aligned with Monix, although I was confused by the difference between the method signatures.
On the other hand, I think that creating an alternative operator that fires and forgets about the result might create confusions.
So closing the ticket :)
