### ISSUE TITLE
use gitbook for docs

### ISSUE THREAD

**Issue by fommil** [monix/monix#169]
It makes it a lot easier to convert into a PDF or ebook format for offline reading.

**Comment by fommil** [comment]
fyi monix.io is blocked by the firewall at my work

**Comment by alexandru** [comment]
@fommil can you find out why does your firewall blocks Monix.io?

Just a note - [monix.io](https://monix.io) gets served exclusively over HTTPS (with a Let's Encrypt Certificate). It does have a redirect from HTTP to HTTPS, but it also has `Strict-Transport-Security` enabled ([HTST](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)) and it's been added to the [preload list](https://hstspreload.appspot.com/) in Chrome and Firefox. Its configuration should be OK, I get an [A+ rating on ssltest](https://www.ssllabs.com/ssltest/analyze.html?d=monix.io).

Maybe this is something related to HTTPS?

On GitBook, I don't know how that works, but I'll take a look. Thanks for the tip.

**Comment by fommil** [comment]
it's a corporate firewall, it blocks whatever it wants.
