### ISSUE TITLE
Add Observable.mapAsync for parallel mapping over Observable

### ISSUE THREAD

**Issue by lukestephenson** [monix/monix#205]
Edit by @alexandru:

Adding a new `Observable.mapAsync[B](parallelism: Int)(f: A => Task[B]): Observable[B]` operator, in spirit similar with `Consumer.loadBalancer`. This is in addition to `mapTask` and `mapFuture` that simply serializes asynchronous requests, but with no parallelism.

Implementation is being pushed in PR #234.

Original request by @lukestephenson:

With a monix Observable, is it possible to map over the elements in parallel (by supplying a function which takes each element and returns a Task)? I've seen Consumer.foreachParallelAsync but I can only see how this can be used as the final step of running an observable. I'm interested in this being one stage in consuming an observable, and then doing further translations, not the final stage (in akka streams, the equivalent operator would be mapAsync http://doc.akka.io/docs/akka/2.4.9-RC1/scala/stream/stages-overview.html#mapasync)

Related discussion on gitter
![image](https://cloud.githubusercontent.com/assets/395523/17617186/0c6f813a-60bc-11e6-808a-2289a1ccea63.png)

**Comment by capacman** [comment]
+1 for the feature.

**Comment by alexandru** [comment]
Sure guys, parallelism is a little tricky, but not that hard. It will happen soon.

**Comment by alexandru** [comment]
@lukestephenson the implementation is ready to be merged in master, in PR #234.

Would love it if you took a quick look.
