### ISSUE TITLE
Observable.fromItarator(iterator) .subscribe(obs) could be blocking

### ISSUE THREAD

**Issue by creyer** [monix/monix#217]
The issue is revealed when having lazy iterators, for which method `hasNext` is blocking.
The monix implementation has an issue here: [https://github.com/monixio/monix/blob/v1.2/monifu/shared/src/main/scala/monifu/reactive/internals/builders/from.scala#L130]
as `def isEmpty: Boolean = !hasNext`

Removing early completion and going directly with `startFeedLoop(iterator)` should fix the issue

**Comment by alexandru** [comment]
In Monix, version 2 at least, forking logical threads is explicit, so if `fromIterator` is blocking, you can always do something like:

```scala
Observable.fromIterator(ref).executeWithFork

// Or specify another scheduler
Observable.fromIterator(ref).executeOn(io)
```

This will ensure that the iterator starts being consumed from a different thread.
