### ISSUE TITLE
Java 8 compatibility: Collection operations for Java 8 Stream

### ISSUE THREAD

**Issue by Diagoras** [monix/monix#222]
Versions of `Task.gather`, `Task.gatherUnordered`, `Task.sequence`, etc. for Java 8's Stream would be nice, and for the rest of Java's collections if that seems feasible. Overloading is the obvious approach, or we could go for a less pleasant Java experience but a nicer codebase by requiring a `CanBuildFrom` to be passed in for `java.util.Stream`.

**Comment by alexandru** [comment]
This suggestion is nice, however the usage of the current `CanBuildFrom` is already enough.

I was actually thinking of migrating to Cats's `Traverse`, but then that is less generic. `CanBuildFrom` is dirty and if Scala doesn't provide integration with Java 8's Stream, then it's a bad idea to do it in Monix.
