### ISSUE TITLE
Projects proposals

### ISSUE THREAD

**Issue by alexandru** [monix/monix#223]
We need to expand the reach of Monix.

I'm thinking of these projects:
1. Integration with Kafka, i.e. `monix-kafka` - shouldn't be much, we are actually using Kafka with Monix in our own projects
2. Integration with Akka Streams (conversions back and forth) - shouldn't be that much either, because Monix already has integration with [Reactive Streams](http://www.reactive-streams.org/) and we are also using Akka and Monix together in our projects - i.e. `monix-akka` and `monix-akka-streams`
3. Integration with Play Framework for web sockets stuff, i.e. `monix-play25` - unfortunately this one is going to be version specific, because they break compatibility, but it is doable - if we have number 2 it shouldn't be too hard, but we should probably expose actors as well and a back-pressuring client/server model, similar to the one exposed in [monix-sample](https://github.com/monixio/monix-sample) - actually, starting with Monix sample shouldn't be too hard
4. We need our own HTTP framework, both client and server - https4s has a [branch dedicated to Cats and FS2](https://github.com/http4s/http4s/tree/topic/cats); if we don't have our own HTTP framework, we're going to be left behind - this is a big project, but one idea would be to fork that branch in http4s, since the important parts (i.e. replacing Scalaz with Cats) will be taken care of and replacing FS2 with Monix should be easier; or another idea is to convince them to make FS2 optional, by means of some type-classes, so people can use Monix instead of FS2; or we could start from scratch - [I personally did that before](https://github.com/alexandru/shifter), it's not that hard when you build on top of already made infrastructure, like Java Servlets and [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client)
5. The Scalaz integration is not enough - we also need to convert Task back and forth - but we can't depend on scalaz-concurrent, unless it is optional
6. The [Shade](https://github.com/alexandru/shade), my Memcached client that's based on SpyMemcached, needs to be upgraded to Monix 2.x and I think this is an instance where `Task` provides value instead of `Future`
7. The Cassandra client in [Quill](http://getquill.io/) depends on Monifu 1.x, would be cool to help them upgrade to 2.x

**Volunteers for these projects needed, ideas needed !!!**

**Comment by mihaisoloi** [comment]
One other project for an HTTP framework could be replacing the Akka Streams implementation in Akka HTTP with Monix. This would hit two birds with one stone.

**Comment by ngbinh** [comment]
For 4. There is https://github.com/hmil/RosHTTP/tree/v2.0.0 .It aims to be a cross Jvm/Js HTTP client

**Comment by vipo** [comment]
For 1: easy to achieve, less boilerplate.

**Comment by alexandru** [comment]
@vipo do you want to volunteer?

I've started `monix-kafka` here: https://github.com/monixio/monix-kafka/tree/master/src/main/scala/monix/kafka - for now I dumped an untested KafkaProducer implementation extracted from somewhere else.

If you're willing to contribute, I can give you access and make you a maintainer if you wish.

**Comment by vipo** [comment]
We have a upgrade-form-1.2-to-2.0 project (kafka consumer) in a pipeline. We are not starting it immediately, but when we will, we will try to drop all these two pieces (producer/consumer) and see how it works.

**Comment by rossabaker** [comment]
I've noticed overlapping interest in http4s and monix.  I would be interested in supporting its Tasks or Observables, but my prior attempts to abstract over the effect and/or stream type have resulted in a mess.  Whether it's an abstraction, another branch, or a fork, I'd be happy to have a conversation to see what kind of effort we can share and benefit both projects.

**Comment by alexandru** [comment]
@rossabaker thanks for getting in touch, I would personally love the ability to use http4s in combination with monix. 

Abstracting over an effect type is hard though, I agree, tried it as an experiment once. I'll have to look a little at the http4s implementation to get a sense of how much effort is involved.

**Comment by aoprisan** [comment]
I startes working on updating Quill.

**Comment by alexandru** [comment]
@aoprisan nice 👍

**Comment by aoprisan** [comment]
I am taking a stab at no. 4, will look into the cats branch of http4s.

**Comment by volth** [comment]
I have a set of files in a pet project which would eventualy become ```monix-postgresql```.
Not publishet yet as the API is not stable

**Comment by alexandru** [comment]
@volth are you using https://github.com/mauricio/postgresql-async ?

**Comment by mihaisoloi** [comment]
@alexandru I've come across this incubator from APACHE they're trying to promote a universal protocol for all the two way data interchange in their projects http://streams.incubator.apache.org/site/0.4-incubating-SNAPSHOT/streams-master/ it would be cool if monix would support it as well.

**Comment by volth** [comment]
It was started as atempt to unify https://github.com/mauricio/postgresql-async and https://github.com/alaisi/postgres-async-driver (rxjava-based). With monix many things are cleaner and more straightforward.

**Comment by alexandru** [comment]
@volth sounds good, go for it :-)

**Comment by gabor-aranyossy** [comment]
Have you thought of having a tcp streaming solution similar like [scalaz-netty](https://github.com/RichRelevance/scalaz-netty)?

**Comment by gabor-aranyossy** [comment]
Never mind. I just discovered [monix-nio](https://github.com/monix/monix-nio) has pretty much that. Nice!

**Comment by alexandru** [comment]
This conversation was nice, however for further conversations, people can just open new issues or to re-open this issue if further discussion is warranted. This is an attempt to clean up the issue tracker.
