### ISSUE TITLE
Add executeWithFork, executeWithModel and asyncBoundary operators on Task

### ISSUE THREAD

**Issue by alexandru** [monix/monix#227]
What we have right now:

- `Task.fork(fa)` which ensures an asynchronous boundary happens with the scheduler injected in `runAsync`
- `Task.fork(fa, scheduler)` which ensures that execute, along with an initial asynchronous boundary, happens with the specified scheduler, overriding the default
- `Task#executeOn(scheduler)` is already there, being the  alias of `Task.fork(fa, scheduler)`

What we need:

- `Task#executeWithFork`, being a convenient alias for `Task.fork(fa)`
- `Task#executeWithModel` for overriding the `ExecutionModel` of a `Task`
- `Task#executeWithOptions` for overriding the default `Task.Options` (see issue #226)
- `Task#asyncBoundary()` and `Task#asyncBoundary(Scheduler)` for creating an asynchronous boundary

The `asyncBoundary` method should basically have the meaning of:

```scala
val boundary = Task.fork(Task.unit)
task.flatMap(result => boundary.map(_ => result))
```

It is similar in spirit with `Observable.asyncBoundary`. It basically has the effect to jump with the execution on the given thread-pool. So if for example you're executing something on your I/O scheduler and want to continue with `map` and `flatMap` transformations on your CPU-bound scheduler, because of Task's characteristics, those transformations won't happen automatically on the CPU-bound scheduler even if it is specified in `runAsync`, not as long as an asynchronous boundary doesn't happen. And this utility helps that asynchronous boundary to happen.

**Comment by oleg-py** [comment]
@fancywriter you should simply use `Task.eval(db.query(params)).executeOn(io)`
