### ISSUE TITLE
Similarly with Task.doOnFinish we need a Task.doOnCancel

### ISSUE THREAD

**Issue by alexandru** [monix/monix#229]
Cancelation is different from finishing a Task and we also need a `doOnCancel` utility that adds tasks to execute in case the `Task` is prematurely canceled.

```scala
sealed trait Task[+A] {
  def doOnCancel(t: Task[Unit]): Task[A]
}
```

This can be more or less implemented like: 

```scala
def doOnCancel(cb: Task[Unit]): Task[A] =
  Task.unsafeCreate { (s, conn, cb) =>
    conn.push(Cancelable(() => t.runAsync(Cancelable.empty)(s)))
    Task.unsafeStartNow(source, s, conn, cb)
  }
```

Note that we cannot also do a `doOnFinish` here, because cancelation can be concurrent with the trampoline, synchronization is sometimes needed and besides, you don't necessarily want to run the same logic.

**Comment by hepin1989** [comment]
This is what I just want to issue up:)
If I have a task from future,and the future is from a promise,and the promise is completed later,then I may want after I cancel the Task,to cancel the promise completion:)

**Comment by alexandru** [comment]
It's already on master.
