### ISSUE TITLE
Real industy usages

### ISSUE THREAD

**Issue by raulraja** [monix/monix#233]
I know Monix is used in several places successfully in production since I have talked to many people that use this great library at diverse scala conferences. I would still be useful to have a list of real references in the README or documentation site so that it's adoption spreads faster and become easier to justify to management types asking for references. I'll start by saying that 47 Degrees uses it and we'd love to be part of that list.

**Comment by andyscott** [comment]
I work with @raulraja and I'd like to second that this information would be very useful.

**Comment by alexandru** [comment]
Hi @raulraja @andyscott, I like the suggestion and thanks for offering. 

There is no such list at the moment, but I guess we can start compiling one. Monix is heavily used by our needs at E.On. Other users will need to step forward - unfortunately I 've only gone to conferences to talk to people about once a year, hopefully next year maybe I'll be more active.

**Comment by ngbinh** [comment]
We https://anduintransact.com/ are using monix quite heavily on our client side (~50K+ LOC scala.js react.js web app).

**Comment by erikvanoosten** [comment]
We are pushing up to 60K events per second into a Monix scheduler. Load decreased by ±1 after me moved away from an Akka scheduler; freeing up an entire CPU!

**Comment by velvia** [comment]
+1.  Would love to hear use cases of this vs Akka Streams.

**Comment by hrlqn** [comment]
@alexandru I have introduced Monix to both Samsung Research (I am no longer with them as of Nov 2016) and Agoda (current employer).

At Agoda I rely on Monix for an in-house query-engine atop of Cassandra and separately am consuming 1.5M measurements per second off of Kafka and aggregating these (sum/count/TDigest/HyperLogLogPlus) forwarding them into both Kafka and Cassandra.

**Comment by knasim** [comment]
hello - i'm looking for a dead simple reference implementation of monix.   can someone kindly point me to one.

**Comment by velvia** [comment]
Hmmm.   I think the variety of applications is probably large enough that the “reference” depends a lot  :)

“Never doubt that a small group of thoughtful, committed citizens can change the world.” —M. Mead

Evan Chan
velvia@gmail.com

**Comment by knasim** [comment]
@velvia  - thanks for your specificity !

**Comment by alexandru** [comment]
A reply that's a little late 🙂 but I'm not sure I want to maintain such a list. Thanks for the suggestion.

Will close this for now.
