### ISSUE TITLE
Add Observable.measureDownstreamLatency

### ISSUE THREAD

**Issue by alexandru** [monix/monix#235]
When pushing events downstream, it would be cool to have an utility such as `measureDownstreamLatency` that, as the name says, measures the time it takes the downstream to process messages, such that we can compile statistics, like:

``` scala
source.measureDownstreamLatency { time =>
  metrics.downstreamTimer.update(time, TimeUnit.MILLIS)
}
```

**Comment by hepin1989** [comment]
or when the time cost is higher than specified value,drop it.
https://github.com/iheartradio/kanaloa
