### ISSUE TITLE
enhance the io scheduler constraction

### ISSUE THREAD

**Issue by hepin1989** [monix/monix#242]
The default CachedExecutorService don't have any upper bound,so I think the following way should be more nice;which means we could limit the mixCoreSize and the maxCoreSize,name,keepAliveTime.
eg:

``` java
        return ExecutionContexts.fromExecutor(new ThreadPoolExecutor(
                minCoreSize,
                maxCoreSize,
                keepAliveTime,
                TimeUnit.MILLISECONDS,
                new SynchronousQueue<Runnable>(),
                new NamedThreadFactory(prefix, true, new Thread.UncaughtExceptionHandler() {

                    @Override
                    public void uncaughtException(Thread t, Throwable e) {
                        LOGGER.error("In [{}] uncaughtException occur on thread :[{}]", prefix, t, e);
                    }
                }), new RejectedExecutionHandler() {
            @Override
            public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
                if (executor.isShutdown()) {
                    LOGGER.error("BlockingExecutionContext :[{}] is shutdown.", prefix);
                    throw new RejectedExecutionException(LoggingHelpers.format(
                            "BlockingExecutionContext's backing executor:[{}] is shutdown.",
                            prefix
                    ));
                } else {
                    r.run();
                }
            }
        }));
```

**Comment by alexandru** [comment]
Hey @hepin1989,

The default (and I assume you refer to `monix.execution.Scheduler.Implicits.global`) is a backed by a `ForkJoinPool` and not by a `CachedExecutorService`. It is `Scheduler.io()` that returns a scheduler backed by a `CachedExecutorService` and it's good that it is unbounded, because that's what you need for blocking I/O.

If you want a `Scheduler` implementation that is bounded, we could introduce another helper.
Something like:

```scala
Scheduler.cached(minThreads=1, maxThreads=10,...)
```

**Comment by hepin1989** [comment]
@alexandru No,I means `Scheduler.io()`.
another problem of using `CachedExecutorService ` is that once there are a lot of long time running,it will grow bigger and bigger,why I want this is I want to do some bulking,especially calling some RPC service with blocking calls.

**Comment by hepin1989** [comment]
And yes ,`Scheduler.cached(minThreads=1, maxThreads=10,...)`,is what I think should be introduced.

**Comment by alexandru** [comment]
Oh, I haven't payed attention to the title.

OK, will make it happen.

**Comment by hepin1989** [comment]
@alexandru This is from our production practice,not illusion:)
