### ISSUE TITLE
Add the TrampolineScheduler for the JVM, in addition to Javascript

### ISSUE THREAD

**Issue by alexandru** [monix/monix#243]
We always had a `TrampolineScheduler` for Javascript, however we need one for the JVM as well.

The implementations don't have to be identical, even if we are introducing the `ThreadLocal`, since performance matters, but we need to share as much of the implementation as possible with the `BatchingScheduler` trait.

So now both on the JVM and on JS we are now able to do:

```scala
implicit val scheduler = Scheduler.trampoline()
```

**Comment by Diagoras** [comment]
+1
