### ISSUE TITLE
Optimize the performance of the buffers

### ISSUE THREAD

**Issue by alexandru** [monix/monix#261]
The `monix-reactive` project uses buffers on asynchronous boundaries, with a configurable `OverflowStrategy`.

PULL REQUEST: https://github.com/monix/monix/pull/265

Changes proposed:

- apply optimizations by means of the non-blocking queues in [JCTools](https://github.com/JCTools/JCTools), a Java project that provides awesome non-blocking data-structures
- review of the cache-line padding applied by means of the [jol tool](http://openjdk.java.net/projects/code-tools/jol/), making sure that we are applying the right amount of padding
- modify the logic of these buffers to not back-pressure `onComplete` and `onError` on the last `Future[Ack]` received from `onNext`
- benchmark and do comparisons with Monifu 1.2 to see how much we've improved, since that code isn't modified since then
- because we make heavy usage of `monix.execution.atomic` references, those have been improved for Java 8: `getAndSet` was already generating a `LOCK XCHG` on Java 8, but the implementation is now also using the `Unsafe` methods for incrementing numbers (`getAndIncrement`), thus having those translated to `XADD` which is way more efficient than CAS loops - and this directly benefited our buffers

In terms of optimizations, we've got *really good* results. But lets go through all the strategies:

## OverflowStrategy.Unbounded & OverflowStrategy.Fail

The `Unbounded` and the `Fail` strategies are usually the default being applied for `ConcurrentSubject` usage, amongst others, the resulting subscribers being guaranteed to be synchronous in usage and not allowing dropping of events. These are being handled by `monix.reactive.observers.buffers.SimpleBufferedSubscriber`, which was the first `BufferedSubscriber` implementation to be optimized.

The benchmarking results for `OverflowStrategy.Unbounded`:

```
jmh:run -r 2 -i 20 -w 2 -wi 20 -f 1 -t 1 monix.UnboundedBufferBenchmark
(higher is better)

Benchmark        (threads)   Mode  Cnt     Score    Error  Units
================================================================
monifuUnbounded          1  thrpt   20  1479.288 ± 13.212  ops/s
monixUnbounded           1  thrpt   20  2355.567 ± 88.869  ops/s
----------------------------------------------------------------
monifuUnbounded          2  thrpt   20   916.984 ± 13.784  ops/s  
monixUnbounded           2  thrpt   20  1601.104 ± 55.258  ops/s
----------------------------------------------------------------
monifuUnbounded          3  thrpt   20   995.930 ± 12.013  ops/s
monixUnbounded           3  thrpt   20  1731.478 ± 10.616  ops/s
----------------------------------------------------------------
monifuUnbounded          4  thrpt   20   955.404 ±  7.617  ops/s
monixUnbounded           4  thrpt   20  1379.462 ± 28.750  ops/s
```

To put this in perspective:

![image](https://cloud.githubusercontent.com/assets/11753/20062062/f9a2260a-a50a-11e6-814e-46be793e3214.png)

```
jmh:run -r 2 -i 20 -w 2 -wi 20 -f 1 -t 1 monix.FailBufferBenchmark
(higher is better)

Benchmark          (events)  (threads)   Mode  Cnt      Score     Error  Units
==============================================================================
monifuOverflowing      1000          1  thrpt   20   8436.588 ± 145.171  ops/s
monixOverflowing       1000          1  thrpt   20  12298.593 ± 180.335  ops/s
------------------------------------------------------------------------------
monifuOverflowing      1000          2  thrpt   20   7340.231 ± 116.128  ops/s
monixOverflowing       1000          2  thrpt   20  11812.279 ± 356.597  ops/s
------------------------------------------------------------------------------
monifuOverflowing      1000          3  thrpt   20   7355.112 ±  42.982  ops/s
monixOverflowing       1000          3  thrpt   20  12346.112 ± 111.156  ops/s
------------------------------------------------------------------------------
monifuOverflowing      1000          4  thrpt   20   7431.399 ±  88.612  ops/s
monixOverflowing       1000          4  thrpt   20  11351.964 ± 150.635  ops/s
------------------------------------------------------------------------------
monifuOverflowing      8000          1  thrpt   20   1619.820 ±  56.210  ops/s
monixOverflowing       8000          1  thrpt   20   2057.911 ±  55.624  ops/s
------------------------------------------------------------------------------
monifuOverflowing      8000          2  thrpt   20   1115.281 ±  16.113  ops/s
monixOverflowing       8000          2  thrpt   20   1910.661 ±  54.603  ops/s
------------------------------------------------------------------------------
monifuOverflowing      8000          3  thrpt   20   1051.244 ±   5.977  ops/s
monixOverflowing       8000          3  thrpt   20   2036.548 ±   7.978  ops/s
------------------------------------------------------------------------------
monifuOverflowing      8000          4  thrpt   20   1027.703 ±   6.133  ops/s
monixOverflowing       8000          4  thrpt   20   1716.239 ±  23.864  ops/s
```

Here we are varying the buffer size, because if we are under `Platform.recommendedBatchSize` then we are able to pick a more efficient non-blocking queue implementation.

![image](https://cloud.githubusercontent.com/assets/11753/20062239/a9609d9c-a50b-11e6-827c-f716bade8dcf.png)

![image](https://cloud.githubusercontent.com/assets/11753/20062299/ebb5ca6e-a50b-11e6-8953-efcadf3a2d5c.png)

## OverflowStrategy.BackPressure

The `OverflowStrategy.BackPressure` is the default strategy being used in Observable's operators, the most important one being `Observable.merge`. 

Note that this overflow-strategy is required to try and back-pressure the source, but if the source doesn't listen then it must NOT lose events, which means that internally it can store an unbounded number of events. Therefore in the benchmark by varying the `bufferSize` we are also testing what happens with or without overflows. Here the improvements are even more dramatic:

```
jmh:run -r 2 -i 20 -w 2 -wi 20 -f 1 -t 1 monix.BackPressuredBufferBenchmark
(higher is better)

[info] Benchmark     (bufferSize)  (threads)   Mode  Cnt     Score    Error  Units
==================================================================================
monifuBackPressured          8192          1  thrpt   20  1158.016 ± 38.302  ops/s
monixBackPressured           8192          1  thrpt   20  2187.149 ± 43.712  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          8192          2  thrpt   20   910.596 ± 54.045  ops/s
monixBackPressured           8192          2  thrpt   20  1645.379 ± 27.994  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          8192          3  thrpt   20   863.964 ± 11.557  ops/s
monixBackPressured           8192          3  thrpt   20  1907.888 ± 21.773  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          8192          4  thrpt   20   992.857 ± 12.195  ops/s
monixBackPressured           8192          4  thrpt   20  1408.718 ± 23.489  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          4096          1  thrpt   20  1164.908 ± 19.756  ops/s
monixBackPressured           4096          1  thrpt   20  1802.754 ± 61.056  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          4096          2  thrpt   20   870.134 ± 54.233  ops/s
monixBackPressured           4096          2  thrpt   20  1611.090 ± 44.151  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          4096          3  thrpt   20   885.456 ±  9.509  ops/s
monixBackPressured           4096          3  thrpt   20  1896.735 ± 19.670  ops/s
----------------------------------------------------------------------------------  
monifuBackPressured          4096          4  thrpt   20   872.744 ±  5.446  ops/s
monixBackPressured           4096          4  thrpt   20  1659.648 ±  7.818  ops/s
```

![image](https://cloud.githubusercontent.com/assets/11753/20062696/48fbeac2-a50d-11e6-9007-ca56c84a1f3e.png)

## OverflowStrategy.DropNew

The `DropNew` strategy specifies that the buffer should drop incoming messages on overflow, possibly by notifying the subscriber and/or logging overflow events somewhere.

Note that this overflow-strategy is required to start dropping incoming events on overflow. Therefore in the benchmark by varying the `bufferSize` we are also testing what happens with or without overflows.

```
jmh:run -r 2 -i 20 -w 2 -wi 20 -f 1 -t 1 monix.DropNewBufferBenchmark

Benchmark      (bufferSize)  (threads)   Mode  Cnt     Score    Error  Units
============================================================================
monifuDropNew          8192          1  thrpt   20  1344.053 ± 13.315  ops/s
monixDropNew           8192          1  thrpt   20  1717.440 ± 55.813  ops/s      
----------------------------------------------------------------------------
monifuDropNew          8192          2  thrpt   20   896.751 ± 36.251  ops/s
monixDropNew           8192          2  thrpt   20  1635.806 ± 35.691  ops/s
----------------------------------------------------------------------------
monifuDropNew          8192          3  thrpt   20   901.071 ± 13.104  ops/s
monixDropNew           8192          3  thrpt   20  1920.868 ± 31.696  ops/s
----------------------------------------------------------------------------
monifuDropNew          8192          4  thrpt   20   878.508 ±  6.113  ops/s
monixDropNew           8192          4  thrpt   20  1292.439 ± 37.575  ops/s
----------------------------------------------------------------------------
monifuDropNew          4096          1  thrpt   20  1344.043 ± 18.214  ops/s
monixDropNew           4096          1  thrpt   20  2355.452 ± 69.670  ops/s
----------------------------------------------------------------------------
monifuDropNew          4096          2  thrpt   20   749.514 ± 15.926  ops/s
monixDropNew           4096          2  thrpt   20  1688.977 ± 32.557  ops/s
----------------------------------------------------------------------------
monifuDropNew          4096          3  thrpt   20   922.695 ±  8.250  ops/s
monixDropNew           4096          3  thrpt   20  1906.217 ± 12.741  ops/s
----------------------------------------------------------------------------
monifuDropNew          4096          4  thrpt   20  1586.744 ± 27.547  ops/s
monixDropNew           4096          4  thrpt   20  2426.228 ± 45.728  ops/s
```

![image](https://cloud.githubusercontent.com/assets/11753/20062857/e7d424a2-a50d-11e6-92d4-5383b0e24724.png)

## OverflowStrategy.DropOld

The `DropOld` starts dropping old events on overflow, thus trying to preserve the incoming events. It's not possible for us to use JCTools (see discussion on the ticket), but the implementation was optimized like this:

- we are no longer using `synchronize` blocks, but a `monix.execution.atomic.Atomic(scala.collections.immutable.Queue)`, with generous padding
- the consumer-side is very fast as it drains the whole queue at once with a `getAndSet` operation, which on top of Java 8 is translated into a `LOCK XCHG`, while producers will contend with CAS loops
- this makes the implementation non-blocking and it actually has decent performance considering what we want to achieve

NOTE that in the benchmark we get weird results for the old Monifu code. Because we've been using intrinsic locks there, by means of `synchronize`, the JVM can do weird tricks and thus we get anomalies like the test using 4 producers having better throughput than the code using a single producer, which is not possible ;-)

Either way, the new implementation is definitely faster in the ideal case (i.e. one or two producers contending) and is non-blocking, hence this is enough for now:

```
jmh:run -r 2 -i 20 -w 2 -wi 20 -f 1 -t 1 monix.DropOldBufferBenchmark

Benchmark      (bufferSize)  (parallelism)   Mode  Cnt     Score     Error  Units
=================================================================================
monifuDropOld          8192              1  thrpt   20   842.700 ± 115.446  ops/s
monixDropOld           8192              1  thrpt   20  1652.989 ±  24.821  ops/s
---------------------------------------------------------------------------------
monifuDropOld          8192              2  thrpt   20   632.467 ±  32.633  ops/s
monixDropOld           8192              2  thrpt   20  1216.629 ±  43.324  ops/s
---------------------------------------------------------------------------------
monifuDropOld          8192              3  thrpt   20  1097.051 ±  21.193  ops/s
monixDropOld           8192              3  thrpt   20   907.566 ±  14.765  ops/s
---------------------------------------------------------------------------------
monifuDropOld          8192              4  thrpt   20  1245.034 ±  17.718  ops/s
monixDropOld           8192              4  thrpt   20   823.816 ±  18.291  ops/s
---------------------------------------------------------------------------------
monifuDropOld          4096              1  thrpt   20   925.732 ±  95.749  ops/s
monixDropOld           4096              1  thrpt   20  2077.013 ±  47.315  ops/s
---------------------------------------------------------------------------------
monifuDropOld          4096              2  thrpt   20   966.570 ±  58.283  ops/s
monixDropOld           4096              2  thrpt   20  1057.430 ±  23.318  ops/s
---------------------------------------------------------------------------------
monifuDropOld          4096              3  thrpt   20   541.593 ±  12.090  ops/s
monixDropOld           4096              3  thrpt   20   906.161 ±  27.930  ops/s
---------------------------------------------------------------------------------
monifuDropOld          4096              4  thrpt   20  1464.677 ±  19.207  ops/s
monixDropOld           4096              4  thrpt   20   819.434 ±  15.236  ops/s
```

![image](https://cloud.githubusercontent.com/assets/11753/20063266/2ec23cea-a50f-11e6-9cf2-b7dde1745bba.png)

What this shows us is that the new `DropOld` buffer implementation behaves better for 1 or 2 threads, but in case of 3 or 4 threads the old implementation might be better (though I'm not buying it), but it definitely has problems when multiple producers are competing, as there's a clear performance degradation there. Unfortunately for now this is the best we can do for `DropOld`.

**Comment by scottcarey** [comment]
I wonder how JCTools compares to the LMAX Disruptor, performace-wise for these use cases.

**Comment by alexandru** [comment]
@scottcarey I don't have measurements, even though I'm pretty sure the LMAX Disruptor yields better performance, however from what I understand they have some tradeoffs towards that purpose that aren't necessarily compatible with our current needs here. First of all, their data-structure is a ring buffer, which (probably) means it has a fixed size, whereas we need queues that can grow.

Also AFAIK (and note I only have superficial knowledge) when consuming events they keep that run-loop busy, even in cases where there are no events incoming, which can yield the best performance, because you then keep the producers and the consumers from contending. This was I think configurable of course, but consider that we need to stop run-loops when the queue is empty and keep track of the total enqueued events by means of `incrementAndGet` (on every push) to infer when a new run-loop should start.

Of course, our strategy is not set in stone, I was actually flirting with a more relaxed alternative, but the point is Monix takes a lighter approach because LMAX Disruptor comes with tradeoffs. 

JCTools is basically simpler and more general purpose.

**Comment by scottcarey** [comment]
Yes, a disruptor won't work for all of the use cases.  It is fixed size, and all consumers have to be getting the same data and executing the same code (so it can't be a general purpose executor).

Its more of a curiosity for me, since information in general on JCTools is sparse.  The documentation is thin and the various queue flavor differences and behaviors are not well described.  Lots of google searches have lead to little info.

I am especially interested in MPMC pub-sub ish behavior with a DropOld policy (newer events are always more important than old ones in my case) where a consumer can discover that they have fallen too far behind and lost messages, and decide what to do.  Most solutions encumber the producer with this choice, but my producer absolutely must not get backpressure.

FWIW: the use case is having websocket consumers be able to 'spy' the internals of a system's data flow at a couple specific points.  Hence, multiple consumer.  (and single producer or multiple, depending on the situation).  Websocket clients might fall behind or be slow and that is their own problem, not one that should cause backpressure eleshwere, and it is best if the clients themselves could decide whether they care about losing some of the events.

The Disruptor sort-of fits this, but has tradeoffs.  It would have to be customized to support the consumers falling behind and not blocking the producer (but possible).   Scalaz-streams' Topic is both slow and unbounded.   Switching to monix is of interest, if it is fast enough and has enough flexibility in this area.

I have several other use cases as well, but the above one is the more problematic one.

Anyway, this is all off topic now; Back to lurking.

**Comment by alexandru** [comment]
@scottcarey I'm not currently sure if we can optimize the `DropOld` implementation, as it requires experimentation and it's a little out of my depth, although I'll try.

Technically the reason for why these concurrent queue implementations work well is because the producers aren't contending with the consumer, meaning that each side gets one end of the queue and works with it without stepping on each other. However a `DropOld` implementation effectively means that the producer has to end up consuming in order to drop events to make room, thus competing for this consumption with the consumer.

I guess we could try a `MPMC` array-queue implementation, JCTools has one, see [MpmcArrayQueue](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java) and we could see how that goes. I also asked a question on JCTools, its author is far more knowledgeable and maybe he'll help with a suggestion: https://github.com/JCTools/JCTools/issues/139

BTW, on Monix, we also have `DropNew` AND `DropNewWithSignal` overflow strategies. Now this could be of interest for you, because on overflow when the consumer recovers, it allows you to send it a notification that an overflow event happened, along with the count of dropped messages. The use-case, for me at least, has been precisely web-socket connections, because the client needs to be informed that overflows are happening and thus display a warning or something. Another possibility is `OverflowStrategy.Fail` - basically if the client is too slow, then you drop the connection. And if the client is smart, it can re-establish that connection when it recovers.

As a final thought, Monix had fairly good throughput already. See for example how it fared back in Sep 2015 against the available versions of Akka Streams and RxJava: https://alexn.org/blog/2015/09/06/monifu-vs-akka-streams.html - that benchmark is old and both Akka Streams and RxJava evolved a lot since then and I'm not sure about FS2, but I'm fairly certain that it already performs quite well when compared with Scalaz-streams.

**Comment by nitsanw** [comment]
@scottcarey The Disruptor is not a queue, and JCTools doesn't offer a Disruptor like construct, so comparing the performance is biased to your usecase. Underlying data structures are similar in places and they each specialize to the contract they offer, which means that a JCTools queue is a faster queue than a Disruptor based queue, while the Disruptor is a faster single-type ringbuffer reusable objects thingy than you could perhaps construct from the building blocks in JCTools.
 
"information in general on JCTools is sparse. The documentation is thin and the various queue flavor differences and behaviors are not well described." - Questions, issues and PRs are most welcome if you have particular concerns. For the queues part, performance is discussed on blog quite often, there are benchmarks for you to test for yourself and public APIs are documented. There's no "which queue for which usecase" guideline, is that what you mean? please file it as an issue and I will do my best to help.
Thanks

**Comment by alexandru** [comment]
@scottcarey if you're interested, I managed to optimize the existing implementation for `DropOld` and `ClearBuffer` with very decent results. Checkout the updated PR description, containing the benchmark results: https://github.com/monix/monix/pull/265

**Comment by alexandru** [comment]
Work for this issue is done - added benchmark details in the description, awaiting feedback and release in the next version (2.1).

**Comment by scottcarey** [comment]
@alexandru  great work!

Sorry, I wrote the below more than a month ago but it sat in my browser all this time:

Regarding `DropOld`, my intuition takes me to ring buffers where advancing when full implicitly means overwriting the oldest.  And that is perhaps why I started looking in the direction of the Disruptor with my use case.  However, for most cases a quality `DropNewWithSignal` or `OverflowStrategy.Fail` will be good enough.  In particular at the WebSocket level.  In the internal network messages on my distributed application however, newer messages are always more important than old ones -- but being forced to choose is a consequence of things going too slow, and so 75% of the time the best fix has been performance improvements (faster queues, optimized serialization, message batching, etc) rather than picking the flawless strategy for dropping messages.

**Comment by alexandru** [comment]
@scottcarey thanks,

Your right and in general newer messages are more valuable than older messages, since information loses value as time passes.

If possible, I think it's best if the system is tuned to not experience overflows, unless serious problems happen. In our system we apply throttling of messages (in the context of Monix that means operations like `sample`, `debounce`, `echo`, `distinctUntilChanged`, etc) and overflows are rare events. They do happen, but when they do, the dev-ops guys start getting alerts.

I view overflowing buffers as a protective measure. You're protecting the process from crashing in response to other systems on the network that are experiencing problems. When those problems happen, things aren't OK, but the important thing is for the system to detect problems and to recover automatically.
