### ISSUE TITLE
Add support for platforms that do not have sun.misc.Unsafe

### ISSUE THREAD

**Issue by alexandru** [monix/monix#270]
We've got problems with Android at least and possibly with the upcoming Java 9. See related issue #269.

1. the Atomic classes should support an Unsafe-free version, based on "atomic field updaters", supported since Java 5, see for example [AtomicIntegerFieldUpdate](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicIntegerFieldUpdater.html) as sample
2. we need to either fork the required [JCTools](https://github.com/JCTools/JCTools) implementations or find a replacement to be used for platforms that don't support `Unsafe`

**Comment by nitsanw** [comment]
You can use the org.jctools.queues.atomic.* queues when Unsafe is not available.
From #269 it would seem this can also be fixed with a patch to UnsafeAccess.

**Comment by alexandru** [comment]
@nitsanw issue #269 can be fixed with a patch to JCTools' UnsafeAccess, I was preparing it.

**Comment by alexandru** [comment]
@nitsanw see I've created a pull request, let me know what you think: https://github.com/JCTools/JCTools/pull/141

/cc @Taig
