### ISSUE TITLE
Provide a way or some document on how to efficiently convert to/from the Scalaz Task

### ISSUE THREAD

**Issue by alexandru** [monix/monix#274]
Currently `monix-scalaz` does not have operations for task conversions, because it only depends on `scalaz-core`. But we should provide at least a document for how to convert back and forth between these task implementations.

**Comment by jtcwang** [comment]
Can we use scalaz Task's `unsafePerformAsync` combined with monix's `Task.create` to avoid blocking?
In gitter chat you suggested `monix.Task.eval(scalaz.Task.unsafePerformIO)` but that's synchronous.

**Comment by lu4nm3** [comment]
Does it make sense to take a Monix Task, convert it into a cancelable future and then use the Delorean library to convert it to a Scalaz Task?

**Comment by jtcwang** [comment]
That's a roundabout way of doing it, I guess, since Delorean uses the same mechanism as I suggested to convert from Future.

**Comment by lu4nm3** [comment]
I see. What would be a good approach to go from ScalaZ -> Monix? I know @alexandru mentioned he was going to write some documentation for it soon but I'll admit that I'm a bit eager to see what that would look like.

**Comment by jtcwang** [comment]
This is roughly what I had:

```
import scalaz.concurrent.{Task => ScalazTask}
import monix.eval.Task
import monix.execution.Scheduler.Implicits.global

  implicit class ExtendedMonixTask[A](val task: Task[A]) extends AnyVal {
    def toScalaz: ScalazTask[A] = {
      ScalazTask.async[A] { cb  =>
        task.runAsync {
          new Callback[A] {
            override def onSuccess(a: A) = cb(a.right)
            override def onError(err: Throwable) = cb(err.left)
          }
        }
        ()
      }
    }
  }

```
Note that I'm using the global monix scheduler here - you might want to take an implicit Scheduler if you want to be able to specify another Scheduler at call site.

**Comment by alexandru** [comment]
At this point we have integration with Cats-Effect on master, so all conversions should go through the type classes provided by Cats-Effect.

Therefore one can provide a `cats.effect.Effect[scalaz.concurrent.Task]` instance and the conversion is handled. And this is recommended not just for Task conversions, but for interop with other libraries as well.

In an effort to cleanup the issue tracker, will now close this.
