### ISSUE TITLE
Performance regression in Task.flatMap

### ISSUE THREAD

**Issue by alexandru** [monix/monix#281]
We might have a slight performance regression for `Task.flatMap`.

- Context: https://twitter.com/alexelcu/status/811556784028717057
- Benchmarks: https://github.com/rossabaker/benchmarks/blob/master/results/0005.txt

**Comment by alexandru** [comment]
**Update:** unfortunately I discovered a big problem when upgrading to Scala 2.12.x

In Scala 2.11.8 the `scala.concurrent.forkjoin.ForkJoinPool` implementation is basically a fork of the JSR-166 implementation by Doug Lea, in order to provide support for older Java versions. However in Scala 2.12.x the implementation is now an alias for `java.util.concurrent.ForkJoinPool`, given of its available in Java 8 and the Scala 2.12 requirement to have Java 8 as a target.

Unfortunately these 2 implementations are NOT the same, the old Scala 2.11 implementation has better throughput in testing. The performance regression is about 50%, so that's quite significant.

Benchmark:
```scala
import monix.eval._
import scala.concurrent._
import duration._

// Piggybacks on Scala's own global
import monix.execution.Scheduler.Implicits.global

val size = 10000
def loop(i: Int): Task[Int] =
  if (i < size) Task(i + 1).flatMap(loop)
  else Task(i)

Await.result(Task(0).flatMap(loop).runAsync, Duration.Inf)
```

**Comment by alexandru** [comment]
UPDATE - I indeed discovered regressions from previous versions, due to the following reasons:

1. frame indexes (the counter we keep for doing the "batched execution" thing) are now transported over light async boundaries, but this implies usage of a `ThreadLocal` which isn't exactly cheap
2. all Monix `Task` operations are stack-safe and I took this to an extreme, but this means our `fork` evolved to deal with an extra light (trampolined) runnable - which is now eliminated, since I discovered another trick
3. the code paths for `Task.eval` and `Task.now` suffered due to the `Coeval` related changes; I have now partially reverted that integration and optimized the run-loop with some ugly (but controlled) mutation

As part of this process I also optimized the memory usage of `Task`, which should now be lighter on the garbage collector. On jumping over async boundaries we no longer create new callback instances and the used stack was converted from an immutable Scala `List` to a custom `ArrayStack` (also tuned for JS's growable arrays). This doesn't necessarily improve performance for the original benchmarks (e.g. tail recursion doesn't even hit this stack) and in testing I haven't seen a big difference in throughput, however what it does is to stabilize that performance, i.e. the results are now seemingly more predictable, due to (just a guess) being more CPU cache friendly.

In my own testing the performance improvement for `flatMap` loops is somewhere between 25% and 40%, depending on the test.

Soon to be released in a `2.2.0-M1`, pending PR: 
https://github.com/monix/monix/pull/283

**Comment by alexandru** [comment]
It's merged on master.

**Comment by jvican** [comment]
@alexandru Did we ever get closer to the performance that we had with the previous executor? I'm doing some heavy performance work and I'm optimizing for throughput on not so many threads. It would be great if there's still some room for improvement in schedulers optimized for this use case (`Scheduler.computation` doesn't seem to cut the best configuration in my preliminary results).

**Comment by Avasil** [comment]
@jvican I think @alexandru is back from vacation so hopefully he can answer :)
