### ISSUE TITLE
Executable finishes before observable completes. Inconsistency with documentation sample code

### ISSUE THREAD

**Issue by V-Lamp** [monix/monix#327]
Very basic problem but I have not found any solution after a couple of hours exploring the API.
``` scala
    import monix.execution.Scheduler.Implicits.global
    Observable.fromIterator(Iterator.from(0)).foreach(println).foreach(_ => println("END"))
``` 
Stops early and "END" is not printed (2nd foreach is on future). How to keep a subscribed observable alive?

**The example on the website appears to have the same issue:**
``` scala
import monix.execution.Scheduler.Implicits.global
 val tick = {
    Observable.interval(1.second)
      // common filtering and mapping
      .filter(_ % 2 == 0)
      .map(_ * 2)
      // any respectable Scala type has flatMap, w00t!
      .flatMap(x => Observable.fromIterable(Seq(x,x)))
      // only take the first 5 elements, then stop
      .take(5)
      // to print the generated events to console
      .dump("Out")
  }
  val cancelable = tick.subscribe()  
```
```
C:\Program Files\Java\jdk1.8.0_112\bin\java" ....
0: Out-->0
1: Out-->0

Process finished with exit code 0
```
It stops before the 2nd tick.

This is with the latest monix:
```sbt
scalaVersion := "2.11.8"
libraryDependencies += "io.monix" %% "monix" % "2.2.2"
```
But I also tested with 2.0.6 and I get the same behaviour

**Comment by alexandru** [comment]
@V-Lamp both examples work as they are supposed to do. You get an early termination because the threads created by the `Scheduler` that you're using (`monix.execution.Scheduler.Implicits.global`) are daemonic threads and won't block the application from exiting when your `main` finishes. They are daemonic because non-daemonic threads are even more annoying. 

This means you need to block your `main` thread in order to keep it from quitting:

```scala
import monix.reactive._
import monix.execution.Scheduler.Implicits.global
import scala.concurrent.Await
import scala.concurrent.duration.Duration

val future = Observable.fromIterator(Iterator.from(0))
  .foreach(println)
  .foreach(_ => println("END"))

Await.result(future, Duration.Inf)
```

Note that in this sample you'll never see an `END` either, because the observable you're creating here is infinite.

If you don't like daemonic threads, you can always configure your own `Scheduler`:
```scala
import monix.execution.Scheduler

implicit val scheduler = Scheduler.forkJoin(
  name="my-forkjoin", 
  parallelism=4, 
  maxThreads=128, 
  daemonic=false
)

// When you want to quit ...
scheduler.shutdown()
```

**Comment by alexandru** [comment]
Please confirm that this fixes your issue.

**Comment by V-Lamp** [comment]
Thanks Alexandru, that solves it. And thanks for the quick reply as well!

In case someone else is stuck on this, I now see that the canonical way to do this probably is:

``` scala
def runAsync(implicit s: Scheduler): CancelableFuture[A]
``` 

on ` Task[A]`, which is returned by many "reducing" methods on observable, or directly

``` scala
def runAsyncGetFirst(implicit s: Scheduler): CancelableFuture[Option[A]]
def runAsyncGetLast(implicit s: Scheduler): CancelableFuture[Option[A]]
``` 

on `Observable[A]` to gain access to a `CancelableFuture[A]` that you can ultimately await.
