### ISSUE TITLE
Feedback Request: Should we depend on Typelevel Cats?

### ISSUE THREAD

**Issue by alexandru** [monix/monix#342]
This is an open question, soliciting feedback from users.

## Current Status

Up until now (current version `2.2.x`), we have supported both Cats and Scalaz in Monix, by providing a shims compatibility layer, similar with [djspiewak/shims](https://github.com/djspiewak/shims).

We exposed this compatibility layer in [monix-types](https://github.com/monix/monix/tree/v2.2.4/monix-types/shared/src/main/scala/monix/types). Users wanting to have common type-class implementations for `Task`, `Coeval` and `Observable` had to import either:

- [monix-cats](https://monix.io/docs/2x/intro/cats.html), for [Typelevel Cats](http://typelevel.org/cats) integration
- [monix-scalaz](https://monix.io/docs/2x/intro/scalaz72.html) for [Scalaz](https://github.com/scalaz/scalaz) integration

This involved an extra import, bringing extra implicit conversions in scope:

```scala
import monix.cats._
```

And we also have conversions in reverse:

```scala
import monix.cats.reverse._
```

With the caveat that having both of these imports in scope generates conflicts.

## Problems with Current Approach

The 4 big problems I'm seeing:

1. **Duplication of effort:** having to maintain our own type-class definitions, with our own laws, duplicating everything we need for Cats and Scalaz really sucks. I don't want us to keep reinventing the wheel and if there are useful type-classes that are needed, I'd rather try and push those changes in Cats. See for example current efforts such as:
  - [MonadDefer PR](https://github.com/typelevel/cats/pull/1552)
  - [Typelevel Effects](https://github.com/typelevel/general/issues/66)
2. **Performance:** working with type-classes in Scala is usually problematic, due to reliance on implicits and the needed conversions (e.g. `cats.syntax`) and conversion from `monix.types.Monad[Task]` whenever `cats.Monad[Task]` is needed introduces another needed conversion in that workflow, creating instances every time such an instance is requested, putting pressure on the GC ... and yes, the JVM runtime can do *magic* (escape analysis, etc), but the JVM doesn't have unlimited budget for such optimizations
3. **Complexity pushed to the user**: users have to do `import monix.cats._` by themselves, they have to read the docs first in order to find out about it and those imports can generate conflicts if not careful (e.g. in combination with `import monix.cats.reverse._`)
4. **Interoperability:** the upcoming `Iterant` type is built in a generic way, making use of type-classes and would be much more useful if it used the Cats type-classes directly; if it doesn't use Cats' hierarchy, I have a feeling that nobody will want to use anything other than `Iterant[Task]`, in which case maybe I shouldn't bother with a generic implementation, or with such a data type implementation at all

## External Events that Prompted this Question

Two things happened lately:

1. Monix is now a @Typelevel project with full membership, see [typelevel/general/issue/61](https://github.com/typelevel/general/issues/61) and see it listed at [typelevel.org/projects](http://typelevel.org/projects/)
  - This indirectly implies a responsibility for us to play extra well within the emerging Typelevel ecosystem
  - Playing well / cooperating with others will benefit Monix's users as well
2. Other projects like `http4s` and `doobie` are now standardizing on Cats, for some of the same reasons (complexity of shims, maintainance), see: https://http4s.github.io/fp-ecosystem/

## Problems with Cats Standardization

For Cats users:

1. Cats is not stable yet, breaking binary compatibility between middle versions (e.g. `0.8` to `0.9`). This is understandable, given it's still in progress, even though I can see some stabilization going on (releases aren't made that often) and with Scala 2.12 things should be much better because of the new traits encoding. But from what I understand `1.0.0` will happen during the course of this year. I'm sure that the Cats contributors aren't treating this lightly, since Cats is supposed to be a standard library for FP.
2. We can no longer provide compatibility with multiple Cats versions and make no mistake, there will be a Cats `2.0`, a Cats `3.0`, etc.

For users of Scalaz:

1. We do in fact have Scalaz users, judging by the approximately 500 monthly downloads for the `monix-scalaz` JARs. These users might object to have `cats-core` on their classpath for various reasons.
  - I really don't want to upset the Scalaz users that we have, this is in no way a political move, the problem is that supporting both projects is expensive and without a reasonable solution, we are pushing complexity to the call site
2. As @toxicafunk correctly points out - in restrictive corporations that need to approve all dependencies used, if you have Scalaz and Monix approved, then Cats is a tough sell for management (and probably vice-versa), given that it's being used indirectly

For all users:

1. `monix-types` is light compared with `cats-kernel` and `cats-core`. This will seem like a problem for:
  - Scala-js users, however I tested with [monix-sample](https://github.com/monix/monix-sample), and the size of the optimized JS file *DID NOT increase*, due to optimizations in the Scala-js compiler and usage of Google Closure's advanced optimizations; basically Cats gets eliminated if unused
  - Android users, but they are applying [Proguard](https://www.guardsquare.com/en/proguard) anyway, to achieve those same size optimizations 
2. Any dependency imported in the classpath creates the potential for the "*DLL Hell*" effect - so if the user does not use Cats, but imports Monix + some other dependency that depends on Cats, both of which depend on different and incompatible Cats versions somehow, then he'll end up with a potential problem that can manifest in production

## Potential Alternative

I'm currently investigating ways to make `cats-core` and `scalaz-core` dependencies that are `"provided"` instead of `"compile"`, thus making them non-transitive and optional.

Maybe it works with macros, I'm exploring possibilities.

## What Do You Think?

Currently no decision has been made.

I do have an experimental branch on which I did these changes for testing purposes, see [monix/tree/cats](https://github.com/monix/monix/tree/cats).

I really want consensus on this. If the current user base thinks this would be bad, or premature, then we can cancel or postpone such a direction.

**Comment by weihsiu** [comment]
i am all for the cats-only monix.  there are somethings that scalaz can do
that cats can't but the gap is closing.  it seems to me that most of the
"modern" libraries i use nowadays, when they need to depend on a fp
library, they always choose cats already.

**Comment by toxicafunk** [comment]
Having `cats-core` along with `scalaz` sounds dangerous. I can understand if you want to develop for cats first and then make sure it works on Scalaz, but making a Scalaz user import `cats-core` sounds... well it sounds dumb IMHO. If for whatever reason I chose to use Scalaz over Cats (even if I switch in the future) why would you make me depend on `cats-core` to use Monix?

**Comment by etorreborre** [comment]
I vote for monix being based on cats. And having a separate project to convert cats typeclasses to Scalaz typeclasses when it is necessary.

**Comment by alexandru** [comment]
@toxicafunk I'm interested in your opinion, can you please provide details? Why do you think it's a problem having `cats-core` on your classpath, in addition to `scalaz-core`?

There is some duplication of course, but the same duplication exists right now in `monix-types` - which is lighter indeed, but it's there anyway. And as I said, we have to duplicate all the type-classes that we want to support. 

If you're worried about size, as I said, Scala.js and Proguard are going to eliminate Cats completely from your package if you're not using it.

**Comment by toxicafunk** [comment]
@alexandru I'm arguing without knowledge of Monix internals but I'm actually more worried about inter-operability. I'm thinking about implicits resolution or *Ops definitions, etc.

Also, thinking about Monix as a product I don't think it makes sense to have this dependency. For instance, imagine the company I work for is very strict and they have audited/authorized the use of Scalaz but not of Cats, do I make them authorize the use of Cats (when I don't even know Cats) or do I look for a Moniz alternative? This is not my current case, but I had a similar situation not long ago with a customer.

**Comment by alexandru** [comment]
@toxicafunk 

I don't see a problem with interoperability, however speaking of approving the used dependencies, that's a useful objection, will take it into consideration.

Thanks for the feedback,

**Comment by sellout** [comment]
I’ve also tried to be non-committal, but without much success. I think the one case where having separate projects like `monix-cats` and `monix-scalaz` is still the right answer is when they contain only Cats-specific instances for Monix type classes, and Monix-specific instances for Cats type classes.

As soon as you need those Cats/Scalaz type classes or instances in Monix proper, you should switch to Cats and let users of Scalaz depend on @djspiewak’s upcoming shims formulation (which may work in the opposite direction as well, but unless your library is already Scalaz-only, I don’t see much reason to choose that direction).

@toxicafunk The fundamental problem is that trying to support both Cats and Scalaz in a library is painful – both to the library author as well as the users. We’re trying to figure out how to minimize that pain. The recently-settled-on approach by a few authors has been that we should support Cats directly, which eliminates pain for both library authors and for library users that don’t depend on Scalaz. And (hopefully, with @djspiewak’s new shims) not increase the pain for library users that _do_ depend on Scalaz. Your concerns re: implicits and `Ops` are valid, but are hopefully addressed with shims.

I think for companies that haven’t approved Cats for use, they are going to soon find themselves in the position with various libraries where they are working from some barely-maintained branch that continues to exist for Scalaz support, or even having to manage those branches themselves. There are already a number of good libraries that don’t support Scalaz at all, and more have made that decision going forward.

**Comment by raulraja** [comment]
@alexandru :+1: on standardizing to cats and agreed with @etorreborre statement.

**Comment by travisbrown** [comment]
For what it's worth we've been getting around 2.5k downloads of circe-optics per month, and it depends on both Cats and Scalaz (via Monocle). This is a pretty substantial chunk of circe users (like 10%, I'd guess), and I've heard zero complaints about this issue specifically (either about how the interop actually works or the politics of requiring both dependencies).

Depending on both isn't ideal, but it's not dangerous, and a lot of orgs are going to be stuck with both for a long time whether or not Monix makes this change.

**Comment by rossabaker** [comment]
As soon as you've reinvented a typeclass that's in Cats, just depend on Cats.  When multiple libraries do as Monix does today, the result is a thicket of interop imports for the end user.  Natively supporting one, and letting shims be the universal bridge, is going to be a better experience for people on either side of that bridge than umpteen redefinitions of standard typeclasses.

**Comment by alexandru** [comment]
@toxicafunk 

I may have found a way to depend on Cats and provide the needed type-class instances out of the box, while making it optional. Still playing, not 100% sure if it will work OK, but the gist is this:

1. we can make `monix-eval` (Task) and `monix-reactive` (Observable) depend on `cats-core` as a `"provided"` dependency, so this makes it non-transitive
2. the implicit instance in the companion objects of these types will get built by macros ... which is great, because AFAIK macros are compile time only and do not appear in the bytecode as methods recognized by the JVM, so the JVM has no reason to complain if those classes can't be instantiated due to Cats missing from the classpath

This opens the possibility of using it with Scalaz without necessarily having Cats in your classpath. The out of the box experience for Scalaz won't be so nice and we can't maintain `import monix.scalaz._` because of the modular nature of Monix. So we'd need to have multiple imports like `import monix.eval.scalaz._`, `import monix.reactive.scalaz._`, etc.  Which wouldn't be absolutely awful, given your main complain would be gone.

I'm still unsure if this works, experiment is in progress.

**Comment by toxicafunk** [comment]
@alexandru that sounds solid! While on the subject, and since everyone argue Cats is the way of the future, anyone has links to a Scalaz vs Cats comparison, specially why Cats seems the way forward?

Thanks!

**Comment by alexandru** [comment]
@toxicafunk that's a little offtopic for this issue, however I encourage you to come and talk on Gitter with the Typelevel / Cats folks.  That is [typelevel/general](https://gitter.im/typelevel/general) and [typelevel/cats](https://gitter.im/typelevel/cats).

There you'll find current and former Cats and Scalaz contributors and they'll be happy to answer this question.

**Comment by macalinao** [comment]
I vote for Cats-only Monix, as Cats is very lightweight and seems to be the future.

**Comment by fsvehla** [comment]
👍 for Cats.

I never ran into any issues having Cats and Scalaz on the class path (because of Monocle for example)

**Comment by fwbrasil** [comment]
@alexandru I have plans to integrate Monix into all sub-modules provided by [Quill](http://getquill.io) and wouldn't do so if it implies having Cats on the classpath. I may never get to it since I'm working on other OSS projects, but I thought it'd be worth giving you feedback on the ticket anyway.

**Comment by fsvehla** [comment]
@fwbrasil May I ask why having Cats on the classpath is an issue for you?

**Comment by fwbrasil** [comment]
@fsvehla In general, we try to avoid adding new dependencies to Quill. For instance, the `jdbc` module has only HikariCP connection pool as dependency. Having very few dependencies allows us to reduce binary compatibility issues. Also, there some companies that don't accept scalaz/cats on the classpath.

@alexandru please don't block the migration to cats because of Quill. Open source shouldn't be a burden for us, so if it makes things easier for you, I'd say go ahead!

**Comment by alexandru** [comment]
Status update - a decision on this issue is still pending because of this Scala PR which might get shipped in Scala 2.12.3: https://github.com/scala/scala/pull/5350

This adds `-Ysysdef` and `-Ypredef` flags to control what gets imported by default in all Scala files. With some syntactic sugar in SBT (maybe provided by a plugin in the beginning), what this means is that users might have an easier time using orphaned type class instances (instances that aren't visible by default, possibly defined in a different compilation unit).

Therefore this pushes complexity at project setup time and I think users get over this with properly written documentation and maybe some SBT support for being able to define a sane list of default imports.

Monix being modular, this might mean that we can leave `monix-eval` and `monix-reactive` free from a Cats dependency and it might mean that we can keep supporting Scalaz users as well.

NOTE: I do not know if we can rely on this feature, it's just a current idea. But for people wanting to play with this, the feature is available in the latest Typelevel Scala release, see https://github.com/typelevel/scala/blob/typelevel-readme/notes/typelevel-4.md

**Comment by alexandru** [comment]
See https://github.com/monix/monix/pull/370
