### ISSUE TITLE
Consumer.contransform

### ISSUE THREAD

**Issue by ArturSoler** [monix/monix#348]
Implement, in Consumer, the `contransform` operator, which transforms the Observables where the consumer is attached to.

The signature would be something like: `def contransform(f: Observable[A] => Observable[B]): Consumer[A]`

**Comment by alexandru** [comment]
Implemented operation is named `transformInput`, since `contransform` was an awkward name.

**Comment by alexandru** [comment]
Going to cut the `2.3.0` release tomorrow.
