### ISSUE TITLE
CoevalLawsSuite and TaskLawsSuite failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [monix/monix#366]
as seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1515/consoleFull

```
[monix] [error] Failed tests:
[monix] [error] 	monix.cats.tests.CoevalLawsSuite
[monix] [error] 	monix.cats.tests.TaskLawsSuite
```

**Comment by alexandru** [comment]
@SethTisue thanks, is this compiled against Cats master?

Will fix.

**Comment by SethTisue** [comment]
> is this compiled against Cats master

yes, and if it turns out that cats master is too unstable, it would be possible for us to freeze it.

I'm running a test right now to see whether freezing monix at the last green revision fixes it.

**Comment by alexandru** [comment]
@SethTisue this is about a new law they introduced in `MonadError` for "ensureOr consistency".

It happens and it might indicate a potential problem in Monix. Will investigate.

**Comment by SethTisue** [comment]
ah wait but monix hasn't changed since May 3 I see. I'll try freezing cats temporarily.

**Comment by SethTisue** [comment]
>  I'll try freezing cats temporarily.

done, community build green again, at some point we'll want to move to newer code again, but no rush

**Comment by alexandru** [comment]
Thanks for the patience @SethTisue. Now that Cats 1.0.0-MF is out, the `master` in Monix is fixed and should be fine.

Let me know.

**Comment by SethTisue** [comment]
I think we could close this ticket, then, and just leave scala/community-builds#549 open (I'll tackle it before too much longer).

**Comment by alexandru** [comment]
Cool, closing this.
