### ISSUE TITLE
New operator `Observable.intersperse`

### ISSUE THREAD

**Issue by omainegra** [monix/monix#367]
It could be useful an operator that emit a specific separator between every pair of elements, with an optional start and end element.

The signature could be like:
```scala
def intersperse(sep: A): Observable[A] =
def intersperse(start: A, sep: A, end: A): Observable[A]
```

Here is an example of usage:
```scala
val fooObservable: Observable[Foo] = ...
fooObservable.map(_.asJson.spaces2).intersperse("[", ",", "]")
```

And the output will be:
```json
[{"id": 1, "name": "Foo"}, {"id": 2, "name": "Bar"}, {"id": 3, "name": "Baz"}]
```

**Comment by mihaisoloi** [comment]
This looks like an interesting operator to have, but how would it be more general? i.e for more than 2 elements. Currently you can achieve the same result with a `scan` or `bufferSliding` and then a `map`.

I'd say it makes more sense to have this as a `start` of observable, `sep` between all of the elements and `end` when the observable ends similar to a `mkString` on a collection.

**Comment by omainegra** [comment]
Yes, the idea is to emit an optional first element, then the upstream elements paired with the separator, except that the separator won't be emitted last, and finally an optional last element. I've update the issue description.

**Comment by mihaisoloi** [comment]
I'll try to work on a PR, looks interesting

**Comment by alexandru** [comment]
N.B. this can be achieved somewhat with:

```scala
source.flatMap { elem =>
  Observable(elem, sep)
}
```

The problem here is that, I'm assuming, you don't want that final `sep`, so some start and end logic is required. Which is doable already using , but kind of complicated.

@omainegra I think you mentioned on Gitter that you already have your own implementation, you can share that if you want in a PR.

**Comment by omainegra** [comment]
@alexandru Yes I will, but I'm still testing it, maybe today or tomorrow I could push it
