### ISSUE TITLE
assert in ConcatMap.onNext

### ISSUE THREAD

**Issue by volth** [monix/monix#375]
The code below works with monix 2.0.x and 2.1.x but fails with 2.2.x and 2.3.0 with 
```java.lang.IllegalStateException: State WaitComplete(Some(java.lang.Throwable)) in the Monix ConcatMap.onNext implementation is invalid, please send a bug report! See https://monix.io```

Precisily, it works before https://github.com/monix/monix/commit/a0a41d2621f0f470f4b20560d7d67ac910428604

```
import scala.concurrent.Await
import scala.concurrent.duration._
import monix.reactive.{Observable, Notification}
import monix.execution.Scheduler.Implicits.global

class ResultSet 

trait QueryExecutor {
  def query(sql: String): Observable[ResultSet]

  def wrapped[A](before: String,
                 after: (/*before's*/ List[ResultSet], /*body's*/ Option[Throwable])=>String)
                (body: QueryExecutor=>Observable[A]): Observable[A] = {
    Observable.fromTask(query(before).toListL) flatMap {
      r => body(this).materialize flatMap {
             case Notification.OnNext(v)  => Observable(v)
             case Notification.OnComplete => query(after(r, None   ))             flatMap (_ => Observable.empty        ) // ignore `after` success
             case Notification.OnError(e) => query(after(r, Some(e))).materialize flatMap (_ => Observable.raiseError(e)) // ignore `after` failure
           } doOnDownstreamStop {
             throw new IllegalStateException("wrappedQuery.doOnDownstreamStop: observable is not consumed fully")
           } doOnSubscriptionCancel {
             throw new IllegalStateException("wrappedQuery.doOnSubscriptionCancel: observable is not consumed fully")
           }
    }
  }

  def inTransaction[A](body: QueryExecutor=>Observable[A]): Observable[A] = wrapped("BEGIN", { case (_, None) => "COMMIT" case (_, Some(_)) => "ROLLBACK" })(body)
}

class Pool extends QueryExecutor {
  def query(sql: String): Observable[ResultSet] = Observable(new ResultSet)
}

object Hello extends App {
  val pool = new Pool

  val tx: Observable[Boolean] = pool.inTransaction[Boolean] { conn =>
                                  conn.query("INSERT INTO TX_TEST(ID) VALUES(9)") flatMap { (result: ResultSet) =>
                                    Observable.raiseError(new Throwable) // rollback the transaction
                                  }
                                }
  println(Await.result(tx.lastL.materialize.runAsync, 5.seconds))
}
```

**Comment by alexandru** [comment]
@volth the new `ConcatMap` implementation ends up being defensive due to possible race conditions; that logic is indeed very risky, which is why I wanted all that stumble upon those errors to fill bug requests.

That said, that error also happens when the Observer's back-pressure contract gets violated in some way or another. I'm not discounting the possibility of an actual error though.

On first sight, nothing wrong jumps at me and I'll investigate this. But maybe you can help me out with a minimal sample that I can run for myself, please?

Thanks for opening the issue.

**Comment by volth** [comment]
The example above should be runnable (```Hello3``` is the main class, it extends ```App``` from scala library which implements ```main``` function), it depends only on monix.

**Comment by alexandru** [comment]
@volth thanks, I'm caught at work atm, will try it soon.

**Comment by volth** [comment]
I tried the testcase few months ago with ```3.0.0-RC1``` and there was no bug (or I forgot how to reproduce it :)
