### ISSUE TITLE
flatMap on CancelableFuture

### ISSUE THREAD

**Issue by larsrh** [monix/monix#381]
Currently, the `flatMap` operation takes a function `A => Future[B]`. But there's no check that the resulting `Future[B]` might be cancelable itself. Hence, cancelling the returned `CancelableFuture[B]` might not cancel correctly. Here's my workaround:

```scala
  final implicit class CancelableFutureOps[A](future: CancelableFuture[A]) {
    def flatMapC[B](cont: A => CancelableFuture[B])(implicit ec: ExecutionContext): CancelableFuture[B] = {
      val conn = MultiAssignmentCancelable()
      val c1 = future.flatMap { a =>
        val c2 = cont(a)
        conn.orderedUpdate(c2, order = 2)
        c2
      }

      conn.orderedUpdate(c1, order = 1)
      CancelableFuture(c1, conn)
    }
  }
```

In principle, this could go into `CancelableFuture` itself, where there could be an `asInstanceOf` check.

**Comment by alexandru** [comment]
Hey,

Yeah, it might be a good idea.
