### ISSUE TITLE
Additional Observable operators wanted, they are awesome

### ISSUE THREAD

**Issue by mmuschalik** [monix/monix#385]
Hi guys,

One of the reasons this library stands out to others is that it has zip and combineLatest on observables. I don't think I've seen this in other libraries such as Akka Streams. I would LOVE to see more of these. In particular I'm thinking of a combineLatest that favours the one stream over another. 

Given two observables o1 & o2, I want the following to apply:

1) Only emit tuple when o1 emits a result (with exception of first tuple which should wait for o2's first value)
2) inspecting the first element of the tuple over time will yield no repeating elements. This implies the second element could potentially have repeating items over time, because it can use the latest emitted value. Obviously none of o2's values should be missed meaning back pressure may need to be applied if o2 wants to submit its next value before o1's next value.

What do you guys think? I want to use this type of logic for joining streams where I want to really react precisely on one stream and conveniently consume the other stream further when that occurs.

**Comment by mmuschalik** [comment]
Now that I read that, there is a potential consequence. o1 might complete before o2 in which case data in o2 would be dropped.

**Comment by alexandru** [comment]
@mmuschalik have you seen [withLatestFrom](https://monix.io/api/2.3/monix/reactive/Observable.html#withLatestFrom[B,R](other:monix.reactive.Observable[B])(f:(A,B)=%3ER):Self[R])?

**Comment by mmuschalik** [comment]
Thanks for that. I just tried, but it seems to be dropping values of the second observable.

**Comment by alexandru** [comment]
@mmuschalik help me understand the behavior,

So given the following two observables, what would be the approximate output?

```scala
val o1 = Observable.interval(1.second, 1.second).take(3).dump("O1")

val o2 = Observable.interval(500.millis, 500.millis).take(8).dump("O2")

myCombination(o1, o2).dump("C")
```

In case both should emit at the same time, like when the clock is at 1 second, assume that `o1` wins the race and emits before `o2`.

I would like a sample like the following, which would be the output of `combineLatest`:

```scala
// 0.6 s
O2 --> 1
// 1 s
O1 --> 1
C   --> (1, 1)
O2 --> 2
C   --> (1, 2)
// 1.5 s
O2 --> 3
C   --> (1, 3)
// 2 s
O1 --> 2
C   --> (2, 3)
O2 --> 4
C   --> (2, 4)
// 2.5 s
O2 --> 5
C   --> (2, 5)
// 3 s
O1 --> 3
C   --> (3, 5)
O2 --> 6
C   --> (3, 6)
// No more O1 updates from here on
O1 completed
// 3.5 s
O2 --> 7
C   --> (3, 7)
// 4 s
O2 --> 8
C   --> (3, 8)
```

**Comment by mmuschalik** [comment]
// 0.6 s
O2 --> 1
// 1 s
O1 --> 1
C   --> (1, 1)
O2 --> 2
                                  // no because o1 needs to come first C   --> (1, 2)
// 1.5 s
                                 // not possible, O2 is back pressured O2 --> 3
                                 // no because o1 needs to come first  C   --> (1, 3)
// 2 s
O1 --> 2
C   --> (2,2)              // we dont want to lose O2's number 2 C   --> (2, 3)
O2 --> 3                                // O2's number 3 can be sent now, O2 --> 4
                                 // have to wait for O1 C   --> (2, 4)
// 2.5 s
// not possible have to wait for O1.  O2 --> 5
// not possible have to wait for O1.C   --> (2, 5)

I'll stop here, hopefully I'm making sense? In other words it almost looks like zip. The difference is O1 doesn't wait for O2 (except for first element) because the operation can use the latest value of O2. O2 has to wait for O1's next value.

**Comment by mmuschalik** [comment]
Example result:

(1,1)    // wait for both
(2,1)    // o1 sent 2, repeat o2
(3,2)    // o1 sent 3, o2 sent 2 just before
(4,3)    //  o1 sent 4, o2 sent 3 just before
(5,3)    // o1 sent 5, o2 nothing yet, repeat 3

**Comment by alexandru** [comment]
@mmuschalik why did you close the issue?

Sorry for not replying, but I'm away on vacation. Will be back on Monday.

**Comment by mmuschalik** [comment]
Oh sorry.

**Comment by alexandru** [comment]
@mmuschalik we can add more observable operators, the reason for why some suggestions linger is that non-orthogonal operators can cause confusion, because you end up with multiple ways of doing things. Observable's operators are already non-orthogonal, plenty of examples there, but striving to keep a balance there.

I'm still trying to wrap my head around your sample above.

What does RxJava's `join` do? Open another ticket, it's fine.

**Comment by alexandru** [comment]
@mmuschalik I'm cleaning up the issue tracker. If you want to continue the conversation, you can re-open this one or open a new one.
