### ISSUE TITLE
Iterant operators

### ISSUE THREAD

**Issue by alexandru** [monix/monix#400]
Opening this issue to track the implementation of the `Iterant` operators that we need before releasing version 3.0.0.

These are the deterministic operators that are more or less available for `Observable`:

- [x] `:+` / `append`, but this can be based on `++`
- [x] `bufferTumbling(count: Int)`: being basically `bufferSliding(count, count)`
- [x] `bufferSliding(count: Int, skip: Int)`: is `sliding` from Scala's collections
- [x] `countL`: counts the number of items emitted by the source
- [x] `liftMap` / `liftMapK`: for transforming `F[_]` references into `G[_]`
- [x] `distinctUntilChanged`
- [x] `distinctUntilChangedByKey`
- [ ] `dropLast`
- [ ] `takeWhileWithIndex`
- [ ] `dropWhileWithIndex`
- [ ] `takeWhileNotCanceled`
- [x] `dump`
- [x] `foldRightL`
- [x] `findL`
- [ ] / `firstOrElseL`
- [ ] `flatScan` (?)
- [x] `scanEval`
- [x] `fold(implicit A: Monoid[A])`
- [x] `foldWhileLeftL` / `foldWhileLeftEvalL`
- [x] `forAllL`
- [x] `existsL`
- [ ] `nonEmptyL`
- [x] `headL`
- [ ]  `isEmptyL`
- [ ] `interleave`
- [x] `maxL`
- [x] `maxByL`
- [x] `minL`
- [ ] `minByL`
- [ ] `onErrorFallbackTo`
- [x] `reduceL` (e.g. like `foldLeft`) ... n.b. inconsistent naming in Observable, should be fixed
- [x] `foldL` (working on Monoid, instead of `sumL`
- [ ] `switchIfEmpty`
- [ ] `takeEveryNth`
- [x] `zipWithIndex`
- [ ] `intersperse`

Not sure if possible because we lack the required type classes, unless we introduce our own:

- [ ] `memoize`

**Comment by Avasil** [comment]
@alexandru any other operators I could implement?

**Comment by alexandru** [comment]
@Avasil do `minByL` and `maxByL` if not implemented yet

**Comment by Avasil** [comment]
We can check boxes for ```dump```, ```zipWithIndex```, ```maxByL``` and ```minByL```

**Comment by alexandru** [comment]
I have opened separate issues for all operators that are of interest at the moment, so closing this one.
