### ISSUE TITLE
Should Monix v3 use different package / artifact id?

### ISSUE THREAD

**Issue by alexandru** [monix/monix#406]
Monix v3 breaks binary and source compatibility.

Should it use a different package and artifact id, such that multiple versions can coexist?

Context:

- discussion on Cats versioning: https://github.com/typelevel/cats/issues/1233#issuecomment-320468526
- [Spec-ulation Keynote](https://www.youtube.com/watch?v=oyLBGkS5ICk) by Rich Hickey

**Comment by dispalt** [comment]
I personally don't like the netty situation, so I vote same artifact Id.  Also seems more okay since cats is undergoing the same transition

**Comment by alexandru** [comment]
@dispalt care to elaborate on the Netty situation, as I'm not familiar?

**Comment by dispalt** [comment]
Fact: Netty 3 and 4 have different coordinates

Opinion: It doesn't encourage upgrading and allows dependents to get lazy on upgrading.  I think the ethos of scala is to encourage quick iteration, therefore I vote no to multiple coordinates.  I also voted on twitter.

**Comment by alexandru** [comment]
@dispalt thanks,

Well, for the moment it appears that the people preferring different packages are in a minority.

**Comment by hepin1989** [comment]
I vote not change it.
For Netty ,it's because them trans from jboss .

**Comment by scottcarey** [comment]
Different artifact id, and package.  Anything else is insane.

Fact: Java's Jackson 1 and 2 have different coordinates and packages.   

Opinion: It saved the project.  Downstream dependencies that are not well maintained or have major difficulties upgrading (e.g. Hadoop / spark) can still have an old version.   Migration can be incremental and it doesn't much matter if a transitive dependency deep in the stack (I have ~ 500 jars in my dependency tree in some projects) uses the old version.

For Monix, I suppose there isn't as much legacy footprint and I'm not likely to run into issues transitively at this time.  It may not be a big deal, but once any project becomes widely adopted and is something lower level that is likely to pop up in disparate transitive dependencies (like netty, jetty, json libraries, serialization libraries), artifact / package shifting is critical.

I've spent far too much of my life dealing with jar hell that could have been prevented by projects being more willing to move artifact/package on major upgrades.

But what this does do, is make me very hesitant to adopt Monix any further today, and instead wait for 3.x.  I've got a couple projects that could use it, but ... this has given me second thoughts.

**Comment by tkroman** [comment]
If there are changes that don't require changes on the call-site but bear a semantic difference, I'd go with new module + an extensive changelog which is googleable so the gitter channel isn't overwhelmed by the "How do i move from `foo()` to `bar()`?". 
Otherwise, if the broken source compatibility means renames/moves etc, I'd go with the same package since there is no danger to miss the critical migration.

**Comment by alexandru** [comment]
@tkroman the issue isn't really about direct dependencies, because presumably the compiler helps a lot, plus we've got tests.

The issue is with transitive dependencies, for which the compiler does not complain that `foo()` was renamed to `bar()` because the compiler is not involved at all.

**Comment by alexandru** [comment]
This has been settled. Community hasn't agreed to it, so I won't do it.
