### ISSUE TITLE
Add Iterant.dump method

### ISSUE THREAD

**Issue by alexandru** [monix/monix#434]
`Observable` has the `.dump` utility that we need for `Iterant`:

- [API Documentation](https://monix.io/api/2.3/monix/reactive/Observable.html#dump(prefix:String,out:java.io.PrintStream):Self[A])
- Source code: [Observable.scala](https://github.com/monix/monix/blob/v3.0.0-M1/monix-reactive/shared/src/main/scala/monix/reactive/Observable.scala#L1210) and [DumpObservable](https://github.com/monix/monix/blob/v3.0.0-M1/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/DumpObservable.scala)

Signature: 

```scala
sealed abstract class Iterant[F[_], A] {
  // ...
  def dump(prefix: String, out: PrintStream = System.out): Iterant[F, A]
}
```

Usage:

```scala
Iterant[Task].range(0, 4)
  .dump("O")
  .completeL.runAsync
```

What this does is to dump the incoming events to standard output, like so:

```scala
O --> 0
O --> 1
O --> 2
O --> 3
O completed
```

**Comment by Avasil** [comment]
I'd like to take this one as well :)

**Comment by alexandru** [comment]
Ah, right, yeah, do the output like what we have with `Observable`, those index numbers are important, although you might add some spacing into `Observable` as well.

This is output meant for debugging, so people shouldn't have parsed that output anyway.

**Comment by alexandru** [comment]
@Avasil and yes, feel free to work on it.

**Comment by alexandru** [comment]
Sovled in #439.
