### ISSUE TITLE
Iterant .zipWithIndex

### ISSUE THREAD

**Issue by alexandru** [monix/monix#435]
Need the `zipWithIndex` operator on `Iterant`:

```scala
sealed abstract class Iterant[F[_], A] {
  //...
  def zipWithIndex(implicit F: Sync[F]): Iterant[F, (A, Long)]
}
```

**Comment by Avasil** [comment]
@alexandru I would love to attempt this issue in next few days, as soon as I get more familiar with ```Iterant```

**Comment by alexandru** [comment]
This was solved in #437 — btw @Avasil you can put `Fixes #issue-nr` in the description of the PR, then when we merge it, it automatically closes the ticket.

**Comment by Avasil** [comment]
@alexandru 
Sorry for that, I'll have that in mind, we need to also close #434 and #421

**Comment by alexandru** [comment]
@Avasil no need to apologize, it was just an FYI about how GitHub works.
