### ISSUE TITLE
Observable.mapParallelUnordered needs configurable overflow strategy

### ISSUE THREAD

**Issue by alexandru** [monix/monix#440]
The `mapParallelUnordered` operator needs a configurable overflow strategy, much like `merge`.

So we need to take it as an implicit, with a default value, just like `merge`, with a signature like:

```scala
final def mapParallelUnordered[B](parallelism: Int)(f: A => Task[B])
  (implicit os: OverflowStrategy[B] = OverflowStrategy.Default): Observable[B]
```

It's easy to change the implementation, although some tests might need to be fixed.

TIP: besides the signature in `Observable.scala`, the implementation that needs to change is in `monix.reactive.internal.operators.MapParallelUnorderedObservable` 😉

**Comment by Wogan** [comment]
Whoops sorry for the spam! Opened a PR.
