### ISSUE TITLE
2.3.1 release not published on Maven Central

### ISSUE THREAD

**Issue by nktpro** [monix/monix#446]
2.3.1 release is currently [missing on Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.monix%22%20AND%20a%3A%22monix_2.12%22)

**Comment by alexandru** [comment]
@nktpro something bad must have happened with the release process.

Please use `2.3.0` in the meantime.

**Comment by nktpro** [comment]
2.3.2 is now available, closing
