### ISSUE TITLE
Add scanMap and scanM combinators to Observable

### ISSUE THREAD

**Issue by LukaJCB** [monix/monix#449]
I.e. something like:

```scala
def scanM[M[_]: Monad, B](seed: B)(accumulator: (B, A) ⇒ M[B]): Observable[M[B]]

def scanMap[B: Monoid](f: A => B): Observable[B]
```

**Comment by alexandru** [comment]
@LukaJCB where have you seen `scanM`?

**Comment by LukaJCB** [comment]
I haven't really seen it anywhere tbh, but it's analogous to `foldM` and you can make it stack safe with `tailRecM`. :)

**Comment by alexandru** [comment]
Wait, so how can you make it stack safe with `tailRecM`?

```scala
val oldState: M[B] = ???
val elem: A = ???

val newState = ???
```

So I don't get it, how can you build a `newState` given an `oldState` without touching `flatMap`?

**Comment by LukaJCB** [comment]
I'm definitely not an expert and I'm not sure if it works for `scan` as it does for `fold`, but here's some discussion on the issue: https://github.com/typelevel/cats/issues/1030

**Comment by LukaJCB** [comment]
I think I was wrong with my comment above, I don't think you can make it stack-safe unless your `Monad` is already stack-safe for left-associated binds.

**Comment by LukaJCB** [comment]
Also here's my implementation if it helps :)
```scala
def scanMap[B: Monoid](f: A => B): Observable[B] =
    scan(Monoid[B].empty)((b, a) => Monoid[B].combine(b, f(a)))

def scanM[M[_]: Monad, B](seed: B)(accumulator: (B, A) ⇒ M[B]): Observable[M[B]] =
    scan(Monad[M].pure(seed)) { (mr, t) =>
      Monad[M].flatMap(mr)(r => accumulator(r, t))
    }
```

**Comment by alexandru** [comment]
@Avasil can you also do `scanMap` for `Observable`?

**Comment by Avasil** [comment]
@alexandru sure :)

**Comment by alexandru** [comment]
This is actually solved for `scanMap` and `scanM` is unfortunately problematic. Closing.
