### ISSUE TITLE
Observables evaluating multiple times

### ISSUE THREAD

**Issue by massung** [monix/monix#453]
Not sure if this is "as-designed" or a bug. Putting the following into [Scastie](https://scastie.scala-lang.org/VnDQAqxvQwCnJqE0G29wHA):

```scala
import monix.execution.Scheduler.Implicits.global
import monix.reactive.subjects._

val numbers = BehaviorSubject[List[Int]](List.empty)

val tens = numbers map {
  xs => println("here"); xs map (_ * 10)
}

val hundreds = tens map {
  xs => xs map (_ * 10)
}

val thousands = tens map {
  xs => xs map (_ * 100)
}

hundreds foreach (println _)
thousands foreach (println _)

numbers onNext List(1, 2, 3)
numbers onNext List(4, 5, 6)
```

This ends up outputting:

```
here
List()
here
List()
here
List(100, 200, 300)
here
List(1000, 2000, 3000)
here
List(400, 500, 600)
here
List(4000, 5000, 6000)
```

What I would expect to be output is this:

```
here
List()
List()
here
List(100, 200, 300)
List(1000, 2000, 3000)
here
List(400, 500, 600)
List(4000, 5000, 6000)
```

My expectation (perhaps incorrectly?) is that each `onNext` to `numbers` would result in `tens` being updated (printing "here"), but then `hundreds` and `thousands` would just be chained off of `tens`, which has already updated and has no need to be executed yet-again.

I have not tested this under 3.0 to know if the behavior is the same.

Is this correct behavior? If it is, can the [documentation page](https://monix.io/docs/2x/reactive/observable.html) be updated to reflect this and explain why?

**Comment by massung** [comment]
After finding [this nodejs article on cold vs. hot observables](https://medium.com/@benlesh/hot-vs-cold-observables-f8094ed53339) I think I understand what's going on. If I change `tens` to be a "hot" observable (perhaps like so)...

```scala
val tens = numbers.map({xs => println("here"); xs map (_ * 10)}).publish
```

Then "here" should only be output once since there's a multicast subject between the "here" observable and the downstream observables. 

I'm closing this assuming the above is correct.

**Comment by alexandru** [comment]
@massung that is correct, observables are by default "cold", meaning that each new `.subscribe` will open a new connection.

If you want sharing, you can transform any cold observable into a "hot" one with `.publish`.
Also checkout:

- `.multicast`: the more capable variant
- `.publishSelector`: the safer variant, since "hot" observables means you end up dealing with shared mutable state and we want FP in our lives :-)
