### ISSUE TITLE
Exception when calling Task.fromIO

### ISSUE THREAD

**Issue by travisblakeney** [monix/monix#454]
We are currently experiencing an issue when converting a cats IO to a monix Task. If the IO fails it results in an exception being thrown rather than handled even when using attempt on the IO. 

The following produces the exception:

```

  val t = Task.fromIO(IO {
    throw new RuntimeException("BOOM")
  }.attempt.map(_ => ()))

  Await.result(t.runAsync, 150.seconds)

```

The version of monix-eval is 3.0.0-M1

**Comment by alexandru** [comment]
Thanks @travisblakeney for the report, will investigate.

**Comment by oleg-py** [comment]
It seems there has been a bug in `cats-effect`:

```scala
import cats.effect.IO
// returns Left(NotImplementedError)
IO { ??? }.to[IO].attempt.unsafeRunSync
// throws
IO { ??? }.attempt.to[IO].unsafeRunSync
```

3.0.0-M1 depends on cats-effect 0.4, which has this bug. Current version depends on 0.8, which does not have this bug, and the code in OP's post does not produce an exception anymore.

**Comment by alexandru** [comment]
Thanks @oleg-py for investigating it. Will close this for now.
