### ISSUE TITLE
Add a Parallel for Observable for using combineLatest

### ISSUE THREAD

**Issue by LukaJCB** [monix/monix#459]
`combineLatestMap` is a super useful combinator! Using it with more than a couple of combinators can be quite cumbersome though, so something like a `Parallel` would be a super useful thing IMO.
Here's some code I wrote:

```scala
class CombineObservable[A](val value: Observable[A]) extends AnyVal
object CombineObservable {
  implicit def combineObservableApplicative: Applicative[CombineObservable] = new Applicative[CombineObservable] {
    def pure[A](x: A): CombineObservable[A] = new CombineObservable(Observable.now(x))

    def ap[A, B](ff: CombineObservable[(A) => B])(fa: CombineObservable[A]) = new CombineObservable(
      ff.value.combineLatestWith(fa.value)((f, a) => f(a))
    )

    override def map[A, B](fa: CombineObservable[A])(f: A => B): CombineObservable[B] =
      new CombineObservable(fa.value.map(f))

    override def product[A, B](fa: CombineObservable[A], fb: CombineObservable[B]): CombineObservable[(A, B)] =
      new CombineObservable(fa.value.combineLatest(fb.value))
  }
}
```

And then inside `object Observable`:
```scala
implicit def observableParallel: Parallel[Observable, CombineObservable] = new Parallel[Observable, CombineObservable] {
  def monad = observableMonad
  def applicative = CombineObservable.combineObservableApplicative
  def sequential = new (CombineObservable ~> Observable) {
    def apply[A](fa: CombineObservable[A]) = fa.value
  }
  def parallel = new (Observable ~> CombineObservable) {
    def apply[A](fa: Observable[A]) = new CombineObservable(fa)
  }
}
``` 

I've checked the laws for my `rxjs` wrapper and they worked fine! However if we find it's not a valid `Applicative`, but only a valid `Apply` we could still make a `NonEmptyParallel` which would still allow us most of the benefits (i.e. `parMapN` syntax)

**Comment by alexandru** [comment]
👍 very interesting!

Btw, what would be the win for the `CombineObservable` wrapper here?

**Comment by LukaJCB** [comment]
There's no real win apart from the fact that it means that one type only gets one instance of `Applicative`. One could do the same thing with a type tag or something like that or just not expose the second `Applicative` instance. All these options seem to valid, imo. 
I just personally like the consistency of defining a newtype. :)
