### ISSUE TITLE
monix.execution.misc.AsyncSemaphoreSuite consistently failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [monix/monix#465]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2165/consoleFull

there was a green run as recently as Nov 10 (https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2159/), so this must be due to a very recent change

**Comment by alexandru** [comment]
Thanks @SethTisue for the report. 

The error that I'm seeing happened, but should have been fixed on `master`.
From where is the community build pulling?

**Comment by SethTisue** [comment]
oh, we're frozen at 18f91fdf5 since I haven't pushed the cats 1.0.0-RCx upgrade through the community build yet

when I'll push that through, I'm not sure, so for now I'll disable your test suite in the community build, but I'll include a note to re-enable it at the time we unfreeze

**Comment by alexandru** [comment]
@SethTisue this error happens because I upgraded Minitest's API and it breaks compatibility with the commit that you mentioned.

So another way to fix the error is to also freeze Minitest at https://github.com/monix/minitest/tree/v1.1.0

**Comment by SethTisue** [comment]
ah, interesting, okay, I'll think about it at the time I push the cats upgrade though
