### ISSUE TITLE
Increase test coverage over 90%

### ISSUE THREAD

**Issue by alexandru** [monix/monix#466]
At the moment of writing the test coverage is at 88%.

**Comment by Avasil** [comment]
I will be happy to help a bit during weekend

It seems like the biggest offender is reactive subproject ( 761 lines missed at the time of writing )

**Comment by alexandru** [comment]
👍 @Avasil, glad to hear it!

Look for the low hanging fruits first — some of the lines are non-deterministic (e.g. in `compareAndSet` loops), we should just turn off coverage for those lines (possible with a comment) and you should avoid those for now.

**Comment by Avasil** [comment]
@alexandru 
How would you suggest to measure test coverage locally?

**Comment by alexandru** [comment]
@Avasil with the `sbt-scoverage` plugin, which is already in Monix's config.

```
sbt

project evalJVM
coverage
test
coverageReport
```

**Comment by Avasil** [comment]
@alexandru As an update on this issue, unfortunately I've been very busy lately and it might last a while before I do any meaningful progress but it will happen eventually :)

Also I have some problem with sbt coverage, both on Windows 10 and Ubuntu 14.04, trying different sbt versions (1.0, 0.13.16) and googling didn't help so far, maybe you encountered something similiar:
```
[IJ]> project evalJVM
[info] Set current project to monix-eval (in build file:/E:/Documents/Idea%20Projects/monix/)
[IJ]> coverage
[error] Not a valid command: coverage
[error] Not a valid project ID: coverage (similar: coreJS, coreJVM)
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: coverage (similar: homepage, package, compilerCache)
[error] coverage
[error]   
```

If I don't solve it I guess I'll just do some workaround and in worst case commit a lot to PR :P

**Comment by alexandru** [comment]
That is because the `sbt-scoverage` plugin is dirty, not necessarily supporting new Scala versions in time and attaching itself to the generated POM on deployment and thus disabled by default as a hack.

You need an `SBT_PROFILE=coverage` environment variable. So run `sbt` like this:

```
SBT_PROFILE=coverage sbt
```
