### ISSUE TITLE
Observable with diamond data flow graph

### ISSUE THREAD

**Issue by fdietze** [monix/monix#467]
I want to model this dataflow graph without *frp glitches* or too many updates:
```
c --> b --> d
      ^     ^
     /     /
    a------
```

In this case `d` should **always** emit values representing `(a,(a,c))`.

[scala.rx](https://github.com/lihaoyi/scala.rx#basic-usage) handles this well:

```scala
@ import $ivy.`com.lihaoyi::scalarx:0.3.2`, rx._
@ val (a,c) = (Var(0), Var(0))
     val b = Rx{ (a(), c()) }
     val d = Rx{ (a(), b()) }
     d.foreach(println) 
(0,(0,0))

@ a() = 1 
(1,(1,0)) // good, since consistent: (a,(a,c))

@ c() = 5 
(1,(1,5)) // good
```

But I have trouble modeling this with monix (and ReactiveX in general). I'm always getting intermediate updates:

```scala
@ import $ivy.`io.monix::monix:2.3.0`, monix.execution.Scheduler.Implicits.global, monix.reactive._, subjects.BehaviorSubject 
import $ivy.$                      , monix.execution.Scheduler.Implicits.global, monix.reactive._, subjects.BehaviorSubject

@ val a = BehaviorSubject[Int](0) 
a: BehaviorSubject[Int] = monix.reactive.subjects.BehaviorSubject@4168f3d9

@ val c = BehaviorSubject[Int](0) 
c: BehaviorSubject[Int] = monix.reactive.subjects.BehaviorSubject@5d8fd077

@ val b = a.combineLatest(c) 
b: Observable[(Int, Int)] = monix.reactive.internal.builders.CombineLatest2Observable@36ae17ef

@ val d = a.combineLatest(b) 
d: Observable[(Int, (Int, Int))] = monix.reactive.internal.builders.CombineLatest2Observable@42a698bd

@ d.foreach(println) 
(0,(0,0))
res8: monix.execution.CancelableFuture[Unit] = monix.execution.CancelableFuture$Implementation@16ad008f

@ a.onNext(1) 
(1,(0,0)) // bad, since this is inconsistent. It does not represent (a,(a,c))
(1,(1,0)) // good
res9: concurrent.Future[monix.execution.Ack] = Continue

@ c.onNext(5) 
(1,(1,5)) // good
res10: concurrent.Future[monix.execution.Ack] = Continue
```

 Any ideas on how to avoid these inconsistent itermediate updates?

**Comment by alexandru** [comment]
I understand the problem, but unfortunately I don't have any elegant ideas of how to solve it. As far as the `combineLatest` operator is concerned, it works as specified. 

Unfortunately what you see as `(a, (a, c))` in this model is actually `(a1, (a2, c))`, as `a1` and `a2` are different observations of `a` from different streams, or lets say moments in time. This is more honest in how communications work over the network, being the difference between consistent and _eventually consistent_.

One stupid solution would be something like this:

```scala
final case class Timed[A](a: A, time: Long = 0)
```

And then `A` can become:

```scala
val inA = BehaviorSubject[Int](0) 
val outA = in.scan(Timed(0)) { case (Timed(_, t), a) => Timed(a, t + 1) }
```

Each update of `A` increments a counter, so you just wait for the `(a, (a, c))` to achieve consistency:

```scala
val d = outA.combineLatest(b).collect {
  case (Timed(a1, t1), (Timed(a2, t2), c)) if t1 == t2 =>
    (a1, (a2, c))
}
```

It's stupid and ugly, I know, but you can't have easy consistency when speaking of messages delivered over the network or between threads that may be busy and in this model that's exactly what `Observable` is prepared for, so you have to cope somehow with an eventually consistent thing.

**Comment by fdietze** [comment]
You are right, the problem is a lot harder in an asynchronous setting which monix is designed for. I like your concept with the counter, though (if I understand it correctly) it only solves the simple case, which can also be solved via the `zip` operator:
```
      b --> d -->
      ^     ^
     /     /
--> a------

d = (a zip b)
```

In my original case, `d` should also be triggered if `b` was only triggered by `c`, while `a` stays the same.
```
-->c --> b --> d -->
         ^     ^
        /     /
   --> a------
```

I digged a bit into the scientific literature and found that glitches are a solved problem in a synchronous environment (using knowledge about the data-flow graph). For example scala.rx solves it [like this](https://github.com/lihaoyi/scala.rx/blob/master/scalarx/shared/src/main/scala/rx/Rx.scala#L115). But consistency and glitches are an open question in distributed reactive programming (https://scholar.google.com/scholar?q=reactive+programming+glitch). I guess this is a bit out of scope for monix...

What I wanted to say with my comment in the `Var` issue, is that people should be aware of glitches when using monix for nontrivial state management. Like in reactive user-interfaces and web-frontends. Maybe a hint in the documentation is enough?

**Comment by alexandru** [comment]
You're right, it should be mentioned in the docs.

Leaving this open until it is.
