### ISSUE TITLE
Task#onErrorRestartIf(Throwable=>Boolean) does not have maxRetries parameter

### ISSUE THREAD

**Issue by johnw** [monix/monix#472]
The scaladoc for Task#onErrorRestart(Throwable => Boolean) suggests that it should have a maxRetries parameter to prevent never-ending restarts, but no such parameter exists.  It seems like it would be a useful addition.  (Alternately, scaladocs should probably be corrected to not mention the parameter.)

**Comment by Avasil** [comment]
In docs there is:
``` scala
def retryBackoff[A](source: Task[A],
  maxRetries: Int, firstDelay: FiniteDuration): Task[A] = {

  source.onErrorHandleWith {
    case ex: Exception =>
      if (maxRetries > 0)
        // Recursive call, it's OK as Monix is stack-safe
        retryBackoff(source, maxRetries-1, firstDelay*2)
          .delayExecution(firstDelay)
      else
        Task.raiseError(ex)
  }
}
```
I've used in every project so far, I wish it was included in library (maybe with backoff as argument)

**Comment by alexandru** [comment]
You are right @johnw, the ScalaDoc is incorrect, will fix.

**Comment by alexandru** [comment]
Guys, see https://github.com/monix/monix/pull/507
