### ISSUE TITLE
Add a .bracket operation for Task / Coeval

### ISSUE THREAD

**Issue by alexandru** [monix/monix#478]
This needs to be coordinated with the developments in `cats-effect`.

**Comment by Avasil** [comment]
Hi, can you give some pointers about this issue when you get back?
```
def bracket(fa: F[A])(use: A => Stream[F, B], release: A => F[Unit]): Stream[F, B]
```

```
def bracket[A, B](use: A => Task[B], release: A => Task[Unit]): Task[B]
```
Is the signature supposed to be like this? And what coordination in ```cats-effect``` is needed?

**Comment by alexandru** [comment]
@Avasil we need a corresponding type class in `cats-effect` that exposes it.

For `Task` and `Coeval` I am thinking of ...

```scala
abstract class Task[A] {
  // ...
  def bracket[A, B](use: A => Task[B], release: A => Task[Unit]): Task[B]
}
```

The resulting `Task` must not be cancelable, must behave as an atomic unit and we need to do something similar or piggyback on the new `.uncancelable` op.

**Comment by alexandru** [comment]
Btw, on `cats-effect` the current discussion is at — https://github.com/typelevel/cats-effect/issues/88

**Comment by alexandru** [comment]
We already have `bracket` on `Task` and `Coeval`. What needs to happen next is for us to implement the upcoming `Bracket` type class, from cats-effect `1.0.0-RC`. So closing this for now.
