### ISSUE TITLE
Add a .bracket operation for Iterant

### ISSUE THREAD

**Issue by alexandru** [monix/monix#479]
FS2 has something like this:

```scala
def bracket(fa: F[A])(use: A => Stream[F, B], release: A => F[Unit]): Stream[F, B]
```

**Comment by oleg-py** [comment]
The bracket discussed currently in `cats-effect` is the alternative of `try ... finally`, ensuring cleanup after `use` completes or throws. On the other hand,`fs2` bracket keeps resources open and closes them upon the completion of the stream, so things like:

```scala
def getFile = bracket(openFile)(file => Iterant[Coeval].of(file))(file => Coeval(file.close()))
def totallyOk = getFile.mapEval(f => Coeval(f.readFirstLine()))
```

are possible (and useful).

Maybe something like this would suffice as the implementation of the latter:

```scala
Iterant.liftF(fa)
  .flatMap(a => Iterant.suspend(use(a)).doOnComplete(_ => F.suspend(release(a)))
```

And maybe it should go under a different name?

**Comment by alexandru** [comment]
@oleg-py hey, I've seen you interested in effects and stuff 😀

Would you mind giving this issue a try?

A `bracket` operation for `Iterant` would be very useful. We just need to make sure that we get the signature right.

The discussion at https://github.com/typelevel/cats-effect/pull/113 is probably relevant. What I'm thinking of is that we need to distinguish between normal termination (with error or not) and cancellation, in `Iterant`'s case this being an "early stop".
