### ISSUE TITLE
value withFilter is not a member of monix.eval.Task

### ISSUE THREAD

**Issue by vilinski** [monix/monix#480]
I have some task functions, want to run them parallel and give their results to the next task.
But experiencint the subject error:

> `value withFilter is not a member of monix.eval.Task[(String,String)]`
> `(a,b) <- Task.zip2(fetchA(), fetchB()`

Do I something wrong with follwing code?:

```scala

import monix.eval.Task
import monix.execution.Scheduler.Implicits.global

object FetchABC {
  def fetchA() = Task { "A" }
  def fetchB() = Task { "B" }
  def combineAB(a: String, b: String) = Task { a + b }

  def runThemAll(): Task[String] = {
   // works but too slow, because B waits for A first
    val cWorks =
      for {
      a <- fetchA()
      b <- fetchB()
      c <- combineAB(a,b)
    } yield c

   // can't compile
    val cError =
      for {
        (a,b) <- Task.zip2(fetchA(), fetchB())
        c <- combineAB(a,b)
      } yield c
  }
}
```

monix: 2.3.2
scala: 2.12.4
sbt: 1.0.4

**Comment by Avasil** [comment]
It is pretty known problem with for comprehensions in general, you could cheat it like this:
```scala
val cError =
  for {
    result <- Task.zip2(fetchA(), fetchB())
    (a, b) = result
    c <- combineAB(a, b)
  } yield c
```
or just write:
``` scala
fetchA()
  .zip(fetchB())
  .flatMap { case (a, b) => combineAB(a, b) }
```

If you are curious about the problem, [check this link](https://github.com/scalaz/scalaz/pull/728#issuecomment-45777181)

**Comment by vilinski** [comment]
Thanks. Didn't know that. Scala has so many ugly quirks to competing with js ...

**Comment by alexandru** [comment]
I'm still thinking on providing or not providing a `withFilter`.

Having such a method that can result in an error at runtime doesn't seem right to me, especially given that you can always do the syntactic trick that @Avasil did above.

So I'm going to err on safety for now and close the ticket.
