### ISSUE TITLE
Upgrade to cats 1.0.0-RC2 and cats-effect 0.6

### ISSUE THREAD

**Issue by lorandszakacs** [monix/monix#484]
Well, everything is in the header really.

Hopefully by doing this the switch to 1.0.0 will be easier.

**Comment by LukaJCB** [comment]
To clarify, 1.0.0 will have zero source code changes over RC2, only tests and documentation are affected :)

**Comment by alexandru** [comment]
Hey, latest `3.0.0-M3` depends on Cats 1.0.1 and cats-effect 0.8. I'm closing this.

Sorry for the latency, I've been on my winter holiday.

Cheers,
