### ISSUE TITLE
Iterant.liftF (F[A] => Iterant[F, A]) builder

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#487]
I've been doing a port from `fs2.Stream` to `monix.Iterant` on one of my personal projects. One of usage patterns I encountered was including effectful values (that are not streams) in the middle of `for`-comprehension:
```scala
for {
  a <- /* streaming operation */
  b <- Stream.eval(/* non-streaming operation dep. on a */)
  c <- /* another streaming operation */
  _ <- Stream.eval(/* another non-streaming operation of b and c */)
} yield c
```
Where `Stream.eval` has the following type signature:

```scala
def eval[F[_],O](fo: F[O]): Stream[F,O] = ???
```

I propose to add such builder to `Iterant`. Proposing name `liftF` based on cats naming for monad transformers' method that does similar thing (see typelevel/cats#2033).

If you don't mind, I'd take a run at making PR for this.

**Comment by alexandru** [comment]
@oleg-py sorry for not replying, I've been away on vacation in my winter break. Feel free to do the PR.

What you want can be expressed with something like this:
```scala
Iterant.suspend(fa.map(Iterant.now))
```

We already have `eval` with a different signature. So `liftF` sounds good.

**Comment by alexandru** [comment]
Assigning it the `3.0.0` milestone, should be an easy fix.
