### ISSUE TITLE
Add Iterant.dropWhileWithIndex

### ISSUE THREAD

**Issue by alexandru** [monix/monix#496]
Similar with the `Observable` equivalent, drops the longest prefix of elements that satisfy the given predicate:

```scala
sealed abstract class Iterant[F[_], A] {
  // ...
  def dropWhileWithIndex(p: (A, Int) => Boolean)(implicit F: Sync[F]): Iterant[F, A]
}
```

For inspiration see the implementation of [DropByPredicateWithIndexOperator](https://github.com/monix/monix/blob/v3.0.0-M3/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/DropByPredicateWithIndexOperator.scala), which is for `Observable`.

**Comment by Avasil** [comment]
I can take this one unless someone is already working on it

**Comment by alexandru** [comment]
@Avasil go for it.
