### ISSUE TITLE
Add Iterant.takeWhileWithIndex

### ISSUE THREAD

**Issue by alexandru** [monix/monix#497]
Similar with [issue #496](https://github.com/monix/monix/issues/496) we need a `takeWhileWithIndex` on `Iterant` that takes elements for as long as the given predicate returns `true`:

```scala
sealed abstract class Iterant[F[_], A] {
  // ...
  def takeWhileWithIndex(p: (A, Int) => Boolean)(implicit F: Sync[F]): Iterant[F, A]
}
```

The implementation should be very similar actually.

**Comment by greenhat** [comment]
I'd like to take this one.

**Comment by alexandru** [comment]
@greenhat sure, go for it
