### ISSUE TITLE
Update monix.io for version 3.0.0

### ISSUE THREAD

**Issue by alexandru** [monix/monix#505]
The monix.io project is already set to support multiple versions, which is cool, as we can redirect users to the relevant version.

However the 2.x pages should contain a warning that they don't talk about the latest version, to warn users landing from Google.

**Comment by xingyif** [comment]
Isn't this issue already fixed? https://monix.io/docs/2x/
![screen shot 2018-06-24 at 15 44 21](https://user-images.githubusercontent.com/15064985/41822952-9308ed7c-77c5-11e8-93a1-66d5ca1cfaac.png)

**Comment by Avasil** [comment]
Good catch @xingyif, thanks!
