### ISSUE TITLE
Introduce @deprecated symbols, document API breakage for 3.0

### ISSUE THREAD

**Issue by alexandru** [monix/monix#506]
@deprecated symbols were removed initially, along with the Mima setup that was checking against 2.3.x because it was too annoying for development.

But wherever possible, source compatibility should be preserved.

Also, document everything that was deprecated or removed in a monix.io article to help people migrate.

**Comment by Avasil** [comment]
@alexandru How do we go about it? If I understand correctly, we didn't keep all methods (like `Observable.mapAsync`) so we should reintroduce them but with @deprecated symbol so it's not like they just disappeared?

Any idea how to reliably get the list of everything?

Also it would be cool to have scalafix for 3.0 release, there were maaaany changes in `Task` API

**Comment by alexandru** [comment]
> Any idea how to reliably get the list of everything?

We can use Mima reports to help us.

**Comment by alexandru** [comment]
No longer interested in doing this. 

It's nice to bring back some deprecated symbols, but I'd rather work on documentation at this point.
