### ISSUE TITLE
Setup automatic code formatting in SBT

### ISSUE THREAD

**Issue by alexandru** [monix/monix#513]
Style is difficult to maintain and a burden in code reviews.

I long maintained that formatting should be done by the developers themselves, due to available tools not understanding context well. But for public projects that receive contributions this does not scale.

My preference would be for [scalafmt](http://scalameta.org/scalafmt/), but it remains to be seen if it can be configured well.

Settings need to be adjusted to match the current style as much as possible.
Some quick rules, probably more to come as the need arises:

1. Automatic copyright header
2. ScalaDoc formatting should be disabled, being completely the responsibility of the developer
3. In general I don't like dangling things to the right and I hate what IntelliJ IDEA does by default with function and class constructor params
4. one line branches in `match` statements are OK, but the style needs to be consistent for all branches of an expression (`if/else`, `match`, etc), so either all branches are one lines, or all of them introduce newlines between condition and expression

## No. 1 — auto copyright header

Being careful about the copyright header is a burden I'd like to avoid.

## No. 2 — ScalaDoc

Monix uses carefully crafted indentation that does not match the formatting rules of IntellIJ IDEA and I'd like to avoid any fuckups of an automated plugin. 

ScalaDoc is documentation and documentation requires manual crafting.

## No. 3 — no dangling stuff to the right

For classes, this is OK:

```scala
case class Foo(
  number: Int,
  name: String)

case class Bar(
  number: Int,
  name: String
)
```

This is not OK:

```scala
case class Foo(number: Int,
               name: String)
```

For functions, this is OK:

```scala
def foo(number: Int,
  name: String): Result = {
  ???
}

def bar(
  number: Int,
  name: String): Result = {

  ???
}

// At call site
foo(
  number,
  name)
```

But this is not OK:

```scala
def foo(number: Int
        name: String): Result = {
  ???
}

// At call site
foo(number
    name)
```

So there's a strict policy against *dangling stuff to the right*.

## No. 4 — indentation of match / if

For `if/else`, this is OK:

```scala
if (condition) success
else failure

if (condition) success else {
  failure
}

if (condition)
  success
else
  failure
```

This is not OK:

```scala
if (condition) success
else {
  failure
}

if (condition) {
  success
} else failure
```

For `match`, this is OK:

```scala
// All branches are one lines
expr match {
  case Foo(_) => success
  case Bar(_) => failure
}

expr match {
  case Foo(_) => 
    success
  case Bar(_) => 
    failure
}

// OK for the first branches(s) to be one lines, 
// but only if the formatter can distinguish this from the other cases
expr match {
  case Foo(_) => success
  case Bar(_) =>
    failure
}
```

This is not OK:

```scala
// unaesthetic mixed style
expr match {
  case Foo(_) =>
    success
  case Bar(_) => failure
}
```

**Comment by Avasil** [comment]
@oleg-py 
Did you plan to work on it (asking because of #531) ? If not - I could take a look into this issue tomorrow

**Comment by lorandszakacs** [comment]
@Avasil, I just opened up a PR. Feel free to lift stuff from there and modify it to better suit the existing formatting.

https://github.com/monix/monix/pull/546

**Comment by Avasil** [comment]
@lorandszakacs cool! I'll have a closer look tomorrow :)

**Comment by alexandru** [comment]
We have formatting rules in place, but truth be told I don't want automatic code formatting.

IntelliJ IDEA knowing how to interpret those rules is good enough.
