### ISSUE TITLE
Observable.take(0) shouldn't subscribe to the source at all

### ISSUE THREAD

**Issue by alexandru** [monix/monix#541]
[January 17, 2018 11:37 PM](https://gitter.im/monix/monix?at=5a5fc21b5a9ebe4f759d4ba5):

```scala
var counter = 0
def inc() ={
  counter += 1
  1
}

val o = Observable.repeatEval( inc() ).take(0)
```

The fix should be that `take(0)` should simply return `Observable.empty`.

Fix should be back-ported to 2.3.x as well.

**Comment by alexandru** [comment]
@Avasil can you please do a back-port to 2.3.x as well?

Pull request to `series/2.3.x` branch.

**Comment by alexandru** [comment]
Planning a `2.3.3` release with bug fixes.

**Comment by Ben-Barron** [comment]
You recommendation on this page: https://monix.io/api/2.3/monix/reactive/observables/ObservableLike.html for handling groups produced by the `groupBy` operator which you are not interested in would not work given this change...right?
