### ISSUE TITLE
Add Iterant.fromStateAction / fromStateActionL

### ISSUE THREAD

**Issue by alexandru** [monix/monix#548]
`Observable` has them and so should `Iterant` 😀

```scala
object Iterant {

  def fromStateAction[F[_], S, A](f: S => (A, S))(seed: => S)
    (implicit F: Sync[F]): Iterant[F, A] 

  def fromStateActionL[F[_], S, A](f: S => F[(A, S)])(seed: F[S])
    (implicit F: Sync[F]): Iterant[F, A]
}
```

Note: the simple version, `fromStateAction`, should emit `NextBatch` items with the default `recommendedBatchSize`.

The `fromStateActionL` overload should emit `Next` items, because presumably the evaluation of `F[_]` is expensive and we can't delay it.

**Comment by Avasil** [comment]
I can do it but want to clarify: 
Should ```fromStateAction```emit items as ```NextBatch``` even in ```case Next```? And then ```fromStateActionL``` should be a bit like ```Iterant#scan```?

**Comment by oleg-py** [comment]
@Avasil this is for building new `Iterant`s, so there won't be anything to match on

**Comment by Avasil** [comment]
@oleg-py 
Oh, right, thanks for pointing this out :D
