### ISSUE TITLE
Iterant error handling is leaky

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#559]
Found those cases while I was looking for correct implementation for #554 

These throw:

```scala
Iterant[IO]
  .eval { throw new Exception }
  .onErrorIgnore.completeL.unsafeRunSync()

Iterant[IO].of(1)
  .mapEval(_ => IO { throw new Exception })
  .onErrorIgnore.completeL.unsafeRunSync()

Iterant[IO].liftF(IO { throw new Exception })
  .onErrorIgnore.completeL.unsafeRunSync()

Iterant[IO].of(1)
  .mapEval(_ => IO(???))
  .attempt.toListL.unsafeRunSync()
```

although these do not:
```scala
Iterant[IO].raiseError(new Exception)
  .onErrorIgnore.completeL.unsafeRunSync()

Iterant[IO].of(1).scanEval(IO[Int](???))((_, _) => ???)
  .onErrorIgnore.completeL.unsafeRunSync()
```

**Comment by alexandru** [comment]
Thanks for investigating.

We need a policy for dealing with errors triggered in the `F[_]` context.

My feeling right now is that the `L` operations, that are folding the iterant and returning `F[_]`, should be the ones in charge.

My only worry is that we'll suffer from performance issues, however I think we can come up with a trick to not do a `handleWith` on each `F[_]` boundary.

We could do a single `handleWith` only once, that wraps everything, the problem is that we need to know the current `earlyStop`, so I wonder if an implementation like the following would work:

```scala
private[tail] object IterantCompleteL {
  /**
    * For boxing stuff. We could close of a plain `var`, but Scala does this
    * under the hood as well (with `ObjectRef`) and I'd rather do this explicitly.
    */
  final class Box[A](var value: A)

  /**
    * Implementation for `Iterant#completeL`
    */
  final def apply[F[_], A](source: Iterant[F, A])
    (implicit F: Sync[F]): F[Unit] = {

    def loop(box: Box[F[Unit]], self: Iterant[F, A]): F[Unit] = {
      try self match {
        case Next(_, rest, stop) =>
          box.value = stop
          rest.flatMap(loop(box, _))
        case NextCursor(cursor, rest, stop) =>
          box.value = stop
          while (cursor.hasNext()) cursor.next()
          rest.flatMap(loop(box, _))
        case NextBatch(gen, rest, stop) =>
          box.value = stop
          val cursor = gen.cursor()
          while (cursor.hasNext()) cursor.next()
          rest.flatMap(loop(box, _))
        case Suspend(rest, stop) =>
          box.value = stop
          rest.flatMap(loop(box, _))
        case Last(_) =>
          box.value = null
          F.unit
        case Halt(None) =>
          box.value = null
          F.unit
        case Halt(Some(ex)) =>
          box.value = null
          F.raiseError(ex)
      } catch {
        case ex if NonFatal(ex) =>
          box.value = null
          source.earlyStop *> F.raiseError(ex)
      }
    }

    F.suspend {
      val box = new Box[F[Unit]](null)
      loop(box, source).handleErrorWith { e =>
        box.value match {
          case null => F.raiseError(e)
          case stop => stop *> F.raiseError(e)
        }
      }
    }
  }
}
```

**Comment by alexandru** [comment]
Or in other words, to avoid the `handleErrorWith` on each cycle, we use a freaking `var` to hold the latest `earlyStop` reference 🤪

**Comment by alexandru** [comment]
This might be difficult to do for every operator — left folds aren't a problem, but for example this won't work for `foldRight`, because the user is in charge of calling `earlyStop` for that one, but that's to be expected, that one is for big boys.

So what do you say?

**Comment by oleg-py** [comment]
To me it seems `attempt` and `onErrorIgnore` require changes too. I expect stream to continue emitting stuff on encountering an error after using one of those.

**Comment by alexandru** [comment]
Those are based on `Iterant.onErrorHandleWith`. I'm afraid to do the `var` trick on this one ☹️ can't reason about the implications right now.

**Comment by Avasil** [comment]
One interesting difference between handling ```Task``` and ```IO``` :
``` scala
\\ List(0)
Iterant[Task].now(1).mapEval[Int](_ => throw dummy).onErrorIgnore.toListL.runAsync
\\ throws
Iterant[IO].now(1).mapEval(_ => throw dummy).onErrorIgnore.toListL.unsafeRunSync()

\\ throws
Iterant[Task].now(1).mapEval[Int](_ => Task{throw dummy}).onErrorIgnore.toListL.runAsync

```
And now when i think about it - I remember having problem with ```Iterant.fromStateAction``` something along these lines:
``` scala
\\ was ok
Iterant.fromStateAction[Coeval, Int, Int](_ => (throw dummy, throw dummy))(0).toListL
\\ was throwing exception
Iterant.fromStateAction[Coeval, Int, Int](_ => (throw dummy, throw dummy))(0).attempt.toListL
```

I don't remember how I was testing it initially but my implementation was failing with ```attempt``` and passing with something else. I started working after some rewriting so I didn't investigate further. Not sure if this is related.

**Comment by alexandru** [comment]
So first of all the function `f` you give to`mapEval` is considered to be "*user code*" that is risky and just as `Observable` always protects against user provided functions, so does `Iterant`.

So `mapEval` protects against functions `f` that return an `F.raiseError` or that `throw`. It's not a typical function though and we can't use `mapEval` for exemplification in this case, unless `mapEval` itself is broken.

```scala
\\ List(0)
Iterant[Task].now(1).mapEval[Int](_ => throw dummy).onErrorIgnore.toListL.runAsync
\\ throws
Iterant[IO].now(1).mapEval(_ => throw dummy).onErrorIgnore.toListL.unsafeRunSync()
```

This is not true, the second one works on my machine, what version are you testing with? If it doesn't, then we have a bug in `mapEval`, but it should work fine with the current implementation.

**Comment by alexandru** [comment]
```
scala> Iterant[Task].now(1).mapEval[Int](_ => throw dummy).onErrorIgnore.toListL.runAsync.foreach(println)
List()

scala> Iterant[IO].now(1).mapEval(_ => throw dummy).onErrorIgnore.toListL.unsafeRunSync()
res4: List[Nothing] = List()
```

**Comment by Avasil** [comment]
@alexandru 
Sorry it wasn't related to ```IO``` and ```Task````, it turned out the difference was about ```Iterant.now``` and ```Iterant.of``` (I've noticed just after I commented but after you saw)

**Comment by alexandru** [comment]
Ah, it basically takes a different code path, will have to investigate, but it might be normal.

So two things:

1. all left folds (`L` method) need to handle errors; well as I said, we probably can't do that for  `foldRight`
2. `Iterant.onErrorHandleWith` needs to lift `F[_]` errors into the `Iterant` context

Question: does FS2 handle errors triggered in the `F[_]` context in their own `onErrorHandleWith` (whatever they call it) implementation?

**Comment by oleg-py** [comment]
@alexandru FS2 lets you handle the first error:
```scala
import cats.effect.IO

fs2.Stream(1, 2, 3).evalMap(_ => IO { ??? : Int })
  .attempt
  .compile
  .toList
  .unsafeRunSync() // List(Left(NotImplementedError))

fs2.Stream(1, 2, 3).evalMap(_ => IO { ??? : Int })
  .handleErrorWith(_ => fs2.Stream("Handled"))
  .compile
  .toList
  .unsafeRunSync() // List("Handled")
```
https://scastie.scala-lang.org/qhln5hWuTeCnYflGOuV3PQ

There seems to be no way to e.g. continue emitting while ignoring errors.

**Comment by alexandru** [comment]
@oleg-py that is to be expected though - I don't think continuing the streaming in `evalMap` makes sense. In general errors are terminal, unless it's explicit in the semantics of the operator that errors get ignored.

We could have like an `evalMapDelayErrors`, much like how we have `concatMapDelayErrors` in `Observable`. But that would be a different operator.

**Comment by oleg-py** [comment]
Yeah, now I realize it's not possible to continue from something like `Next(1, IO.raiseError(..), IO.unit)` anyway.

**Comment by Avasil** [comment]
@alexandru @oleg-py 
I think
```scala
final def skipSuspendL(implicit F: Sync[F]): F[Iterant[F, A]]
```
is left. Writing here so we don't forget about it if it needs the same treatment
