### ISSUE TITLE
Task.runSyncUnsafe does not complete when using global Scheduler

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#560]
Got this in REPL using global scheduler:
```scala
Task(2).runSyncUnsafe(10.seconds) // throws TimeoutException
```

I tried various other schedulers, it seems to work only with `trampoline` one:

```scala
Task(1).runSyncUnsafe(10.seconds)(Scheduler.trampoline(), null) // returns 1 very quickly
```

**Comment by alexandru** [comment]
@oleg-py there's something wrong with SBT repl itself, not allowing blocking its main thread for some reason.

Same thing happens with:

```scala
Await.result(Future(1), 10.seconds)
```

**Comment by alexandru** [comment]
I assume that the second sample runs because the result is already available upon evaluation so the implementation doesn't block because it doesn't have to.

**Comment by oleg-py** [comment]
@alexandru you are right. I just found [SI-9076](https://issues.scala-lang.org/browse/SI-9076) describing that problem. And like mentioned here, it works if I break task into two lines:
```
scala> val t = Task(1)
t: monix.eval.Task[Int] = Task.FlatMap$782057867
scala> t.runSyncUnsafe(1.second)
res1: Int = 1
```
Sorry for bothering.

**Comment by alexandru** [comment]
NP, it's weird, caught me by surprise as well.
