### ISSUE TITLE
Update monix.io documentation for 3.0

### ISSUE THREAD

**Issue by alexandru** [monix/monix#564]
....

**Comment by Avasil** [comment]
I think we're approaching time when we should start thinking about this. :)
Current API documentation is fantastic but I feel like `monix.io` docs are very important for new users.  I know it was a big factor to try this library in my case.

It could be a good opportunity to finish [Observable](https://monix.io/docs/2x/reactive/observable.html) documentation, update `Task` about new features (like `TaskLocal` and `bracket`) and of course write section about `Iterant`. Showing integration with `cats-effect` might be a good idea too!

I know API might still change but I feel like it's better to change some things if needed than wait for the last possible moment.

My idea is that we could design a draft for everything we want to write about. Think listing desired content and then gradually filling it with examples and explanation. I don't have any experience with it and I don't know how did you approach writing existing documentation but I think that writing everything at once might not be very likely.

How do you see it? Of course I volunteer to help out :D

**Comment by alexandru** [comment]
Thanks @Avasil for volunteering. The first hurdle is the setup and I started re-configuring the website to compile for two versions instead of one.

**Comment by Avasil** [comment]
@alexandru I'm about to write something, I don't have too much spare time lately so it might be slow but that's better than nothing. :D

I could start with `Observable` which is probably the most urgent, covering things from ReactiveX and Akka Streams.

Next thing - I was thinking that more reference applications could help. Either in separate `monix-examples` repo or `examples` subproject. Could be even accompanied by blog post or something to get more attention and explanation. That's not very urgent but I feel like that's a cool thing to do and I'd be happy to work on it but I need to gather ideas first so any feedback is welcome.

**Comment by alexandru** [comment]
@Avasil thanks,

Note that we have a new branch on the `monix.io` repository where I'm gradually updating the docs for 3.x: https://github.com/monix/monix.io/tree/series/3.x

For writing stuff on `Observable`, clone that and start writing in `_tut/3x/reactive/`.
That branch now has a README with how the website can be built.

**Comment by anjuna** [comment]
Is there any update on this?

I am finding it very hard getting my head around this library. The examples in the Observer docs feel esoteric and there is nothing in the Observable section.

**Comment by Avasil** [comment]
@anjuna 
It is in progress but not released yet.
There is `Observable` PR here: https://github.com/monix/monix.io/pull/34
You can [view its content](https://github.com/monix/monix.io/blob/038de49219af7db7beeeea53e8c6c3963304b7ef/_tut/docs/3x/reactive/observable.md)

I hope it will be helpful. If explanations there are not clear please make a comment on the PR - I'd really appreciate it!

Also, good place to ask questions is gitter:
https://gitter.im/monix/monix

**Comment by anjuna** [comment]
Thanks for the quick response! I'll certainly check that out.

Also thanks for all the effort gone into library, and all the comments in the code itself. I'm just such a newbie to reactive programming it was always going to be hard...

Are there some good books/other resources you can recommend to help me get my head around it?

**Comment by Avasil** [comment]
@anjuna 
Tbh you don't have to think too much about `Observers` or `Subscribers` in the beginning. Learn how to use `Task` (it's much better documented) and use `Observable` methods and then convert it to `Task` ( I have a section about it in the linked PR)

I don't have anything about streaming in general other than few talks:

https://monix.io/presentations/

https://www.youtube.com/watch?v=brnq6RsVeN4 (note this is for Monix 2.3.x so there will be some changes in 3.0 but it should give you an idea how to use it)

https://www.youtube.com/watch?v=81I_nzjUYy4 (this one uses fs2 but it's a great talk and you can do the same things with Monix)

You might also check out rx java documentation, there will be similarities to Monix `Observable`.

And I can recommend two books which might be helpful in general:

https://www.manning.com/books/functional-and-reactive-domain-modeling

https://www.manning.com/books/reactive-design-patterns

There are 50% discounts very often, check their deals of the day

**Comment by alexandru** [comment]
This ticket is too generic. The website is now compiled against 3.0.0-RC2. It's incomplete, but if issues are needed, we'll create more specific ones, otherwise I'm considering this to be solved.
