### ISSUE TITLE
Discussion on finalizers and ++

### ISSUE THREAD

**Issue by alexandru** [monix/monix#586]
I just encountered this very interesting issue on FS2's issue tracker: https://github.com/functional-streams-for-scala/fs2/issues/333

Code sample:

```scala
  property("associativity of append with finalizers") = secure {
    @volatile
    var finalized = false

    val p = emit(()) ++ (emit(()) onComplete eval_(Task delay { finalized = true }))
    // val p = (emit(()) ++ emit(())) onComplete eval_(Task delay { finalized = true })

    p.kill.run.run
    finalized
  }
```

Daniel is saying that the two lines above have different results and they shouldn't. Which is very interesting, because our "onComplete" (via our new `bracket` for example) refers to the stream on which it is applied, not to what came before it. 

We also don't have a `kill` operation currently, but I guess that's not very different from `take(0)` or something like that.

So the thing I don't understand about this issue is why should those two lines produce equivalent effects and why would anybody expect that? After all, the `onComplete` might cleanup resources that are only relevant once you evaluate the second stream.

And we could make `++` chain the first `earlyStop` value of the second stream to the first one, but why should we do that?

/cc @oleg-py

**Comment by oleg-py** [comment]
I think we're good.
* `onComplete` does not come with guarantee that it will ever be called (which should probably be noted in docs, if it isn't yet)
* `bracket` does not release resource that has not been acquired (and it's how it should be). For acquired resources, it guarantees (it should :) once and only once semantics

`bracket` is the thing to go for if you need to release some resource. I was not able to come up with any practical case where I would want `onComplete` instead. The latter is still useful for stuff like logging and debugging, but that's about it.

FWIW, current fs2 does the same thing as Iterant with its `onFinalize` (oh, and it doesn't have `kill` anymore):
```scala
import fs2._
import cats.effect.IO

val effect = IO(println("Effect!"))
val s = Stream(1, 1).onFinalize(effect)

(s ++ s).take(0).compile.drain.unsafeRunSync() // prints nothing
println("^ after take 0")
(s ++ s).take(1).compile.drain.unsafeRunSync() // prints Effect! once
println("^ after take 1")
(s ++ s).take(3).compile.drain.unsafeRunSync() // prints Effect! twice
println("^ after take 3")
```
[(scastie)](https://scastie.scala-lang.org/8Tg3tAyoTaecCXZfZzZ80g)

I also think that `iterA ++ iterB` should behave exactly as `Iterant.of(true, false).flatMap(if (_) iterA else iterB)` at least up to differences in internal representation. So if it is not practical to make `flatMap` call `earlyStop` of all results it would ever generate, it shouldn't be done for `++` either.

**Comment by alexandru** [comment]
@oleg-py thanks for investigating this.

**Comment by alexandru** [comment]
Closing this for now.
