### ISSUE TITLE
monix.tail.Iterant should have a cats.effect.Sync instance

### ISSUE THREAD

**Issue by alexandru** [monix/monix#599]
`cats-effect` [version 0.9](https://github.com/typelevel/cats-effect/releases/tag/v0.9) is released and @oleg-py's changes to `SyncLaws` is in (issue [#118](https://github.com/typelevel/cats-effect/issues/118)).

This means that we should be able to implement a `Sync` instance for `monix.tail.Iterant`. And it would be cool to do so because we get extra validations for free.

**Comment by alexandru** [comment]
@oleg-py I think you already worked on this? You interested?

**Comment by oleg-py** [comment]
@alexandru yup, will take a look shortly
