### ISSUE TITLE
Iterant.merge

### ISSUE THREAD

**Issue by alexandru** [monix/monix#616]
Just like `zipMap` and `parZipMap` on `Iterant`, which are making use of Applicative's `map2`, we also need a `merge` operation making use of `Concurrent#racePair`.

```scala
Iterant[Task].merge(stream1, stream2)
```

Behavior:

1. At each step this will create a race condition, via `racePair`, between `stream1` and `stream2`
2. The winner gets signaled immediately, with the loser's `Fiber` being used to create the next race condition, in `rest`

For anybody wanting to pick this up, note this is a difficult operator to implement.
Some special considerations for behavior:

1. the protocol allows for infinite `NextCursor` nodes, with the `recommendedBatchSize` mechanism provided for fairness — so we cannot simply serve a winning `NextCursor` / `NextBatch` node, nope, we have to split it according to the `recommendedBatchSize`  value, in order to give a chance to the other stream to also stream its own events
2. fairness is a concern; for example if we split a `NextCursor`, like mentioned at point 1, we probably need to `shift` (`Async.shift` or `Timer#shift`) the rest of it, to give a chance to the other stream to produce its results, because `racePair` is not doing that for us; or maybe we need to fork both just before `racePair`
3. we can't produce a `Fiber` on each race when the loser looses repeatedly — the first produced `Fiber` needs to be reused, otherwise we'll have a memory leak if the merged stream is `Iterant.suspend(Task.never)`, as we'll keep creating `Fiber` objects on `racePair`, linked to the previous `Fiber`, in an unending chain

Also an open question is what happens on early termination. We probably have to wait for the loser too.

Testing might also prove problematic, because the ordering of the merged events is going to be non-deterministic, as intended.

I'm not setting a deadline for it, as it is not critical. If it happens for 3.0.0, great.

**Comment by oleg-py** [comment]
@alexandru can we cancel the loser on early termination?

**Comment by alexandru** [comment]
We might be able to do it, but it gets tricky to do so.

When we have two streams, we'll end up at each step dealing with two early termination tokens, lets say `stopA` and `stopB`, just like happens with `zip`.

The problem is that, compared with `zip`, at any point in time we'll have either `stopA` or `stopB`, not both — because once you follow `rest`, the previous `stop` is not necessarily valid anymore and even if it is, it does not assume concurrency, so once you follow `rest` you have to wait for it in order to get a `stop`. 

So assuming that the second stream is the loser, cancelling it implies that cancelation does what `stopB` is doing, so we no longer need to worry about `stopB`.

That's not a reasonable assumption. I gave this sample in the documentation which is a totally legitimate usage of `Iterant`:

```scala
def readLines[F[_]](file: File)(implicit F: Sync[F]): Iterant[F, String] =
  Iterant[F].suspend {
    def loop(in: BufferedReader): F[Iterant[F, String]] =
      F.delay {
        // For resource cleanup
        val stop = F.delay(in.close())
        in.readLine() match {
          case null =>
            Iterant.suspendS(stop.map(_ => Iterant.empty), stop)
          case line =>
            Iterant.nextS(line, loop(in), stop)
        }
      }

    val in = F.delay {
      // Freaking Java
      new BufferedReader(
        new InputStreamReader(new FileInputStream("file"), 
        "utf-8"))
    }
    // Go, go, go
    in.flatMap(loop)
  }
```

Assuming this `F[_]` is either `Task` or `IO`, then on cancelation nothing will happen and the file handle will leak.

Note that we might be able to do something about it. For example we might prepare these `rest` references to:

1. build a new `F[_]` that wraps the `rest` we have, but that changes some `Boolean` on cancelation
2. then we `flatMap` the result, in which case we've got two possibilities:
  a. we notice the cancelation boolean and trigger `stopB`
  b. the `flatMap` never goes through, which means that our `F[_]` was already cancelable, hence we don't worry about it

It's a little complicated though. And we might want to solve this via a more generic approach. For example we might want to describe another operation on `Iterant` named `makeCancelable` (or smth), to make streams that aren't described with cancelable `F[_]` values to trigger "early stop" when they notice cancelation. Note that I was careful to not describe "early stop" as being cancelation in the vocabulary of `Iterant` because it isn't.

That's tricky too, not sure if `cats-effect` has what it takes to describe that generically, never tried it.

**Comment by alexandru** [comment]
What I'm trying to express is that it's easier to *not cancel* the loser in early termination. We just wait for it.

It's not ideal, but it would be a good first version. And if we'll be able to do cancelation of the loser, that's going to be a nice upgrade, but that can come later.

**Comment by alexandru** [comment]
As an addendum to the above 🙂 this is what I'm thinking of ...

```scala
var isCanceled = false

val next = rest.flatMap { x =>
  if (isCanceled) stop *> F.never
  else F.pure(x)
}

val cancelErr = new RuntimeException("canceled")
next.onCancelRaiseError(cancelErr).onErrorHandleWith {
  case `cancelErr` =>
    isCanceled = true
    F.never
  case err =>
    F.raiseError(err)
}
```

So on cancelation we set a boolean flag and if `rest` is not cancelable, then we'll notice it in its `flatMap` continuation (which should probably be preceded by an `attempt` 😔) and thus trigger early stop.

If `rest` is cancelable, then it becomes the user's responsability. Which is totally reasonable, because that piece of code above can be prepared to work for a `Concurrent[F]` that closes that file on cancelation.

**Comment by alexandru** [comment]
I must also mention that this problem is precisely why I campaigned (and introduced in `cats-effect`) a design in which, by default, cancelation of `flatMap`-loops is not automatic and all cancelation behavior has to be opt-in.

**Comment by alexandru** [comment]
Actually while showering 😀 I had an idea — and we need a `cancelable` operation, see: https://github.com/monix/monix/issues/630

**Comment by alexandru** [comment]
The advice given in this issue is no longer relevant.

In case we implement `Iterant.merge`, I'd rather start with a clean issue. Plus this won't happen for 3.0.0.
