### ISSUE TITLE
Iterant#mapBatch

### ISSUE THREAD

**Issue by alexandru** [monix/monix#617]
We need an operation like this:

```scala
sealed abstract class Iterant[F[_], A] {
  // ...
  def mapBatch[B](f: A => Batch[B]): Iterant[F, B] = ???
}
```

The yielded `Iterant` then be made of `NextBatch` nodes. This is useful for optimizing a data stream, for example for converting an `Iterant[F, Array[A]]` into an optimized `Iterant[F, A]`.

**Comment by Avasil** [comment]
I can implement it in the meantime, it has been a while. :D

**Comment by alexandru** [comment]
👍 go for it
