### ISSUE TITLE
What to do with Task#foreach ?

### ISSUE THREAD

**Issue by alexandru** [monix/monix#619]
`Task#foreach` triggers side effects and doesn't behave like `Future#foreach`, in that it doesn't log errors.

We need to decide what to do with it. Solutions:

1. we make it behave like `Future#foreach`, to report errors via `Scheduler#reportFailure`
2. we make it return a `Task` instead, but this helps with nothing imo
3. we deprecated it in 3.0.0-RC2 and then remove it in 3.0.0

Opinions?

**Comment by oleg-py** [comment]
**2.** is a no-go:
- There's already `Task#foreachL` that returns a `Task[Unit]`
- for-syntax might be silently broken:
```scala
for (a <- taskA; b <- taskB) println(a + b)

//desugars
taskA.foreach {a =>
  taskB.foreach(b => println(a + b)) // discarded value, so loop is no-op!
}
```

I think it's ok to deprecate it and leave for a while with a message to use `runAsync` or `runSyncUnsafe` instead. That means losing for-loop support, however.

---

Also, `foreach` is essentially implemented as `map { a => f(a); () }.runAsync`

So the issue you mention means that there is a more general bug: exceptions thrown inside `map` might not get reported. That has to be fixed.

**Comment by Avasil** [comment]
Unfortunately I don't have time now to play around with it too much but I agree with @oleg-py that the problem might be with `map`. Shouldn't it `reportFailure` somewhere?

**Comment by alexandru** [comment]
It should, but it doesn't and I got a confused user on Gitter complaining about it.

The current behavior is wrong, along with its signature.

Returning `CancelableFuture[Unit]` is also a bad idea for the same reason that @oleg-py mentioned above ... the result will not wait on an inner-for, this isn't a `flatMap` that we are describing, so returning a `Future` in here gives a false sense of what the thing does.

We need to get rid of it. 
And first we'll fix the implementation to report errors and `@deprecate` it for 3.0.0-RC.

**Comment by oleg-py** [comment]
I have problems reproducing the behavior. Seems like `map` is catching things, like expected.
