### ISSUE TITLE
Should ConcurrentEffect[Task] take implicit Task.Options?

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#625]
When using abstractions built on top of `ConcurrentEffect`, the user is no longer in charge of running the task. It makes it quite hard to configure both cancelability and local context propagation, requiring manual insertion of `executeWithOptions` in every possibly affected returned `Task`.

I think it makes sense if `ConcurrentEffect` required not only `Scheduler`, but also `Task.Options`.

For example, http4s now cancels running effect. It might be an option to not resume execution of task (by enabling `autoCancelableRunLoops`) if I have only DB transactions (which require `localContextPropagation`).

While I can build instance of `Effect[Task]` myself with all desired properties, a user might not be aware that he needs to, as it is not a compile-time error, but might lead to incorrect behavior at runtime, possibly even without even a runtime exception thrown.

/cc @leandrob13

**Comment by alexandru** [comment]
We probably need `Task.Options` in there, yes, but with a default value.

I'm not 100% sure though. It complicates the API.
Are you sure it eases your interaction with Http4s?

**Comment by oleg-py** [comment]
@alexandru the thing is:
* I am using `TaskApp` to start http4s server
* I am redefining `def options` to `Coeval(Task.Options(true, true))`
* When I make a request, http4s uses `Task.Options(false, false)` (the default) to run my Tasks

Issues:
1. Caught me completely by surprise. So it might be error-prone.
2. There is no easy way provide the `Effect` instance I need. I have to extend `CatsEffectForTask` (luckily it's not private) and override `runAsync`

**Comment by alexandru** [comment]
@oleg-py can you do a PR? It needs a default value though, set to `Task.defaultOptions`.

**Comment by oleg-py** [comment]
@alexandru Sure. But I don't see why it is a good idea to provide default value. It would still compile without any warning if you don't have an implicit instance available (which, when using `TaskApp`, you don't).

**Comment by alexandru** [comment]
Well, `Task.defaultOptions` is not implicit and I don't want people to be forced to provide their own `Options` for `Effect`, but I want to force people to provide their own `Options` when they do `runAsyncOpt`.

We probably need another change as well. Usage of `TaskLocal` is error prone without that option being enabled and I think we should enable it ourselves on `bind` for the resulting task.
