### ISSUE TITLE
Iterant#cancelable

### ISSUE THREAD

**Issue by alexandru** [monix/monix#630]
We need a `cancelable` operation, that transforms any `Iterant[F, A]` into one whose `F[_]` can be canceled.

See the discussion in #616.

We also need a `CancelStrategy` as an (implicit?) parameter:

1. `Deterministic` — that forces cancelation to call `stop` in a deterministic way
2. `Concurrent` — that assumes `stop` can be called concurrently

This should also introduce another `Iterant` state, lets call it `Iterant.Cancelable` to mark streams that are already cancelable, such that we don't do double work or override the user's carefully planned cancelation logic.

**Comment by Avasil** [comment]
What do you mean by another state - adding new type to ADT?

**Comment by alexandru** [comment]
Yes, but I'm not sure if it's a good idea, I'm still thinking about this issue.

**Comment by alexandru** [comment]
This issue is no longer relevant since switching to the new encoding. Closing.
