### ISSUE TITLE
Make Observable's ++ take a lazy (by-name) parameter

### ISSUE THREAD

**Issue by alexandru** [monix/monix#643]
Similar to #642, on `Observable` we've got the `++` operator currently defined like this:

```scala
abstract class Observable[+A] {
  //...
  def ++[B >: A](other: Observable[B]): Observable[B]
}
```

We need to change that parameter to be by-name (lazy):

```scala
def ++[B >: A](other: => Observable[B]): Observable[B]
```

**Comment by kubukoz** [comment]
@Avasil do you think there should be a strict alternative like in https://github.com/monix/monix/issues/642?

**Comment by alexandru** [comment]
@kubukoz there's already a strict alternative, it's called `Observable.concat`.

Issue #644 specifies that its implementation admits an optimization though, currently being based on `flatMap`, which is heavier than the current `++`.

**Comment by Avasil** [comment]
@kubukoz I think so, current implementations work with strict alternative so they should be changed to use strict `concat` if there is any that use `++`

@alexandru I think you misread the issue - it's about `Iterant`. :D

**Comment by kubukoz** [comment]
@Avasil 642 #642 is about Iterant :D

**Comment by Avasil** [comment]
@kubukoz @alexandru  Oh, sorry XD I was reading 642 but I think it is the same with both :D
