### ISSUE TITLE
Properly deal with InterruptedException on the JVM

### ISSUE THREAD

**Issue by alexandru** [monix/monix#645]
Copying the issue from https://github.com/typelevel/cats-effect/issues/181 because Monix suffers from the same issue.

We have our own [NonFatal](https://github.com/monix/monix/blob/master/monix-execution/shared/src/main/scala/monix/execution/misc/NonFatal.scala) implementation because the standard one also filters things like `ControlThrowable`, which is pretty dumb.

However this means we are no longer catching `InterruptedException`, which is a problem.

The problem is that on top of the JVM, when you catch an `InterruptedException`, you can't just swallow it like any other exception. This is a problem:

```scala
try {
  operation()
} catch {
  case ignored: InterruptedException => /* BIG PROBLEM! */
}
```

What needs to happen is that we need to "restore the interrupted status". This can be done like this:

```scala
try {
  operation()
} catch {
  case ignored: InterruptedException =>
    // Restores interrupted status
    Thread.currentThread().interrupt()
}
```

So we need a `NonFatal` specific to the JVM that, upon catching `InterruptedException`, it restores its interrupted status.

**Comment by kubukoz** [comment]
Can we check it with `Platform.isJVM`, or should we have two separate sources?

**Comment by Avasil** [comment]
@kubukoz
I'll admit I'm not yet too familiar with how Scala.JS converts code - I guess if  `VirtualMachineError` is ok then `InterruptedException` probably too but it would be good to check how it's resolved assuming all tests pass for Scala.JS

**Comment by kubukoz** [comment]
From what I see, `InterruptedException` is possible in JS world as well... then if it has to remain unhandled we'd need to have two separate sources for `NonFatal` js/jvm - @Avasil @alexandru does that make sense?
