### ISSUE TITLE
Operators for splitting Observable

### ISSUE THREAD

**Issue by Avasil** [monix/monix#648]
Currently we don't have any methods for splitting `Observable`. 

Is there any specific reason for that @alexandru ? We could add `Observable.span`,  `partition` and `unzip` equivalent to standard collection. It should be quite easy to express using existing operators but those are familiar from stdlib so I feel like they might have place in API. 

If you think that's good idea I can create issues for those and handle it during Scala Spree.

And what about `Iterant`?

**Comment by alexandru** [comment]
Splitting an `Observable` is not as easy as splitting a standard collection.

It's a given that if an observable gets split, the data source needs to be hot.

And that's a problem, because only cold observables are safe / referentialy transparent.

**Comment by alexandru** [comment]
For `Iterant` the only easy way to do it is to memoize the whole data source, also denying the user the possibility of stopping early 😉

**Comment by Avasil** [comment]
There is naive implementation like this:
```scala
// self = Iterant[F, (A, B)]
def unzip: (Iterant[F, A], Iterant[F, B]) = {
  val iter1 = self.map(_._1)
  val iter2 = self.map(_._2)

  (iter1, iter2)
}
```

Is this not safe?

**Comment by alexandru** [comment]
No, because the source gets evaluated twice and imo that’s not obvious.

**Comment by Avasil** [comment]
Oh, I understand, thanks for claryfing
