### ISSUE TITLE
Add Observable.bracket, similar with Iterant.bracket

### ISSUE THREAD

**Issue by alexandru** [monix/monix#649]
Currently `Iterant` has this function described in its companion object:

```scala
def bracket[F[_], A, B](acquire: F[A])(use: A => Iterant[F, B], release: A => F[Unit])
  (implicit F: Sync[F]): Iterant[F, B] = ???
```

So given a resource created by `acquire`, it feeds that into `use` to create an `Iterant` and then at the end executes `release` no matter what — i.e. even if the consumer stops the streaming early, or the stream ends in success or error.

We need to describe the same for `Observable`:

```scala
def bracketTask[A, B](acquire: Task[A])
  (use: A => Observable[B], release: A => Task[Unit]): Observable[A]
```

Implementation notes:

- the returned `Observable` is cancelable and cancelation needs to take into account at least `acquire`, which yields a task that could also be cancelable
- it needs to trigger `release` on early stop (by noticing `Stop` events in `onNext`)
- it needs to trigger `release` on `onComplete` and `onError`
- it needs to trigger `release` the observable gets cancelled
- `release` can be executed only once and cancelation is concurrent with whatever happens in onNext/onComplete/onError, so some synchronization is required

To use for inspiration:

- [doOnTerminate](https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/DoOnTerminateOperator.scala)
- [doOnSubscriptionCancel](https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/DoOnSubscriptionCancelObservable.scala)

**Comment by Avasil** [comment]
@alexandru 
Should we trigger `release` before or after `onComplete` and `onError` ?

**Comment by Avasil** [comment]
@alexandru 

There were some changes to `bracket` because of cats-effect integration.
Until now I was working on those signatures:
```scala
final def bracketTask[A, B](acquire: Task[A])(use: A => Observable[B], release: A => Task[Unit]): Observable[B]

private[reactive] def bracketA[A, B](acquire: Task[A])(
  use: A => Observable[B],
  release: (A, BracketResult) => Task[Unit]
): Observable[B]
```

should I change it to:

```scala
final def resourceTask[A, B](acquire: Task[A])(release: A => Task[Unit]): Observable[A]

final def bracketTask[B](use: A => Observable[B])(release: A => Observable[Unit])

final def bracketCaseTask[B](use: A => Observable[B])(release: (A, ExitCase[Throwable]) =>  Observable[Unit])
```

Should I also try to implement cats-effect typeclasses with `Observable` or just keep it something else but with similar functionality?

**Comment by Avasil** [comment]
Added in #729
