### ISSUE TITLE
Wrong effect execution order in map2, mapBoth, zipMap

### ISSUE THREAD

**Issue by Odomontois** [monix/monix#663]
This code
```scala
Await.result(
  Task.map2(
    Task.delay(println("first")),
    Task.delay(println("second")))
  ((_, _) => ()).runAsync,
  Duration.Inf)
```
constantly prints
> second
> first

Which is very misleading.

**Comment by alexandru** [comment]
For `Task.map2` you are right, they should have been evaluated in order — not sure how we missed that.

For `mapBoth` and `zipMap` (they are the same), that's normal behavior, because you don't get a guarantee about order of execution, the tasks being meant to execute in parallel.

**Comment by Odomontois** [comment]
Yes, about mapBoth and zipMap It's sounds intuitive and follows from what I've seen in TaskMapBoth code.
It's just strange that map2 is defined via zipMap
