### ISSUE TITLE
Task.gather[Unordered] Should Defer To Scheduler For Determining Parallelism

### ISSUE THREAD

**Issue by dccorona** [monix/monix#672]
Currently, `Task.gather` and `Task.gatherUnordered` (and also `Task.zipList`) determine whether or not to execute the tasks in parallel based on whether explicit async boundaries exist or not (i.e. tasks created with `Task.apply` or `Task.fork` will run in parallel...if all the tasks use `Task.eval`, they'll always run synchronously. However, this feels unnecessarily explicit, and takes away one of the great advantages of Monix when using these APIs: defining the business logic and the execution strategy are completely separate. Ideally, even if all of my tasks are created using `Task.eval` or some other mechanism that does not make tasks explicitly async, they should still execute in parallel during a `Task.gather` or similar aggregation if the scheduler says they should. However, to achieve parallel execution in this case, I need to explicitly declare my tasks as async, breaking the nice separation of concerns most of the other Monix APIs afford me.

It would be awesome if, by simply changing my scheduler, I can make an execution of dozens of tasks switch from sync to partial or full async, etc. Please see below for an example of the current behavior: 

    import monix.eval.Task
    import monix.execution.{ExecutionModel, Scheduler}
    
    import scala.concurrent.Await
    import scala.concurrent.duration.Duration
    
    def myThread = Thread.currentThread().getId
    
    val evals = for (_ <- 0 to 1000) yield Task.eval(myThread)
    
    val applys = for (_ <- 0 to 1000) yield Task(myThread)
    
    val batched = Scheduler.io("batched")
    val async = Scheduler.io("async", executionModel = ExecutionModel.AlwaysAsyncExecution)
    val sync = Scheduler.io("async", executionModel = ExecutionModel.SynchronousExecution)
    
    val batchedUsedEval = Await.result(Task.gather(evals).runAsync(batched), Duration.Inf).toSet.size
    val asyncUsedEval = Await.result(Task.gather(evals).runAsync(async), Duration.Inf).toSet.size
    val syncUsedEval = Await.result(Task.gather(evals).runAsync(sync), Duration.Inf).toSet.size
    
    val batchedUsedApply = Await.result(Task.gather(applys).runAsync(batched), Duration.Inf).toSet.size
    val asyncUsedApply = Await.result(Task.gather(applys).runAsync(async), Duration.Inf).toSet.size
    val syncUsedApply = Await.result(Task.gather(applys).runAsync(sync), Duration.Inf).toSet.size

     //batchedUsedEval: Int = 1
    //asyncUsedEval: Int = 1
    //syncUsedEval: Int = 1
    //
    //batchedUsedApply: Int = 15
    //asyncUsedApply: Int = 79
    //syncUsedApply: Int = 3

**Comment by Avasil** [comment]
You might like #670
