### ISSUE TITLE
Iterant: stateful scan

### ISSUE THREAD

**Issue by badmitrii** [monix/monix#687]
Hi. I would like to propose a small enhancement of `Iterant::scan`. It seems one may wish to emit the result not on each step, but according to some state transition. Here is what I mean:

`final def statefulScanOption[S, T](seed: => S)(op: (S, A) => (S, Option[T])): Iterant[F, T]`

**Comment by oleg-py** [comment]
@badmitrii can it be done with existing combinators, e.g. `xs.scan(seed)(op).collect { case Some(t) => t }`?

**Comment by badmitrii** [comment]
@oleg-py Yes, you are exactly right. Thanks.
