### ISSUE TITLE
Why is the ParallelApplicative private?

### ISSUE THREAD

**Issue by rpiaggio** [monix/monix#692]
We are building an Applicative-based validation library and it would be great to allow bringing the ParallelApplicative into scope to allow for parallel execution of Task-based validations.

Could it be made public?

**Comment by alexandru** [comment]
`ParallelApplicative` violates the coherency laws of type classes. Meaning that you shouldn't have an alterantive `Applicative[Task]` implementation.

**Comment by alexandru** [comment]
I tried pushing the functionality in Cats btw. 

See: https://github.com/typelevel/cats/pull/2019

**Comment by rpiaggio** [comment]
Thank you for your answer @alexandru.

I think that for specific cases, it still makes sense to be able to use the `ParallelApplicative` even though it violates the coherency laws. Maybe this could be made explicit to the user by placing it in a, say, `unsafe` package?

As it is, people like myself who want to use parallel tasks through `Applicative` will end up copy/pasting the code from `ParallelApplicative`, which doesn't make much sense.

**Comment by alexandru** [comment]
> As it is, people like myself who want to use parallel tasks through Applicative will end up copy/pasting the code from ParallelApplicative, which doesn't make much sense.

I agree. But if it has to happen, I was hoping for it to happen in Cats.

Unfortunately that's going to happen in Cats 2.0 if at all, because it breaks binary compatibility.

**Comment by rpiaggio** [comment]
I see, I hope it makes it into Cats 2.0 then. We will still need access to `CatsParallelForTask`, which is public.

Thanks again, I'll close this issue.
