### ISSUE TITLE
"tail -f"-ing rotating logs using Iterant

### ISSUE THREAD

**Issue by volth** [monix/monix#702]
I assume that a natural ```Iterant```'s use case (and probably the source of inspiration for monix.**tail** name) is following (```tail -f```ing) log files.

It would be nice to provide ```Iterant.followLinesFromFile``` and ```Iterant.followLinesFromDirectory``` (assuming there is the directory with log files where the latest file (alphanumerically) is growing, then a new file is created hourly or daily or when the current file is too big) in the ```object Iterant``` or in examples.

It is not as easy as it might look and might require interacting with ```inotify```.

**Comment by alexandru** [comment]
Having that functionality is a great idea, however I/O stuff can't be in core, we need a separate project.

We currently have `monix-nio`, but TBH it needs a reboot. I've been dreaming about it for some time, but haven't had any time for it.

**Comment by volth** [comment]
There is a problem with resource acquisition: if open files are wrapped with ```Iterant.resource``` they all will be closed only at the end of iteration.

Files are read sequentially each forming a ```NextBatch``` or  few ```NextBatch```es, but the number of files is potentially infinite so although it is not a leak (the files will be eventually closed), the number of open files in the middle of iteration might grow very big

**Comment by oleg-py** [comment]
With current Iterant encoding, files should be closed as soon as they are done processing, if you construct a stream correctly (e.g. by concatenation - `file1 ++ file2 ++ otherFiles.flatten`).

I'm going to close this for now, since it doesn't belong to the core monix.

**Comment by volth** [comment]
Yes, I ended up with using ```Observable``` for ```tail-f```-ing.
Although ```Iterant``` was looking "natural" for that, sometimes it is very tricky to use.
