### ISSUE TITLE
Missing `SemigroupK[Task]` instance

### ISSUE THREAD

**Issue by jendakol** [monix/monix#703]
Hello, is there some reason why there is `SemigroupK[Task]` instance **not** present in `Task` companion object (like there are instances for some other Cats typeclasses)? If not, please add it (or I can do it via PR).  
I tried to implement it and simple copy-paste from `cats.affect.IO` works:
```scala
implicit val taskSemigroupK: SemigroupK[Task] = new SemigroupK[Task] {
  def combineK[A](a: Task[A], b: Task[A]): Task[A] =
    ApplicativeError[Task, Throwable].handleErrorWith(a)(_ => b)
}
```

**Comment by Avasil** [comment]
I don't think there is any specific reason, PR will be appreciated @jendakol :)

**Comment by oleg-py** [comment]
I'm closing it, as we now have an instance 👍
