### ISSUE TITLE
Plan for the Cats-Effect 1.0.0 Update

### ISSUE THREAD

**Issue by alexandru** [monix/monix#710]
We have to release a version compatible with Cats-Effect 1.0.0 and soon.

Currently these are the pending issues:

1. make `Task` back-pressure on the finalizers on cancellation, like we did in Cats-Effect's `IO` — this is not a very easy change, will work on it either tonight or tomorrow night
2. make `Task` auto-cancelable by default (change the default setting); the design of the type classes clearly favors auto-cancelation by default, therefore the current model has to be opt-in; and we also need to remove the `cancelable` method and replace it with `continual`
3. change `MVar` and `TaskSemaphore`, to inherit from those in Cats-Effect, and possibly use those implementation as a short-cut until we can provide more optimal implementations, see discussion at #708

Not sure if I thought of anything.

**Comment by Avasil** [comment]
I can do 3. today. 
How are we going to let users know that `read` semantics are changed?

**Comment by alexandru** [comment]
`MVar.read` becoming atomic is a relaxation not an added constraint, so a change in ScalaDoc is fine.

**Comment by Avasil** [comment]
@alexandru 
So I looked into it and both `MVar` and `TaskSemaphore` are based on their Async `Future` versions so we can't really mix them with Cats-Effect implementations.

It  comes down to whether we implement all missing operators there or change `MVar` / `TaskSemaphore` to call `Cats-Effect` constructors directly. Or get rid of it completely.

Would be cool to have it implemented in a way that both `Async` and `Task/F` versions have the same operations but I'm afraid it will take too much time and it's not worth prolonging the release. Adding new public methods to `Async` variants shouldn't break binary compatibility right? So could be targeted for `3.1.0` (on related note, I'd love to see `Task` version of `AsyncQueue` :P)

**Comment by alexandru** [comment]
I forgot about the Future-enabled versions.

So it is fine if their implementations aren't based on the Future-enable version. But the API needs to be consistent. Not entirely sure how to proceed, but even the Future-enabled versions can be at first be based on `IO` and work from there.

So if you want to help with this, start with one of them and lets work from there.

**Comment by alexandru** [comment]
What I mean is, lets get the API changes in and we can worry about providing good implementations later.

**Comment by Avasil** [comment]
Seems like it's done, what's the plan forward? I'll have a spare time over the weekend so I can help getting closer to the release. :)

**Comment by alexandru** [comment]
The `Task` back-pressuring on finalizers like in IO is not done, but isn't a priority either.

After the queues are merged, I'll want to release a `RC2` as soon as possible, because it's been stalling since forever.

I don't know if there are any breaking changes left to do. Hopefully not.

**Comment by Avasil** [comment]
So after `RC2` plan for `3.0.0` are finalizers, `Observable.mapParallelOrdered` and ScalaFix / anything that comes up in the meantime?

**Comment by alexandru** [comment]
Closing this issue due to 3.0.0-RC2 release. Will create individual issues if needed.
