### ISSUE TITLE
Iterant.headOptionL and Iterant.tail at once

### ISSUE THREAD

**Issue by volth** [monix/monix#712]
It seems useful to have a function which would do ```Iterant.headOptionL``` and ```Iterant.tail``` at once for (head, rest)-iteration (yes, there is ```fold```-family of functions, but sometimes is it useful to perform "just one step", e.g. when merging many streams looking at their head's content)

Something like
```
  final def deconsL(implicit F: Sync[F]): F[(Option[A], Iterant[F, A])] =
    F.map(this.headOptionL) {
      case Some(hd) => (Some(hd), this.tail)
      case None     => (None, Iterant.empty)
    }
```

But this naive code won't work well: separate ```headOptionL``` and ```tail``` produce different "forks" of the ```Iterant```, evaluating ```Task```s inside the ```Iterant``` twice (besides the performance hit, it might result in double resource acquisition or in garbage output if the Task code is not deterministic)

**Comment by oleg-py** [comment]
I think FS2 has it as `uncons1` on `Pull`. There's also a variant for getting a next batch completely, which we might want as well.

**Comment by Avasil** [comment]
So `uncons1` and `unconsBatch`? 
I see they [have many variants](https://github.com/functional-streams-for-scala/fs2/blob/series/1.0/core/shared/src/main/scala/fs2/Stream.scala) we could take inspiration from but these two might be good enough.

Wanna do PR @volth for any of them?

**Comment by volth** [comment]
> Wanna do PR @volth for any of them?

I have a simple implementation made by colliding those of ```headOptionL``` and ```tail``` but it seems too buggy for a PR (it does not handle ```Scope``` properly)
