### ISSUE TITLE
Implement Task.timed

### ISSUE THREAD

**Issue by Avasil** [monix/monix#714]
@guizmaii has mentioned on Twitter that he's often missing following method:

```scala
final def timed: Task[(Duration, A)]
```

See [Scalaz-ZIO](https://github.com/scalaz/scalaz-zio/blob/master/core/shared/src/main/scala/scalaz/zio/IO.scala#L527)

`Task` has methods like `deferAction`, `async0` and `cancelable0` which allow access to the `Scheduler` (for clock) so it should be very easy to implement.

@guizmaii 
Do you still want to make PR or you don't mind if someone else takes this?

**Comment by guizmaii** [comment]
Hi @Avasil 

I still want to do it but if someone does the job it's ok for me.

I'll be in a train all the day tomorrow, going to Scotland. I'll try to push you a PR. :)

**Comment by guizmaii** [comment]
Hi @Avasil and @alexandru,

I've pushed an initial implementation here https://github.com/monix/monix/pull/715. 
Let me know your thinking about it.
