### ISSUE TITLE
Missing Alternative instance for Observable

### ISSUE THREAD

**Issue by jferris** [monix/monix#722]
There are instances for Applicative and MonoidK, but not for Alternative. Observable already implements all the necessary abstract methods.

Adding Alternative to `Observable.CatsInstances` allows methods like `guard` to be used. It's also more convenient as an implicit dependency than `MonoidK with Applicative`.

**Comment by alexandru** [comment]
Sure, do a PR.

**Comment by alexandru** [comment]
Ah, you already did 🙂
