### ISSUE TITLE
Add guarantee and guaranteeCase to Task

### ISSUE THREAD

**Issue by alexandru** [monix/monix#730]
Somehow I missed adding `guarantee` and `guaranteeCase` to `Task`. We should add them.

**Comment by bhop** [comment]
Hi @alexandru,

I happy to take this one. Let me know if the signatures are correct:
`
def guarantee[A](fa: Task[A])(finalizer: Task[Unit]): Task[A]
def guaranteeCase[A](fa: Task[A])(finalizer: ExitCase[E] => Task[Unit]): Task[A]
`

**Comment by alexandru** [comment]
@bhop 👍  yes, that's fine.

Note this is about implementing the methods from [Bracket](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Bracket.scala).

**Comment by oleg-py** [comment]
We should also have these on `Coeval`. Let's not forget our sync side-kick 😃

**Comment by bhop** [comment]
Thanks @oleg-py, I will add them to `Coeval` too.
