### ISSUE TITLE
Observable.bufferTimedWithPressure operator with custom counting function

### ISSUE THREAD

**Issue by ybr** [monix/monix#735]
I need an operator that consider the sum of the size of elements as the count instead of the count of elements.

Something like:
def bufferTimedWithPressure[A](period: FiniteDuration, maxSize: Int, sizer: A => Int): Observable[Seq[A]]

The existing one could be rewritten in terms of the new:
def bufferTimedWithPressure[A](period: FiniteDuration, maxSize: Int): Observable[Seq[A]] = bufferTimedWithPressure(period, maxSize, _ => 1)

I implemented a version in our code base, I can propose a pull request.

**Comment by ybr** [comment]
This issue look sa lot like https://github.com/monix/monix/issues/447 but on another operator.

**Comment by Avasil** [comment]
If you already have implementation, PR should help in decision and having it in time for `3.0.0` :)

**Comment by ybr** [comment]
Ok @Avasil I'll try my best to submit it promptly :)
