### ISSUE TITLE
API for cancelling Observable from Consumer

### ISSUE THREAD

**Issue by felixbr** [monix/monix#737]
Hi, I'm having a blast using Monix and generally everything works great, but I encountered something that might be a common use-case with no good solution currently (or I'm just not able to find it in the source/docs).

When writing a stream of tweets (`Observable[Tweet]`) to the database as batch-inserts, I'd like to cancel the stream if I encounter a tweet I've already saved previously, as this means I don't have to fetch more tweets and can safe time and api-requests.

Here's the code:
```scala
  final case class BatchContainedAlreadySavedTweetException(fetchedCount: Int, insertedCount: Int)
      extends Exception("Last batch contained already saved tweet")

  val writeFavoritesToDB: Task[Unit] =
    twitterService
      .fetchFavoritesAsObservable(favUser)
      .bufferTumbling(100)
      .consumeWith(
        Consumer.foreachTask { tweetBatch =>
          favTweetsRepository.insertTweets(favUser, tweetBatch.toList).flatMap { insertedCount =>
            val fetchedCount = tweetBatch.size

            if (insertedCount < fetchedCount)
              Task.raiseError[Unit](BatchContainedAlreadySavedTweetException(fetchedCount, insertedCount))
            else
              Task.unit
          }
        }
      )
      .onErrorRecover {
        case BatchContainedAlreadySavedTweetException(fetchedCount, insertedCount) =>
          println(s"Stream cancelled: Inserted $insertedCount of $fetchedCount fetched")
          ()
      }
```

The code works fine, but as you can see I need a custom Exception that's used in `Consumer.foreachTask` to create a failing `Task` which cancels the stream and I have to remember to recover that Exception outside of the `Consumer` otherwise it blows up.

Using exceptions for flow-control is generally a bad idea and also not very functional. I was looking for something like the following:
```scala
Consumer.foreachTaskCancellable { tweetBatch =>
  favTweetsRepository.insertTweets(favUser, tweetBatch.toList).map { insertedCount =>
    val fetchedCount = tweetBatch.size

    if (insertedCount < fetchedCount)
      Cancel
    else
      Continue
    }
}
```
I know there is `Consumer.cancel`, but I haven't found a way to use it for this case.

Maybe I'm missing something and there is an easy solution already, but in any case I appreciate if you can point me in the right direction.

Cheers
~ Felix

**Comment by Avasil** [comment]
Hi @felixbr I think `takeWhile` on `Observable` might solve your problem. :)

If not, you could write your own simple short-circuiting `Consumer`, e.g:
```scala
val cons = new Consumer.Sync[Boolean, Unit] {
  override def createSubscriber(cb: Callback[Unit], s: Scheduler): (Subscriber.Sync[Boolean], AssignableCancelable) = {
    val out = new Subscriber.Sync[Boolean] {
      implicit val scheduler = s
      def onNext(elem: Boolean): Ack = if (elem) Continue else Stop
      def onComplete(): Unit = cb.onSuccess(())
      def onError(ex: Throwable): Unit = cb.onError(ex)
    }
    (out, AssignableCancelable.dummy)
  }
}
```

I'm glad you like the library and let me know if it helped.

**Comment by alexandru** [comment]
@felixbr @Avasil btw, the purpose of that `AssignableCancelable` being returned is to cancel the observable. So in case `Stop` returned from `onNext` is not enough.

So `AssignableCancelable` acts as a forward reference that will eventually be assigned with the cancelable of the subscription.

**Comment by alexandru** [comment]
In an effort to get on top of issues, will close this for now, but feel  free to add more comments, or re-open it if you feel that the answers don't solve your problem.
