### ISSUE TITLE
[idea] To check if coeval is initialised without touching it's value?

### ISSUE THREAD

**Issue by fancywriter** [monix/monix#747]
Hello! Is it possible to have some sort of lazy container which doesn't (yet) have any value and I want to check if it does. Suppose I have some resource (like database connection) which I may need or may not need - I want to run a script which (maybe) uses this connection, depending on other things. And by the end of the script I want to close resource (like database connection) if and only if it was opened, otherwise I don't want to do anything.

Of course it can be done with Option/Some/None, but options are not lazy... and it requires to change it from None to Some manually.

**Comment by alexandru** [comment]
`Coeval` is basically a function, like `Task` or `IO`, the `evalOnce` / `memoize` operations are just nice to have, but they break referential transparency. So a facility to check that `Coeval` was initialized is kind of incompatible with what `Coeval` is. 

You can workaround it by having some more side effects and state though 🙂

```scala
private val dbHandle = Atomic(Option.empty[Handle])

val db = Coeval.evalOnce { 
  dbHandle := initDB()
  dbHandle.get()
}

def release() = 
  dbHandle.getAndSet(None) match {
    case Some(db) => db.close()
    case _ => ()
  }
```

**Comment by alexandru** [comment]
Closing this for now. Feel free to re-open it.
