### ISSUE TITLE
contramap on Subscriber

### ISSUE THREAD

**Issue by Avasil** [monix/monix#748]
We have `contramap` for `Consumer`, now we also have `Profunctor` instance for `Subject` and it might be useful to have `Contravariant` for `Subscriber`. 

[Implementation of Consumer.contramap](https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/consumers/ContraMapConsumer.scala)

**Comment by alexandru** [comment]
👍

**Comment by Avasil** [comment]
@alexandru I went ahead and implemented it for both `Observer` and `Subscriber` but I have trouble testing the laws because I have to write `Eq` instance for `Observer`. Usually it's tested using side-effects but here I don't know implementations. Any ideas?
