### ISSUE TITLE
Should an Observable’s scan operator be re-evaluated for every subscriber?

### ISSUE THREAD

**Issue by djneades** [monix/monix#752]
I have a Scala.js 0.6.25 project using Monix 3.0.0-RC1. It has code that, when simplified, is along the following lines:

```scala
val messages = PublishSubject[Message]

val modelUpdates = messages
    .scan(initialModel) { (currentModel, msg) => {
        Log.info("scan")
        // we’d normally do something expensive here, but for now just keep the current model
        currentModel
    }
}
```

Subscribers subscribe to `modelUpdates` by calling this method:

```scala
def subscribe(notify: ListenerNotifyFn, completed: () => Unit): Cancelable =
    modelUpdates.subscribe(newModel => {
        notify(newModel)
        Continue
  }, ex => Log.error(ex.getLocalizedMessage), completed)
```

Everything works as I would expect, except that the scan operator seems to be evaluated once per subscriber. Thus, with two subscribers to `modelUpdates`, calling `messages.onNext(msg)` once results in two `scan` messages being logged. With one subscriber, only one `scan` message is logged.

I (perhaps mistakenly) would have expected the scan operator to have been evaluated only once per call to `messages.onNext`, regardless of the number of subscribers to `modelUpdates`. (I understand that `Observable`s don’t trigger execution or effects until there are subscribers, but it isn’t obvious to me that it is desirable for potentially expensive execution to be repeated for every subscriber.)

My question is thus: is the behaviour I am seeing expected, or potentially a bug (either in my code or in Monix)?

If the behaviour is expected, what would be the recommended way of ensuring that the scan operator is evaluated only once per `messages.onNext` call, regardless of the number of subscribers to `modelUpdates`?

It is, of course, entirely possible that I am doing something wrong somewhere …

Many thanks in advance for any assistance.

**Comment by djneades** [comment]
To follow up, if I pop a `.share` after the call to `scan`, I no longer get the repeated log messages when I have multiple subscribers. Thus:

```scala
val modelUpdates = messages
    .scan(initialModel) { (currentModel, msg) => {
        Log.info("scan")
        // we’d normally do something expensive here, but for now just keep the current model
        currentModel
    }
}.share
```

However, I have no confidence that this is the right (or even sensible) thing to have done.

**Comment by alexandru** [comment]
@djneades `Observable` streams are not shared by default between subscribers. By default (i.e. unless specified otherwise), on each `subscribe` you initiate a new data source.

Thus having two subscribers will lead to having two data sources open. These in the vocabulary of ReactiveX are called "called observables". To transform such an observable into a shared one, you have several methods that help.

`share` is fine, but I suggest `publish` instead.

**Comment by djneades** [comment]
@alexandru Thank you for that very clear explanation; I understand.

I did try using `publish` rather than `share`, but my subscribers don’t see any events (and the `scan` operator with the logging is never evaluated) when I do that. I don’t wish to impinge further upon your time, but do you have any ideas why that may be?

**Comment by djneades** [comment]
@alexandru Got it, thank you. That works perfectly now. Thank you again for your always excellent support.

**Comment by alexandru** [comment]
@djneades cool. Will close this for now.
