### ISSUE TITLE
Add Observable#filterTask

### ISSUE THREAD

**Issue by yanns** [monix/monix#758]
As we are using `Task` for everything, including logging, we would like to use `Observable.filter` but with a `Task[Boolean]` instead of a `Boolean` to be able to log what we needs.

Currently we need some boilerplate code, like:
```
      source
        .mapTask { element ⇒
          infoT(s"The log about the $element") >> Task.pure((element, element.keep))
        }
        .filter(_._2)
        .map(_._1)
```
Instead of:
```
      source
        .filterTask { element ⇒
          infoT(s"The log about the $element") >> Task.pure(element.keep)
        }
```

**Comment by Avasil** [comment]
I think there should be `flatTap` if you have cats import to do the logging before but it's still in two passes so having `filterEval` could have its use. Would you like to try doing PR?

**Comment by yanns** [comment]
Yes, I could try to do a PR for this if you think it's a good idea to have this in the library.
What about the naming? `filterTask` would be good?

**Comment by alexandru** [comment]
@yanns the convention changed, functions taking a `Task` action should be named with an `Eval` suffix, instead of `Task`

**Comment by yanns** [comment]
@alexandru thx for the quick feedback.
Do you think that this addition would be useful?

**Comment by alexandru** [comment]
@yanns sure, go ahead.

But if we have `filterEval`, we need `filterEvalF` too.
