### ISSUE TITLE
AsyncScheduler.scheduleAtFixedRate should schedule at the specified fixed rate with ScalaJS

### ISSUE THREAD

**Issue by djneades** [monix/monix#780]
The documentation for `scheduleAtFixedRate` states:

>Schedules a periodic task that becomes enabled first after the given
>    * initial delay, and subsequently with the given period. Executions will
>    * commence after `initialDelay` then `initialDelay + period`, then
>    * `initialDelay + 2 * period` and so on.

In practice, however, the Scala.js implementation in Monix 3.0.0-RC2 drifts, adding a small amount of unwanted additional delay between executions.

This program shows the problem:

```scala
import monix.execution.Scheduler.{global => scheduler}
import scala.concurrent.duration._

object App {
  def main(args: Array[String]): Unit = {
    val start = scheduler.clockMonotonic(MILLISECONDS)

    scheduler.scheduleAtFixedRate(1.second, 1000.milliseconds) {
      println(s"${scheduler.clockMonotonic(MILLISECONDS) - start} ms")
    }
  }
}
```

When compiled with Scala.js 0.6.25 + Scala 2.12.7 (with `fastOptJs`) and run under the current versions of both Firefox and Chrome, the console output is along the following lines:

```
1015 ms
2017 ms
3017 ms
4019 ms
5021 ms
6022 ms
7022 ms
8024 ms
9026 ms
10027 ms
11028 ms
12029 ms

...

95171 ms
96172 ms
97173 ms
98175 ms
99176 ms
100178 ms
```

As can be seen from this run with Chrome 70.0.3538.110 on Windows 10 October 2018 Update, the execution is 163 ms late after 100 seconds.

Many thanks for Monix, and for your attention on this.

**Comment by oleg-py** [comment]
Note that a native JS version using setInterval exhibits similar drift in Firefox but not in Chrome (at least on Mac I'm currently on)
```js
var start = Date.now(); setInterval(() => console.log(Date.now() - start), 1000)
```

**Comment by alexandru** [comment]
Could we implement some algorithm to avoid it?

**Comment by oleg-py** [comment]
Sure, I can take a look in the next few days
