### ISSUE TITLE
JavaScript source maps should have globally accessible paths

### ISSUE THREAD

**Issue by djneades** [monix/monix#781]
As shown in the attached Chrome screenshot, the Monix 3.0.0-RC2 source maps have paths beginning `Users/alex/Projects/monix/monix-upstream`. This makes debugging from within the browser harder, as the browser is unable to load the relevant sources directly (unless you are @alexandru).

As also shown in the screenshot, the scala, scala-js and cats source maps (excepting cats-effect, which also looks problematic here) have paths on raw.githubusercontent.com, thus making the sources accessible to the browser. It would be very helpful if Monix were to do likewise.

![chromedevtools](https://user-images.githubusercontent.com/4183286/48917120-1676b080-ee7d-11e8-87c9-0137f6fa4be5.jpg)

**Comment by djneades** [comment]
In case it helps, note that Cats tweaks the source maps in its [`build.sbt`](https://github.com/typelevel/cats/blob/master/build.sbt) thusly:

```
  scalacOptions += {
    val tv = tagName.value
    val tagOrHash =
      if (isSnapshot.value) sys.process.Process("git rev-parse HEAD").lineStream_!.head
      else tv
    val a = (baseDirectory in LocalRootProject).value.toURI.toString
    val g = "https://raw.githubusercontent.com/typelevel/cats/" + tagOrHash
    s"-P:scalajs:mapSourceURI:$a->$g/"
  },
```

**Comment by alexandru** [comment]
@djneades thanks for the report — can you do a PR, please?

**Comment by oleg-py** [comment]
Closing this as fix was already merged :)
