### ISSUE TITLE
Local state remains on previous thread after context switch

### ISSUE THREAD

**Issue by ljwagerfield** [monix/monix#787]
**Monix Version: `3.0.0-RC2`**

## Observed behavior:
When using `Local` the state is left behind on the previous thread after a context switch. For example, given a `Local[Int](default = 0)`, you start on `thread 1` and set `local=42` and then shift to another thread. On `thread 2` you automagically see `local=42`  thanks to `enableLocalContextPropagation`... BUT `local=42` remains on `thread 1`, even though the task is done with that thread. It assumes the next task will clean up before starting, which IMO makes the `default` value somewhat useless (as the value never really means anything useful to you, as it's only in its initial state when a task is arbitrarily scheduled onto a virgin thread).

## Expected behavior:
When context switch occurs `thread 1 / local` should be reverted to the `default=0` value.

## Reproduction steps:

```scala
object Application extends App {
  implicit val scheduler: Scheduler = Scheduler.traced
  val local = Local[Int](0)

  (0 to 1000).foreach { _ =>
    Task
      .eval {
        if (local() > 0) {
          println("Uh-oh!")
        }
        local.update(local() + 1)
      }
      .asyncBoundary // If you comment this out, all works fine... but with it in, demonstrates the context is left behind on the previous thread.
      .map { _ =>
        local.update(local() - 1)
      }
      .executeWithOptions(_.enableLocalContextPropagation)
      .runSyncUnsafe()
  }
}
```

**Comment by leandrob13** [comment]
@ljwagerfield I didn't realize you were using the `Local` directly. In this case that is the expected behavior since you are indeed jumping to an async boundary so it is ok to see that the local never gets back to 0 because you are not referencing the same var given that you are in another thread.

There are some known issues with `TaskLocal` restoring the local (https://github.com/monix/monix/issues/624) but this is not that case.

**Comment by ljwagerfield** [comment]
Ok, but out of interest: how could you implement a re-entrancy check using `TaskLocal`? This is something `ThreadLocal` was very useful for, but obviously won't work with `Task`s...

```scala
object Implicits {
  private val local = Local[Int](0)
  implicit class RichConnectionIO[A](val connectionIO: ConnectionIO[A]) {
    /**
      * Calls 'transact' internally, but warns on re-entrant calls which result in nested transactions. 
     **/
    def transactSafely(): Task[A] =
      if (local() > 0)
        println("WARN: nested transaction detected!")

      local.update(local() + 1)
      connectionIO.transact().doOnFinish(_ => Task.eval {
        local.update(local() - 1)
      })
  }
}
```
