### ISSUE TITLE
behavior of `Observable.bracket`

### ISSUE THREAD

**Issue by shengc** [monix/monix#789]
Apologize if it is not appropriate to ask for clarification of behavior of operator in the issue list. Gitter is blocked in my working environment.

Let's say I have the following setup:

```scala
val source = Observable.apply(1,2,3,4,5)

val sql: String = ???
val ds: javax.sql.DataSource = ???
def recv(id: Long): Observable[Long] =
  Observable.delay(ds.getConnection)
   .bracket(conn => 
      Observable.delay(conn.createStatement).bracket(st => 
         Observable.delay(st.executeQuery(sql)).bracket(rs =>
            Observable.fromIterable(
              Stream.continually(rs).takeWhile(_.next).map(_.getLong(1))
            )
         )(rs => Task.delay(rs.close()))
      )(st => Task.delay(st.close()))
   )(conn => Task.delay(conn.close()))
```

if I write something like the following,
```scala
import monix.execution.Scheduler.Implicits.global
val fut = source.flatMap(recv).foreach(println)
```
My question is, will the resource be released under the scope of bracket on per item basis from `Source`, or until the whole `Observable` is consumed, i.e., `onComplete`/`onError` is called?

**Comment by oleg-py** [comment]
@shengc sorry for the super late reply.

Indeed, in your case `bracket` release - and `ds.getConnection`, and `conn.createStatement` will be called on per item basis. The behavior you probably want is to do these once, outside.
