### ISSUE TITLE
Version of switchMap that waits for the child observable to complete

### ISSUE THREAD

**Issue by MartinHH** [monix/monix#793]
Current behavior of `switchMap` in Monix (3.0.0-RC2):

If the "parent" observable completes, an observable that was created using `switchMap` will complete immediately. This is different from RxScala (and apparently also from fs2), where the "switchMapped" observable will not complete until its current ("latest") child observable is completed.

(Find a minimal example here: https://gist.github.com/MartinHH/6977ee66963e438eaf9a4d8f6314893b)

While I could imagine that the current behavior is desirable in certain situations (and I guess it might be dangerous to just change the behavior of Monix' `switchMap`), I think it would be good to have a convenient method that supports the other behavior (wait for current child to complete).

**Comment by MartinHH** [comment]
P.S.: I just noticed I changed my original question from gitter and it became a feature request when I posted it here: Originally, I my question was if there is an idiomatic way in Monix to model the requested behavior (wait for current child to complete)? (That would be helpful enough for me...)

**Comment by alexandru** [comment]
@MartinHH it's fine as a feature request.

I haven't thought about it yet, have been busy, however we need to evaluate if the behavior you want can be expressed in another way, whether we should introduce a second operator with the behavior you want or whether we should change the current behavior.

I don't like the idea of having a different behavior than Rx unless it is justified and in this case it might not be justified.

So the question is: can one behavior be expressed in terms of the other? (doesn't matter which)

Otherwise we probably need both.

**Comment by alexandru** [comment]
Also thanks for opening the issue, it's certainly an interesting one.

**Comment by MartinHH** [comment]
Here's an idea how the current behavior could be expressed in terms of the requested one (and `materialize`/`dematerialize`):
```scala
  def switchMapCompleteEarly[A, B](o: Observable[A])(f: A => Observable[B]): Observable[B] =
    o.materialize.switchMap {
      case OnNext(a) =>
        // materialize child, but without OnComplete:
        (f(a) ++ Observable.never).materialize
      case OnComplete =>
        Observable.pure(OnComplete)
      case e: OnError =>
        Observable.pure(e)
    }.dematerialize
```

Of course, there would be the obvious cost of object allocation for the `Notification`objects.

**Comment by oleg-py** [comment]
I would actually consider this a bug.
```scala
Observable.unit.switchMap(_ => Observable.interval(1.second)).foreach(println)
```
prints a single value for me. Replace `switchMap` with `flatMap`, ant it continues printing.

IMO this is desired to hold, similar to monad left identity law:
```
Observable.now(a).switchMap(f) <-> f(a)
```
and now it does not. (Side note: we already have the variant of right identity law in SwitchMap tests)

And it has probably not surfaced for a long time b/c switchMap is used in context of infinite streams.
