### ISSUE TITLE
Task.timeout behavior

### ISSUE THREAD

**Issue by AlejandroME** [monix/monix#795]
Hello there,

Consider this example:

```
import monix.eval.Task
import monix.execution.Scheduler
import org.scalatest.{FlatSpec, Matchers}

import scala.concurrent.{Await, Future, TimeoutException}
import scala.concurrent.duration._

class MonixExampleTest extends FlatSpec with Matchers {

  "Task.deferFuture" should "throw a TimeoutException" in {
    implicit val scheduler = Scheduler.io(name = "TestScheduler")

    val t = Task.deferFuture {
      Future {
        Thread.sleep(6000L)
        1
      }
    }.timeout(4.seconds)

    val f = t.runToFuture

    intercept[TimeoutException]{
      Await.result(f, 5.seconds)
    }
  }

}
```

Monitoring the behavior of this example in VisualVM, I can see this:

![screenshot at 2018-12-14 13-52-26](https://user-images.githubusercontent.com/2565308/50021631-b7054f80-ffa7-11e8-931e-3780d688b735.png)

`TestScheduler-54` was the Thread in where this code ran. If you see, the timeout was set to wait 4 seconds, simulating a computation that doesn't complete in that time. We assert that the execution throws a `TimeoutException`, condition that is met.

I want to understand why didn't `timeout` cancel the execution of the task at the provided time. From what I understand about the VisualVM graphic, the thread was blocked for the time specified in `.sleep`, but once the `Await` time exhausts (1 second after the scheduled timeout), the Thread is still running, so no matter the timeout, the task doesn't get canceled.
Is this the correct behavior? Does the `.timeout` worked as expected?

According to the [docs](https://monix.io/docs/2x/eval/task.html#trigger-a-timeout):

> On timeout the source gets canceled (if it’s a source that supports cancelation).

We have a strange behavior in which we're seeing blocking actions that don't get completed in the specified timeout but they still run, causing undesirable effects. This blocking action is an Http service call with Akka-Http and we're using `timeout` for a custom exponential backoff implementation.

Our implementation uses `Task` as a container for `Future`, that's why the example provided here uses `.deferFuture`.

We're using Monix 2.3.3.

If you can point me in the right direction it would be greatly appreciated!

Thanks

**Comment by Avasil** [comment]
This is because `Thread.sleep` is not cancelable so it runs in the background up to the point that can be stopped. It will probably be similar in case of your HTTP call unfortunately. The problem boils down to the fact that you can't just suddenly stop arbitrary operations so if you want someone to be cancelable you need to provide necessary logic or use operations that are cancelable (e.g. try your example with `Task.sleep` if it's present in 2.3.3)

I think [this section](https://typelevel.org/cats-effect/datatypes/io.html#concurrency-and-cancellation) should be helpful to understand it better.

**Comment by AlejandroME** [comment]
@Avasil Thank you so much for the explanation! I think that we should be good with that in mind.

**Comment by Avasil** [comment]
@AlejandroME You're welcome, I will close the issue then but in case of further questions/problems feel free to ask here or on gitter (`monix/monix` or `typelevel/cats-effect` channels)
