### ISSUE TITLE
API for overriding Scheduler.reportException?

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#799]
On JS, I wanted to override `reportException` in a Scheduler and ended up in a bad situation:

* `AsyncScheduler` and `TrampolineScheduler` are final, so I cannot inherit from any of them.
* There are no utilities like `withExecutionModel` for creating one.
* There are no factory methods on Scheduler that take an `UncaughtExceptionReporter` for JS (there are for JVM).

I think we can port a number of JVM-only constructors to JS, such as this one:
```scala
def apply(reporter: UncaughtExceptionReporter, executionModel: ExecModel): Scheduler
```
and those taking ExecutionContext (since we have ECs in SJS, and schedulers are ECs themselves)

I'd also appreciate a method like `withExceptionReporter` too.

**Comment by alexandru** [comment]
You're right, we need that 👍
