### ISSUE TITLE
TaskLocal is not propagated when using bracket methods

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#806]
The following usage of `TaskLocal` seems to be broken with bracket-like methods:

```scala
import monix.eval._
import monix.execution.Scheduler.Implicits.global

val taskL = for {
  local <- TaskLocal(0)
  _ <- Task.unit.executeAsync.guarantee(local.write(1))
 // alternative:
//   _ <- Task.unit.guarantee(local.write(1).executeAsync)
  value <- local.read
} yield value

taskL
  .executeWithOptions(_.enableLocalContextPropagation)
  .runSyncUnsafe() // results in 0
```

@alexandru the code in `TaskBracket` seems to directly say to NOT restore locals. Not sure why should it be the case.

**Comment by alexandru** [comment]
I don't remember what the issue was TBH and why it made sense.

Will take another look.

Feel free to investigate yourself.

**Comment by alexandru** [comment]
@oleg-py does your latest PR (#807) fix this?

**Comment by oleg-py** [comment]
@alexandru nope. It addresses a separate issue. Didn't yet have a chance to look into that one

**Comment by Avasil** [comment]
@alexandru @oleg-py 

Actually, it seems like if we don't restore locals in `TaskShift` (set `restoreLocals = false` ) then it works and all the tests pass. I guess it's either the solution or we need more tests

The new local value is discarded here: 
```scala
override def prepareCallback: Callback[Throwable, Any] =
  new Callback[Throwable, Any] {
    def onSuccess(value: Any): Unit = {
      val locals = previousLocals
      if (locals ne null) Local.setContext(locals)
      callback.onSuccess(value)
     }
```

https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/internal/TaskRestartCallback.scala#L166

It was changed here: https://github.com/monix/monix/pull/647

Do you remember any context regarding this? I have been investigating this recently but I don't quite grasp Task's internals and can't really reason about potential repercusions. :( Though this case seems to be similar to `executeOn` explained in the PR.

**Comment by mdedetrich** [comment]
Is there a conclusion to this problem? We are trying to use `TaskLocal` and this bit us before?

**Comment by oleg-py** [comment]
@Avasil if the tests pass and it works, I'd say go for PR (since @alexandru seems to be busy for now).

**Comment by mdedetrich** [comment]
PR is open, although it may make a sense to wait for a few days to see if @alexandru responds with the original reasoning for what was done.

@alexandru @oleg-py Does it make sense to do a RC3 release (or a SNAPSHOT) once this problem gets resolved? Its effecting us on our end and I would love to solve the issue ASAP

**Comment by oleg-py** [comment]
Closing, as we already merged the PR
