### ISSUE TITLE
UncaughtExceptionReporter not guaranteed to be used

### ISSUE THREAD

**Issue by oleg-py** [monix/monix#829]
The `ExecutionContext` we're using in `AsyncScheduler` is hard-wired to use _its own reportFailure_. So, even if we pass ours, it's not going to use it. That means some of the builders provided on Scheduler companion aren't actually reporting exceptions with provided reporter.

For example, this simple snippet (on JVM):
```scala
import monix.execution.Scheduler
Scheduler(Scheduler.global, _ => ()).execute(() => throw new Exception)
```
is supposed to swallow the exception, but it is still being logged.

**Comment by alexandru** [comment]
@oleg-py you can wrap the Runnables into your own implementation that catches exceptions, but find a way to not do that in case the exception reporter isn’t customized

**Comment by oleg-py** [comment]
Yes, I'm doing it in #828, but we also probably need to fix it for our existing constructors.

**Comment by alexandru** [comment]
True, so to make it clear I'm thinking of something like the following, maybe in `ReferenceScheduler`...

```scala
protected def wrapRunnable(r: Runnable): Runnable = r
```

And then in `AsyncScheduler`:

```scala
override final def wrapRunnable(r: Runnable): Runnable = 
  if (reporter != null) r else new RunnableWithReporter(r, reporter)
```

Where `RunnableWithReporter` would be like:

```scala
final class RunnableWithReporter(r: Runnable, reporter: UncaughtExceptionReporter) {
  def run() = try r.run() catch { case NonFatal(e) => reporter.reportFailure(e) }
}
```
