### ISSUE TITLE
.reduce on Observable with one item emits an empty stream

### ISSUE THREAD

**Issue by ThijsBroersen** [monix/monix#832]
Using the .reduce operator on a single-item observable results in an empty stream.

```
import monix.reactive.Observable
implicit val ec = monix.execution.Scheduler.global

Observable.fromIterable(List(1,2)).reduce(_ + _).toListL.runToFuture 
//res8: monix.execution.CancelableFuture[List[Int]] = Async(
//  Future(Success(List(3))),
//  monix.eval.internal.TaskConnection$Impl$$anon$1@7fac18dc
//)

Observable.fromIterable(List(1)).reduce(_ + _).toListL.runToFuture
//res9: monix.execution.CancelableFuture[List[Int]] = Async(
//  Future(Success(List())),
//  monix.eval.internal.TaskConnection$Impl$$anon$1@279c4e3b
//)
```

**Comment by Avasil** [comment]
I think it's on purpose. I don't know the reasoning behind this decision though, might have been a mistake considering `List(1).reduceLeft(_ + _)` returns 1. `Iterant` will have similiar behaviour I think (`Some(1)`)

Can we fix this @alexandru ? I mean change is trivial but there's a chance for silently breaking users' code

**Comment by alexandru** [comment]
I don't remember any specific reason for that. Yes, it's fine to have the same behavior as `List` and `Iterant`.
