### ISSUE TITLE
Task#unsafeRunSync

### ISSUE THREAD

**Issue by Avasil** [monix/monix#835]
What would you think about adding `unsafeRunSync` to `Task`? 

I think `runSyncUnsafe` is cool for "IDE discoverability reasons" so we could keep it and add `unsafeRunSync` as an alias to make it easier for people familiar with `cats.effect.IO`.

**Comment by oleg-py** [comment]
I don't think we want two functions for exactly the same unsafe thing (IIRC the only exception is `Task.apply` + `Task.eval`), but I don't really care how it's named. We can deprecate the current one. This would simplify things for people migrating from IO to Task at the expense of people already using Monix.

If we go this route, we'd probably want to rename the rest of unsafe methods for consistency sake.

There are also alternatives: one can use `toIO.unsafeRunSync()` or create own extension methods.

Overall, I'm on the fence, but leaning to it's not being worth it.

**Comment by jvican** [comment]
> as an alias to make it easier for people familiar with cats.effect.IO
  
Sounds like there should be an extra module that adds all of this syntactic sugar to the API to make it easier to use for Cats users. I would probably avoid over-extending the core API and keep it as small as possible.

**Comment by Avasil** [comment]
I agree with you guys
