### ISSUE TITLE
Like tasks raceMany but just the failFast

### ISSUE THREAD

**Issue by fd8s0** [monix/monix#836]
What I've been meaning to do for a few days now is to run a few tasks which are different, but if any of them fail, it makes no sense to waste any more time (and it's important that they don't) on the others and they should get cancelled, however as long as they succeed they should keep on running.

I thought I had working code on this but it turned out I didn't, and I find myself wanting to copy paste TaskRaceList and make a few modifications.

Not sure if I'm doing something so unexpected, sounds reasonable to me but I haven't seen any examples of people trying to do it. Sounds like the concept of task races could be a bit more flexible or the underlying logic that makes it click could be abstracted out and be extended to do this kind of thing, or let you override the onSuccess / onError clauses

**Comment by Avasil** [comment]
@fd8s0 Isn't that behavior of `Task.gather` / `parSequence`?

**Comment by fd8s0** [comment]
@Avasil that was my original implementation... for some reason I decided it wasn't behaving, but now it behaves correctly, e.g.

```package net.structureit.homestead.aggregationmodel

import monix.eval._
import monix.execution.Scheduler.Implicits.global

import scala.concurrent.duration._
import scala.util.{Failure, Try}

object TestMonix {

  def main(args: Array[String]): Unit = {
    val w = Task {
      Console.err.println("lala"); Thread.sleep(2000)
    }
    val collection = Seq(
      Task {
        Console.err.println("foobar")
      },
      Task {
        Console.err.println("foo")
        Thread.sleep(1000)
        Console.err.println("bar")
        throw new RuntimeException
      }
    )

    val start = System.currentTimeMillis()
    val a = collection ++ (1 to 100).map(_ => w)
    Try {
      val exe = Task.gatherUnordered(a)
      exe.runSyncUnsafe(3 seconds)
    } match {
      case Failure(exception) =>
        val duration = (System.currentTimeMillis() - start) / 1000
        println(s"Ran for $duration seconds")
        throw exception
    }
  }

}
```

Note the thread sleeps are intentional because the code I need to run can unfortunately block threads.

Anyway, sorry to bother, closing.

**Comment by Avasil** [comment]
No worries @fd8s0 - in case the problem returns feel free to ask on gitter or through issue again
