### ISSUE TITLE
Bracket.use upon task cancellation reads outdated state if the resource is an MVar

### ISSUE THREAD

**Issue by lukasz-golebiewski** [monix/monix#853]
I noticed a weird behavior when using `MVar` together with the `Bracket` typeclass. My initial idea was to use it for synchronization instead of `Ref` together with a `Semaphore` but I hit a corner case which ended with a deadlock. The test below when added to the `BaseMVarJVMSuite` gives an outlook on the problem. I believe the correct behavior would be if the assertion never failed, but it does with:
`Caused by: minitest.api.AssertionException: Should have been canceled when state was -1 but was with 5`

```scala

test("MVar (concurrent) — bracket.use doesn't return latest state on cancel") { implicit ec =>
    def run = {

      import cats._
      import cats.effect.ExitCase._

      def decrement(d: MVar[IO,Int]) = for {
        _ <- Sync[IO].bracketCase(d.take) { v =>
          Monad[IO].ifM[Unit]((v < 0).pure[IO])(
                      ifTrue = MonadError[IO, Throwable].raiseError[Unit](new IllegalArgumentException("Value is below zero")) ,
                      ifFalse = d.put(v - 1)
              )}{
            case (_, Completed) => IO.unit
            case (previous, Canceled) => IO(assert(previous == -1, s"Should have been canceled when state was -1 but was with $previous" )) *> d.put(previous)
            case (previous, _) => d.put(previous)
          }
        } yield ()

      for {
        d     <- MVar.of[IO, Int](5)
        fb    <- Parallel.parSequence(List.fill(100)(decrement(d))).handleError{case e : IllegalArgumentException => List(())}
        res   <- d.read
      } yield res
    }

    for (_ <- 0 until iterations) {
      assert(run.unsafeRunTimed(timeout).nonEmpty, s"; timed-out after $timeout")
    }
  }
```

**Comment by oleg-py** [comment]
Hi @lukasz-golebiewski. It seems you are using `cats.effect.concurrent.MVar` and `cats.effect.IO`, so it's probably a question to ask on cats-effect gitter or a repo

**Comment by lukasz-golebiewski** [comment]
Sure, can do - thanks for the hint. What is the purpose of `MVarJVMSuite` in `monix-catnap`? My test is based on those, and they also seem to be testing `cats.effect`

**Comment by Avasil** [comment]
@lukasz-golebiewski `MVar` was ported to `Cats-Effect` from Monix but we decided to keep Monix implementation which extends `Cats-Effect` one but also allows `Future` and customizing Atomic's Padding

**Comment by lukasz-golebiewski** [comment]
Closing in favor of https://github.com/typelevel/cats-effect/issues/503
