### ISSUE TITLE
Support Scala 2.13.0

### ISSUE THREAD

**Issue by Avasil** [monix/monix#862]
`Scala 2.13-RC1` has been released with many improvements to Scala's Future. Would be interesting to see how it affects `Observable` which uses `Future` internally.

Currently blocked by following releases:
- minitest
- cats
- cats-effect

`kind-projector` will need to be changed to
```scala
"org.typelevel" % "kind-projector" % "0.10.0"
```

**Comment by Avasil** [comment]
New version of monitest: `2.4.0`
So just waiting for cats/cats-effect

**Comment by SethTisue** [comment]
cats 2.0.0-M1 and cats-effect 2.0.0-M1 have been published for Scala 2.13.0-RC1

**Comment by Avasil** [comment]
Thanks @SethTisue - I made a PR #875 
Not sure how fast we can release proper version but we could definitely do at least a snapshot soon

**Comment by ALPSMAC** [comment]
Scala 2.13 has been released.  Would love to have a corresponding Monix 3.0 official release too :-)

**Comment by Avasil** [comment]
@ALPSMAC We're going to release for Scala 2.13 as soon as stable Cats-Effect version supporting this release is available (I think it is planned in the next 2-3 weeks)

**Comment by ALPSMAC** [comment]
Ah - perfect - thanks!

**Comment by Daenyth** [comment]
@Avasil Could a milestone build be put out until then, for people to start doing WIP upgrades?

**Comment by Avasil** [comment]
@Daenyth Sure, I will release something in a couple of hours

**Comment by Daenyth** [comment]
Much appreciated!

**Comment by Avasil** [comment]
@Daenyth 
The release is in progress but `2.13` should be already available
`3.0.0-eddc79d-SNAPSHOT`

The version is the latest master + dependencies supporting 2.13

**Comment by Daenyth** [comment]
What resolver do I need for that?

**Comment by Avasil** [comment]
@Daenyth I think it's `"Sonatype OSS Snapshots" at "http://oss.sonatype.org/content/repositories/snapshots/"`

**Comment by alexandru** [comment]
`3.0.0` is now released with support for Scala 2.13
