### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by adamw** [monix/monix#873]
Are there any plans for a RC3 or 3.0-Final? :) 

I think master has some fixes to concurrent usage of `Local`s which might be useful

**Comment by Avasil** [comment]
The plan for the next release is after we fix all issues with `Local` / `TracingScheduler` 
Shouldnt be that far n the future if this PR makes it to master: https://github.com/monix/monix/pull/866

**Comment by adamw** [comment]
Thanks! :)
