### ISSUE TITLE
Make a RT "fire and forget" function

### ISSUE THREAD

**Issue by mdedetrich** [monix/monix#877]
So we kind of have this problem in our services where we do a lot of "fire and forget" tasks. These are tasks that follow these properties

* Do not block, even in the resulting computation, i.e.
```scala
for {
  _ <- doSomething
  _ <- fireAndForgetTask.executeAsync
  _ <- anotherFireAndForgetTask.executeAsync
} yield ()
```

In this example, by fire and forget we mean that this for expression will immediately exist after `doSomething`, we do not wait for either `fireAndForgetTask` or `anotherFireAndForgetTask` to complete, i.e. the for comprehension will return immediately after `doSomething` is finished.

* Do not prevent the current computation in case of any error (this can be currently already be done with the various recover functions)

The issue is I don't think this is currently possible without having to unsafely run a `Task` into a `Future` (which is what we currently do, i.e. `runToFuture`). This has actually kind of caused incidents because said functions are not RT (so they executed immediately when they weren't meant to since they weren't suspended)

Is it possible to create a RT "fire and forget" style function. Note this may also already be possible, but from all of the reading online people say the only real way to do true "fire and forget" is to use `runToFuture` (in which case it may be a documentation issue and/or we may also need to create a handy helper function).

**Comment by Avasil** [comment]
Wouldn't `start.void` do what you want? Or is it about `2.x`?

**Comment by alexandru** [comment]
We also have `forkAndForget` which should be more optimal.

**Comment by alexandru** [comment]
Speaking of which, we should probably rename it to `startAndForget`, since `fork` comes from a time when `start` was not automatically forking.

**Comment by alexandru** [comment]
Also if actual execution is necessary, we also have `runAsyncAndForget` instead of `runToFuture` 🙂

**Comment by mdedetrich** [comment]
> Wouldn't start.void do what you want? Or is it about 2.x?

We were using Monix 2.x up until recently

**Comment by mdedetrich** [comment]
@alexandru Should I make a PR to deprecate `forkAndForget` and rename it to `startAndForget`? Also just to clarify, `forkAndForget` doesn't delay the current computation its running on (i.e. its not just ignoring the error of the computation?)

I will also make a PR for documentation since i think its missing there.

**Comment by alexandru** [comment]
`forkAndForget` will do the equivalent of `start.map(_ => ())` meaning that it forks the task, executing on another thread, but then does not wait for the computation to finish in any way.

Also in case of errors, the errors get logged via `Scheduler.reportFailure`.

**Comment by alexandru** [comment]
Yes, you can do the PR if you want to help.

**Comment by Avasil** [comment]
> @alexandru Should I make a PR to deprecate `forkAndForget` and rename it to `startAndForget`? Also just to clarify, `forkAndForget` doesn't delay the current computation its running on (i.e. its not just ignoring the error of the computation?)

It "succeeds" as soon as this computation is started:

```scala
private[eval] object TaskForkAndForget {
  /**
    * Implementation for `Task.startAndForget`.
    */
  def apply[A](fa: Task[A]): Task[Unit] = {
    val start = (ctx: Context, cb: Callback[Throwable, Unit]) => {
      implicit val sc = ctx.scheduler
      // It needs its own context, its own cancelable
      val ctx2 = Task.Context(sc, ctx.options)
      // Starting actual execution of our newly created task forcing new async boundary
      Task.unsafeStartEnsureAsync(fa, ctx2, Callback.empty)
      cb.onSuccess(())
    }
    Task.Async[Unit](start, trampolineBefore = false, trampolineAfter = true)
  }
}
```

> I will also make a PR for documentation since i think its missing there.

That would be fantastic!

**Comment by mdedetrich** [comment]
Awesome many thanks, will set up a PR both for renaming the method and for docs

**Comment by Avasil** [comment]
@mdedetrich are you still interested in doing this? If not, I can use it for Scala Spree next week

**Comment by mdedetrich** [comment]
I was on a holiday in the middle east with no laptop, just came back today. I can do it tomorrow, sorry for the delay.
