### ISSUE TITLE
Split out Monix's Local into its own project/dependency

### ISSUE THREAD

**Issue by mdedetrich** [monix/monix#880]
So basically Monix's `Local` has really nothing to do with Monix itself, its basically a helper over an immutable map that stores its data into a `ThreadPool` which provides suspension on its effectful methods so that it can be used sanely with `Task`.

Which gets to the second point, it can be used not only with `Task` but also Cats `IO` or even ZIO. There is nothing that ties `Local` to Monix.

Would everyone be open to just making `Local` into its own project/dependency? Ideally it would even be its own subproject under the monix org (the implementation is trivial and quite self contained) however as a first step we can just split it into its own package. 

There can even be an argument that this can belong to cats-effect/cats repo, but this may be stretching it a bit far.

**Comment by alexandru** [comment]
`Local` is from `monix-execution`, a sub-project. You don't need to depend on `Task` in order to use `Local`.

**Comment by mdedetrich** [comment]
Ah thats fantastic, would it make sense to make it its own github project (under the monix repo)?

**Comment by mdedetrich** [comment]
I will close this for now, I think the push for making `monix-execution` its own project isn't backed by evidence that the modularity is needed for now

**Comment by kag0** [comment]
@mdedetrich are there any examples or documentation of `Local` being used with something like cats `IO` or ZIO?
