### ISSUE TITLE
Certificate issues on monix.io

### ISSUE THREAD

**Issue by vilu** [monix/monix#881]
![Screenshot 2019-05-14 at 13 47 07](https://user-images.githubusercontent.com/1489367/57695558-de437400-764e-11e9-87a8-2cfe023cb6e4.png)

**Comment by alexandru** [comment]
Hi @vilu,

Indeed, thanks for the report.

I configured an automatic [Letsecrypt](https://letsencrypt.org) renewal on the server, however the script was frozen, don't know since when and the certificates were expired.

The website should be up now.
