### ISSUE TITLE
Bring back Observable.Transformer?

### ISSUE THREAD

**Issue by Avasil** [monix/monix#891]
We used to have ` type Transformer[-A,+B] = Observable[A] => Observable[B]` type alias with corresponding function

```scala
override def transform[B](transformer: Transformer[A, B]): Observable[B] =
    transformer(this)
```

which was removed in `3.x`. It's trivial to implement for the user but I feel like it's quite convenient and many people like this style of transforming streams (looking at the usage of `fs2.through`, `AkkaStream.via` and even [Monix presentation](https://monix.io/presentations/2018-practical-reactive-streams-jacek-kunicki-sbtb.html) etc).

What do you think? And would the syntax stay the same, or shorter?

**Comment by oleg-py** [comment]
I used to like that method, as it makes chaining observable operations easier, but

- `typelevel/mouse` and 2.13s `scala.util.chaining._` already give you more universal syntax
- fs2 has a handful of methods that take it's version (Pipe), not just `through` (e.g. observe, broadcastTo and balanceTo)

So, I'm not convinced it's very valuable going forward, but I'm not a heavy user of `Observable`, so would be open to know if anybody else wants it.

**Comment by Avasil** [comment]
@oleg-py 
> typelevel/mouse and 2.13s scala.util.chaining._ already give you more universal syntax

Good point, though both options require extra import and it will take a while until everyone migrates to 2.13

There are several thumbs up on my first comments and people ask about it from time to time on gitter so I feel like having it available could ease migration. I'm thinking we could either bring it back or have it deprecated but available for now. 

@alexandru Do you remember why it was removed?

**Comment by babyman** [comment]
I pulled this from @Avasil comment in GITTER for anyone who, like me, has been confounded by the code in older presentations

```scala
  implicit class ObservableSyntax[A](val o: Observable[A]) extends AnyVal {
    def transform[B](f: Observable[A] => Observable[B]): Observable[B] = f(o)
  }
```

**Comment by paualarco** [comment]
In my opinion the `transform(Transformer)` signature was very useful and would be very nice to bring it back in future releases :)
