### ISSUE TITLE
Memory leak in MapParallelOrderedObservable

### ISSUE THREAD

**Issue by rfkm** [monix/monix#892]
The number of child cancelables of `CompositeCancelable` will increase unlimitedly due to wrong cleanup logic.

An instance of `SingleAssignCancelable` is added to `composite` [here](https://github.com/monix/monix/blob/af9e61e6d655cf8e043b681741d480ae8c9f9e8c/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/MapParallelOrderedObservable.scala#L134) but the cleanup code seems to try to remove its underlying cancelable [here](https://github.com/monix/monix/blob/af9e61e6d655cf8e043b681741d480ae8c9f9e8c/monix-reactive/shared/src/main/scala/monix/reactive/internal/operators/MapParallelOrderedObservable.scala#L104).

**Comment by Avasil** [comment]
@rfkm Nice catch, thanks!
It looks like we could add `future.cancelable` to the composite and get rid of `SingleAssignCancelable` entirely. Would you be interested in making PR?
