### ISSUE TITLE
Change Task.apply to Task.evalAsync in MapParallelOrderedConcurrencySuite

### ISSUE THREAD

**Issue by Avasil** [monix/monix#893]
This test should run all `Task` concurrently and not synchronously but it wasn't fixed when `Task.apply` behavior changed:

https://github.com/monix/monix/blob/master/monix-reactive/jvm/src/test/scala/monix/reactive/internal/operators/MapParallelOrderedConcurrencySuite.scala#L33 (here and in the 2nd test)

**Comment by oleg-py** [comment]
Would we actually notice any difference?

**Comment by Avasil** [comment]
@oleg-py I don't think so because it currently forces async boundary in the implementation but it would be consistent with `MapParallelUnorderedConcurrencySuite`
