### ISSUE TITLE
Make default scheduler remove cancelled tasks

### ISSUE THREAD

**Issue by alexandru** [monix/monix#912]
We need to look into this:

https://github.com/typelevel/cats-effect/pull/568/

As this might prevent some leaks with `timeout`.

**Comment by Avasil** [comment]
Easy to change but I'm not sure whether we should have 1 thread in pool or 2.

BTW Cats-Effect also changed the default Scheduler to its own: https://github.com/typelevel/cats-effect/issues/509 (PR is linked)
