### ISSUE TITLE
Add missing F[_]-polymorphic methods to Observable

### ISSUE THREAD

**Issue by Avasil** [monix/monix#914]
Many operators, like `mapEval` have equivalent working for `F[_]` which is convenient for people using other Effect type or writing using Tagless Final.

There are missing methods, e.g.:
- `mapParallelOrdered`
- `mapParallelUnordered`
- ` fromIterator`
- `consumeWith`
- `completedL`
And more. 

In some cases we might be able to express them in terms of Cats-Effect typeclasses but converting to/from `Task` is ok too.

**Comment by entangled90** [comment]
Hi, I'm picking this up if nobody has started working on it.
One simple question.
What's the standard way of converting a Task` to an `F[_]`? 
The `TaskLike` constraint only wokrs on the other direction, from `F[_]` to `Task`.

**Comment by Avasil** [comment]
Solved in #941 
There are more methods but the most important ones are covered so closing this for now
