### ISSUE TITLE
Shifting back to the default pool in Task.fromFuture, Task.async and others

### ISSUE THREAD

**Issue by Avasil** [monix/monix#916]
Currently code like this:

```scala
Task.async[Unit] { cb =>
  foreignEC.submit(new Runnable {
    override def run(): Unit = {
      cb(Right(()))
    }
  })
}
```
Stays on `foreignEC` for the next operations until async boundary. Similar to `Future` and probably the rest similar operators. 

I'm not familiar with any situation when it's desirable but it can easily catch off-guard and is a source of confusion, see [recent blog post](https://blog.softwaremill.com/thread-shifting-in-cats-effect-and-zio-9c184708067b) and it was already changed for `fromFuture` in Cats-Effect: https://github.com/typelevel/cats-effect/pull/546

I believe the rest is planned to be fixed in `3.0`. Do you think we should do it and can we allow it such a change right now? cc @oleg-py @alexandru 

I feel like it wouldn't be noticable to the users unless there are use cases from current behavior that I'm not aware of.

If we agree to do it, I can provide a PR

**Comment by alexandru** [comment]
It might make sense for `Task.async` to shift back to the default `Scheduler`.

**Comment by alexandru** [comment]
Compared with `cats.effects.IO` we can do this without changing the API. And it might make `Task.async` safer.

My worry is that we might need some extra builders that don't shift. We already have `Task.async`, `Task.async0`, `Task.cancelable`, `Task.cancelable0` and `Task.create` 🙂
