### ISSUE TITLE
Bounded versions for Task.gather and Task.wander

### ISSUE THREAD

**Issue by Avasil** [monix/monix#926]
Recently `Cats-Effect`  added [`parSequenceN` and `parTraverseN`](https://github.com/typelevel/cats-effect/pull/498/files) and it can be used with `Task` but it will use generic `parSequence` / `parTraverse` from cats which is much slower than hand-optimized version we have.

[ZIO also has this operator named as foreachParN](https://github.com/zio/zio/blob/master/core/shared/src/main/scala/zio/ZIO.scala#L1734)

**Comment by Avasil** [comment]
One of the Scalamatsuri ScalaSpree attendants is working on this issue

**Comment by allantl** [comment]
@Avasil Any news on the progress? If not, can I pick it up? I found myself needing this in multiple projects. Would be nice to have it upstream.

**Comment by Avasil** [comment]
@allantl go ahead, I don't have any contact to this person but he told that's ok if someone else picks it up :)

**Comment by allantl** [comment]
@Avasil Just came across this https://github.com/zio/zio/issues/1165. WDYT?

**Comment by Avasil** [comment]
@allantl we should address it as well. Is it only about traverse or is there a problem (that can be solved) with sequence too? 

I don't have access to PC until tomorrow so I'll share few ideas later. I feel like there could be more efficient solution (ZIO.foreach has a quite naive impl) but need to check

**Comment by allantl** [comment]
I tried wander and gather with semaphore with `-Xmx512m`. 
Its quite slow, although there's no OutOfMemoryError.

**Comment by Avasil** [comment]
@allantl

I've taken a brief look and indeed we can't use `gather` because it will start everything.

I feel like the most efficient way (but also the hardest to implement) would be a low-level operator. Basically a clone of `TaskGather` but instead of starting everything, we can start first `n` tasks and then start a new one each time something has completed. [Here is a relevant part of the code](https://github.com/monix/monix/blob/master/monix-eval/shared/src/main/scala/monix/eval/internal/TaskGather.scala#L132). It will be complicated to get right but I expect performance gain to be siginificant (`gather` is 2-3x faster than `parSequence`).

Alternatively, we can also try to create it from existing combinators. I didn't think about it too much yet but probably will have to involve `ConcurrentQueue` or maybe `MVar`.

And there is of course an option to just keep initial approach with `Semaphore` + `gather`.

I think any of it can be good enough for now - we can always improve it later in binary compatible way. So it depends on how much time you are willing to spend on this. I'm happy to help with any approach you'll choose to try first.

**Comment by allantl** [comment]
@Avasil I'll take a stab at the first option. But, I'll probably make mistakes, since I'm not familiar with the internal. If I find it too challenging, I'll fallback to the semaphore + gather version.

**Comment by Avasil** [comment]
Don't hesitate to ask about anything in case of confusion

**Comment by alexandru** [comment]
The simplest way to implement this is to use `monix.catnap.Semaphore`:

```scala
def parSequenceN(n: Long)(tasks: List[Task[A]]): Task[List[A]] = 
  Semaphore[Task](n).flatMap { semaphore =>
    Task.gather(tasks.map(semaphore.withPermit))
  }
```

**Comment by Avasil** [comment]
@alexandru 
If we run something like `1000000` tasks it will start all of them and JVM might run out of memory so we're looking for other approaches
