### ISSUE TITLE
Task.*> and <* combinator

### ISSUE THREAD

**Issue by Avasil** [monix/monix#929]
It can be found in [cats.Apply](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Apply.scala) syntax and/or [cats.FlatMap](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/flatMap.scala)

but it's very common to use, so importing cats all the time is annoying.

```scala
final def *>[B](that: => Task[B]): Task[B]
final def <*[B](that: => Task[B]): Task[A]
```

```scala
taskA *> taskB // runs taskA, then taskB, returns the result of taskB
taskA <* taskB // runs taskA, then taskB, returns the result of taskA
```

**Comment by valenterry** [comment]
I will pick it up

**Comment by alexandru** [comment]
I see that we have `>>`. Can we also have `<*` and `*>`, with the signature from Cats?

These operators are still useful, in spite of their strict parameter and remember that many people import `cats.implicits._` anyway, so they are available.

**Comment by alexandru** [comment]
I use `<*` a lot for triggering side effects, like logs, after some important action.

**Comment by alexandru** [comment]
And `<*` shouldn't have a non-strict param, because it wouldn't help 😉
