### ISSUE TITLE
Add Observable.unfold

### ISSUE THREAD

**Issue by Avasil** [monix/monix#955]
```scala
def unfold[S, A](seed: => S)(f: S => Option[(A, S)]): Observable[A]
```

Similar to [fromStateAction](https://github.com/monix/monix/blob/master/monix-reactive/shared/src/main/scala/monix/reactive/internal/builders/StateActionObservable.scala) but stops as soon as `None` is generated

**Comment by oleg-py** [comment]
Why is `seed` the 2nd parameter list here? Wouldn't that cause worse inference, as `S` would fail to infer?

**Comment by Avasil** [comment]
Eh, I'd prefer it to be the first parameter but `fromStateAction` has it in this order... But in everywhere else it's the way you describe.

Maybe we can deprecate old methods and switch the order?

**Comment by alexandru** [comment]
Even though the ordering doesn't play well with Scala's type inference, the `seed` as the second parameter is the natural order in `fromStateAction`:

```scala
val randomNumbers = Observable.fromStateAction { (state: Long) =>
  val state2 = (state * 0X5DEECE66DL + 0XBL) & 0XFFFFFFFFFFFFL
  val n = (state2 >>> 16).toInt
  (n, state2)
} _
```

You just need an explicit type in that function to do this. What you gain however is that `randomNumbers` is a function and that seed is especially important ...

```scala
Task.deferAction { sc =>
  randomNumbers(sc.clockRealtime(MILLISECONDS))
}
```

In other words this isn't necessarily like `foldLeft` where you're always dealing with the same empty / zero element.

**Comment by Avasil** [comment]
Thanks for explanation @alexandru 
Makes sense to me, I withdraw my deprecation idea

Though `unfold` itself should follow the order of `fold` and other streaming libraries, right?

**Comment by alexandru** [comment]
Not sure. What are other libraries doing?

**Comment by Avasil** [comment]
@alexandru 

Akka streams: 
[def unfold[S, E](s: S)(f: S => Option[(S, E)]): Source[E, NotUsed]
](https://doc.akka.io/docs/akka/current/stream/operators/Source/unfold.html)

fs2:
```
def unfold[F[x] >: Pure[x], S, O](s: S)(f: S => Option[(O, S)]): Stream[F, O]
```

ZIO: 
```
final def unfold[S, A](s: S)(f0: S => Option[(A, S)]): Stream[Nothing, A]
```

**Comment by alexandru** [comment]
@Avasil thanks for looking into it.

Then do the state as the first param.

**Comment by pk044** [comment]
i can pick it up - i'm planning to create a pull request for this in the following days  :)
