### ISSUE TITLE
Changes after RC3 should not break binary compat in 3.0.0 for Scala 2.12

### ISSUE THREAD

**Issue by alexandru** [monix/monix#962]
We have #921 that apparently breaks binary compat.

Unfortunately we've broken binary compat far too often. We can't afford to piss off our users on every release, especially since we have downstream libraries depending on us like Quill.

`3.0.0` should be binary compatible with `RC3`, unless we want to fix something seriously broken and I don't think we have such broken APIs.

We need to change the work done in #921 such that we don't break binary compat again.

Consider this: most users won't object to the extra fork. The "unsafe" versions are not interesting. And if we really, really need them, then we can add them later with different names.

---

Changes to be investigated and possibly fixed:

```scala
     // Breaking changes for https://github.com/monix/monix/pull/921
    exclude[DirectMissingMethodProblem]("monix.eval.Task#AsyncBuilder.create"),
    exclude[ReversedMissingMethodProblem]("monix.eval.Task#AsyncBuilder.create"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.async0"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.deferFuture"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.cancelable"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.cancelable0"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.asyncF"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.async"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.fromFuture"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.deferFutureAction"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task#AsyncBuilder#CreatePartiallyApplied.apply"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task#AsyncBuilder#CreatePartiallyApplied.apply$extension"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskFromFuture.strict"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskFromFuture.deferAction"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate#Cancelable0Start.this"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.async0"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.cancelableIO"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.cancelableEffect"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.cancelable0"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.cancelableCoeval"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.asyncF"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.async"),
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskCreate.cancelableCancelable"),
    // Newly detected changes after upgrading mima to 0.4.0
    exclude[IncompatibleMethTypeProblem]("monix.reactive.instances.CatsProfunctorForSubject.dimap"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.observers.BufferedSubscriber.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.consumers.CompleteConsumer.apply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.observers.buffers.AbstractEvictingBufferedSubscriber.this"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.observers.buffers.DropNewBufferedSubscriber.withSignal"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.observers.buffers.EvictingBufferedSubscriber.this"),
    exclude[IncompatibleSignatureProblem](
      "monix.reactive.observers.buffers.EvictingBufferedSubscriber.dropOldAndSignal"),
    exclude[IncompatibleSignatureProblem](
      "monix.reactive.observers.buffers.EvictingBufferedSubscriber.clearBufferAndSignal"),
    exclude[IncompatibleSignatureProblem](
      "monix.reactive.observers.buffers.EvictingBufferedSubscriber.dropOldAndSignal"),
    exclude[IncompatibleSignatureProblem](
      "monix.reactive.observers.buffers.EvictingBufferedSubscriber.clearBufferAndSignal"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.observers.buffers.DropNewBufferedSubscriber.this"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.observers.buffers.DropNewBufferedSubscriber.withSignal"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.consumers.CancelledConsumer.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.operators.CompletedOperator.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.operators.CountOperator.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.operators.IsEmptyOperator.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.internal.operators.FailedOperator.apply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.apply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.unapply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.apply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.unapply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.this"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.copy"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.copy$default$2"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#ClearBufferAndSignal.onOverflow"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.this"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.copy"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.copy$default$2"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropOldAndSignal.onOverflow"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.this"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.copy"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.copy$default$2"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.onOverflow"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.apply"),
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.unapply"),
    exclude[IncompatibleMethTypeProblem]("monix.reactive.ObservableLike.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.eval.TaskLike.apply"),
    exclude[DirectMissingMethodProblem]("monix.eval.TaskLike.fromComonad"),
    exclude[IncompatibleMethTypeProblem]("monix.eval.CoevalLike.apply"),
    exclude[DirectMissingMethodProblem]("monix.eval.CoevalLike.fromComonad"),
    exclude[IncompatibleMethTypeProblem]("monix.eval.TaskLift.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.ExecutionRejectedException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.DummyException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.APIContractViolationException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.BufferOverflowException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.DownstreamTimeoutException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.CompositeException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.UpstreamTimeoutException.apply"),
    exclude[IncompatibleMethTypeProblem]("monix.execution.schedulers.StartAsyncBatchRunnable.apply"),
    exclude[IncompatibleSignatureProblem]("monix.execution.schedulers.ReferenceScheduler#WrappedScheduler.unapply"),
    exclude[IncompatibleResultTypeProblem]("monix.execution.Scheduler.Implicits"),
    exclude[IncompatibleResultTypeProblem]("monix.tail.batches.EmptyBatch.cursor"),
    exclude[IncompatibleResultTypeProblem]("monix.tail.batches.EmptyCursor.next"),
    exclude[IncompatibleMethTypeProblem]("monix.catnap.FutureLift.apply"),
    // Breaking changes for https://github.com/monix/monix/pull/934
    exclude[MissingClassProblem]("monix.eval.Task$DoOnFinish"),
```

**Comment by Avasil** [comment]
Mamy new filters were added after mima update:

https://github.com/lightbend/mima/releases/tag/0.4.0

Some of them might preserve bincompat and others were probably originally introduced in older version

> exclude[MissingClassProblem]("monix.eval.Task$DoOnFinish")

https://github.com/monix/monix/pull/934

It was private do its fine right?

**Comment by alexandru** [comment]
@Avasil we have to investigate.

First of all the `monixSeries` should be set to `RC3` as right now we only care about breakage since `RC3`.

**Comment by Avasil** [comment]
Regarding Task.create and others, I can return to 1 param. My use case for "unsafe" version was `Observable` because it can optimize on synchronous version. But it was using very few variants so maybe I will implement just those? I also had and idea for a name like `createDirect` instead of unsafe 

Oleg had a thought about adding it to task options, he explained in pr comments

**Comment by alexandru** [comment]
@Avasil in regards to #934, well, the issue isn't simple.

When you remove a class like that, it has an impact on Java serialization. For example when used with Spark. On the other hand we need the ability to replace internals, or otherwise we would go nuts.

So yes, removing private classes is totally fine.

**Comment by oleg-py** [comment]
This list raises suspicions.

E.g.
```scala
    exclude[IncompatibleMethTypeProblem]("monix.execution.exceptions.ExecutionRejectedException.apply"),
```
Has literally not changed since 2.3.3 except for formatting. The report suggests
```
method apply(java.lang.Object)java.lang.Object in class monix.execution.exceptions.ExecutionRejectedException's type is different in current version, where it is (java.lang.String)monix.execution.exceptions.ExecutionRejectedException instead of (java.lang.Object)java.lang.Object
```

This looks like something has changed with erasure and `AbstractFunction1` handling (we extend AbstractFunction1 in companion)

```scala
    exclude[IncompatibleResultTypeProblem]("monix.tail.batches.EmptyBatch.cursor"),
```
Has been there since the 3.0.0-M1, in the same shape.

The report isn't helping:
```scala
method cursor()monix.tail.batches.BatchCursor in class monix.tail.batches.EmptyBatch has a different result type in current version, where it is monix.tail.batches.EmptyCursor# rather than monix.tail.batches.BatchCursor
```
We never had that method returning `BatchCursor` and not EmptyCursor. The file was only touched in 3 commits, so I've got no idea where that would be picked from.

There _are_ also cases for broken APIs. For example,
```scala
    exclude[IncompatibleSignatureProblem]("monix.reactive.OverflowStrategy#DropNewAndSignal.apply"),
```
was replaced with a version where function returns a `Coeval` value, for purity sake. And while we can overload `apply`, we probably can't do that for `unapply`. Also, this guy:

```scala
    exclude[DirectMissingMethodProblem]("monix.eval.TaskLike.fromComonad"),
```

we decided is potentially more harmful than useful.

This one honestly look like a bug in MiMa:
```scala
exclude[IncompatibleMethTypeProblem]("monix.eval.TaskLike.apply"),
```
The report is 
```
method apply(monix.eval.TaskLike)monix.eval.TaskLike in interface monix.eval.TaskLike's type is different in current version, where it is (java.lang.Object)monix.eval.Task instead of (monix.eval.TaskLike)monix.eval.TaskLike
```
The former is a newly-added method as we changed the instances to be FunctionK. The latter looks like the summoner on a companion object which we still have - we never had `apply` on the instance before.

**Comment by alexandru** [comment]
@Avasil
> My use case for "unsafe" version was Observable because it can optimize on synchronous version.

I think `create` subsumes every other variant, right? 

Lets just supply a `createUnshifted` for now. How do you feel about a name like that?

**Comment by Avasil** [comment]
> I think `create` subsumes every other variant, right?

Yes. I checked and `Observable` is using `Task.async0` via `Task.create` in:
`lastOrElseL`, `firstOrElseL`, `completedL`, `foreachL` and `Consumer.apply` (+ tests). Those are methods that call callback only once per `Observable` lifetime so I suppose we actually don't need non-shifting variants after all.

`Task.fromFuture` on the other hand is used in few normal operators, including `mapTask` and `scanTask` so it could definitely be useful

> Lets just supply a `createUnshifted` for now. How do you feel about a name like that?

I don't like any name here :D As Oleg pointed out, we can't really have a descriptive name here. One version is always adding extra async boundary, the other isn't but the core of the issue is whether the `Task` callback is called directly or not which probably doesn't make a lot of sense to most users. So I guess `createUnshifted` is as good as anything else. Though now I'm thinking we should be good with just `Task.fromFutureXXX` and `Task.deferFutureXXX` variants.

**Comment by alexandru** [comment]
> Task.fromFuture on the other hand is used in few normal operators, including mapTask and scanTask so it could definitely be useful

I think that `Task.fromFuture` is precisely the operation that we shouldn't allow to have a non-forked version, because it's a design mistake.

Consider this:

```scala
def writeToFile(line: String): Future[Unit] = ???

// ...
stream.mapFuture(writeToFile)
```

If the `writeToFile` operation uses a `Scheduler.io` meant for blocking I/O operations, then the whole stream will be processed on that thread-pool, instead of those writes.

**Comment by alexandru** [comment]
Ah, wait, I see what you mean. I think we use it to optimize the `Ack` processing.

So, `Task.fromFuture` should not shift if the `Future` is already complete.
That should solve the issue.

**Comment by alexandru** [comment]
And yes, maybe we need an unshifted version for `Task.fromFuture` if it's extensively used in `Observable`.

So my proposal is this ... investigate current usage and lets add unshifted versions if it makes sense for those use-cases we have.

And those versions could be `internals` btw.

**Comment by alexandru** [comment]
I mean ... it would be nice to add those versions only if somebody begs for them 🙂

**Comment by alexandru** [comment]
One last proposal and I'm out ...

How about adding another item in `Task.Options`? 🤣

**Comment by oleg-py** [comment]
> How about adding another item in `Task.Options`? 🤣

That's what I suggested too 😆. @Avasil's objection was that it's meant to control the run-loop, and builders have little to do with it.

**Comment by Avasil** [comment]
Sure, I'll try to prepare something today. I'll also look at `Observable.fromFuture` if it doesn't need similar handling. Other methods taking `Future` should be fine because they work via `Task` conversion which uses safe `fromFuture`.

> One last proposal and I'm out ...
How about adding another item in Task.Options? 🤣

https://github.com/monix/monix/pull/921#issuecomment-513836690

**Comment by YulawOne** [comment]
Do you have plans doing something with https://github.com/monix/monix/issues/924? Or you don't see any binary compatibility issues for the possible fixes? I'm personally failing to find time to create PR with possible mitigation (at least for DCNF error classes) for the issue

**Comment by alexandru** [comment]
@YulawOne the handling of errors is an internal implementation detail and shouldn't break binary compatibility.

I don't know if there's anything to be done about that issue. The standard in Scala has been usage of `NonFatal` in order to let apps crash.

That said, the issue needs careful consideration, maybe we can improve it.

**Comment by Avasil** [comment]
Situation is vastly improved but we couldn't avoid breaking things for Local internals
