### ISSUE TITLE
add `isEmpty` to the ConcurrentQueue

### ISSUE THREAD

**Issue by dmgcodevil** [monix/monix#978]

**Comment by Avasil** [comment]
What's your use case @dmgcodevil ?

It's not very safe operation in context of `ConcurrentQueue` because the "emptiness" can change all the time

**Comment by dmgcodevil** [comment]
@Avasil yes, I understand that (same with `size`), but as I can see the underlying queue has `isEmpty` anyway. I solved my problem by using `tryPoll` , `None` means the queue is empty.  

> "emptiness" can change all the time
yes, but all I need to know if the queue is empty at the  given moment of time

**Comment by Avasil** [comment]
Is solution with `tryPoll` good enough? Implementing `isEmpty` should be easy but I'm hestitant to add more unsafe operators unless they are necessary to solve additional use cases

**Comment by dmgcodevil** [comment]
`tryPoll` works but awkward to use because you have to deal with a removed element. Why `isEmpty` is unsafe ?

**Comment by Avasil** [comment]
Sorry for late answer @dmgcodevil, I got caught up in other things and I have forgotten to respond.

> Why isEmpty is unsafe ?

AFAIK it is unsafe in similar way to `tryPoll` - any logic built on it can be very fragile so I wouldn't recommend it for general usage.

If it serves extra use case, we could add it. WDYT @alexandru ?

**Comment by alexandru** [comment]
I think adding `isEmpty` should be fine.

**Comment by pk044** [comment]
I could try implementing this if you don't mind :)

**Comment by Avasil** [comment]
@pk044 Sure, go ahead! Let us know if you have any questions
