### ISSUE TITLE
Proposal: add Task.flatMapLoop method

### ISSUE THREAD

**Issue by alexandru** [monix/monix#995]
I think this method would be cool to have on `Task`:

```scala
sealed abstract class Task[+A] {

  // ...

  def flatMapLoop[S](seed: S)(f: (A, S, S => Task[S]) => Task[S]): Task[S] =
    this.flatMap { a => f(a, seed, loop(_)(f)) }
}
```

Usage sample:

```scala
val random = Task(Random.nextInt())

random.flatMapLoop(Vector.empty[Int]) { (a, list, continue) =>
  val newList = list :+ a

  if (newList.length < 10)
    continue(newList)
  else
    Task.now(newList)
}
```

This saves us from describing a loop via `def`, which I find super annoying:

```scala
def loop(list: Vector[Int]): Task[Vector[Int]] =
  random.flatMap { a =>
    val newList = list :+ a

    if (newList.length < 10)
      loop(newList)
    else
      Task.now(newList)    
  }

loop(Vector.empty)
```

So it's a syntactic helper that's similar with `onErrorRestartLoop`.

---

TODO:

- [ ] check if there's already an alternative in [Cats](https://github.com/typelevel/cats) (when in doubt, ask on Cats's gitter :))
- [ ] get the signature right, one problem is that this looks like a `foldLeft`, however usually the order of params in `foldLeft` in Scala is `(S, A)` and not `(A, S)` (like we're doing here)
- [ ] also add it for `Coeval`

**Comment by alexandru** [comment]
Btw, this helper is super obvious — is it described anywhere? In Cats maybe?

**Comment by alexandru** [comment]
👍 let's call it flatMapLoop, has a nicer ring to it. Also search for an equivalent in Cats first.

**Comment by alexandru** [comment]
One issue we need to solve is to get the signature right — this function looks like a `foldLeft`:

```scala
def foldLeft[A, B](fa: F[A], b: B)(f: (B, A) => B): B
```

This is consistent with the definition from Haskell:

```haskell
foldl :: Foldable t => (b -> a -> b) -> b -> t a -> b
```

In other words maybe the signature should be:

```scala
def flatMapLoop[S](seed: S)(f: (S, A, S => Task[S]) => Task[S]): Task[S]
```

**Comment by alexandru** [comment]
Note that `foldRight` on the other hand is:

```haskell
foldr :: Foldable t => (a -> b -> b) -> b -> t a -> b
```

```scala
def foldRight[A, B](fa: F[A], lb: Eval[B])(f: (A, Eval[B]) => Eval[B]): Eval[B]
```

So maybe this is more like a foldRight 😂

**Comment by mudsam** [comment]
PR coming tonight (US Mountain Time). I was not able to find a similar method in cats. Currently working on a couple of test cases. Regarding the signature do you want to keep it as is or change it?

**Comment by alexandru** [comment]
Consistency with `onErrorRestartLoop` is important, so unless I hear objections, then we'll keep the signature.

**Comment by mudsam** [comment]
Will be delayed til tomorrow

**Comment by mudsam** [comment]
Anything else needed in the PR?

**Comment by Avasil** [comment]
Thank you for the PR @mudsam and sorry for the delay!
